// swad_action_list.h: action list

#ifndef _SWAD_ACT_LST
#define _SWAD_ACT_LST
/*
    SWAD (Shared Workspace At a Distance),
    is a web platform developed at the University of Granada (Spain),
    and used to support university teaching.

    This file is part of SWAD core.
    Copyright (C) 1999-2022 Antonio Cañas Vargas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*****************************************************************************/
/********************************** Headers **********************************/
/*****************************************************************************/

#include "swad_tab.h"

/*****************************************************************************/
/****************************** Public constants *****************************/
/*****************************************************************************/

/*****************************************************************************/
/************************* Not asociates with tabs ***************************/
/*****************************************************************************/
#define ActAll			 0

#define ActUnk			 1
#define ActMnu			 2

#define ActRefCon		 3

#define ActWebSvc		 4

/*****************************************************************************/
/********************************* Start tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActFrmLogIn		(ActWebSvc +   1)
#define ActReqSch		(ActWebSvc +   2)
#define ActSeeGblTL		(ActWebSvc +   3)
#define ActSeeSocPrf		(ActWebSvc +   4)
#define ActSeeCal		(ActWebSvc +   5)
#define ActSeeNtf		(ActWebSvc +   6)

// Secondary actions
#define ActLogIn		(ActWebSvc +   7)
#define ActLogInNew		(ActWebSvc +   8)
#define ActLogInLan		(ActWebSvc +   9)
#define ActAnnSee		(ActWebSvc +  10)
#define ActReqSndNewPwd		(ActWebSvc +  11)
#define ActSndNewPwd		(ActWebSvc +  12)
#define ActLogOut		(ActWebSvc +  13)

#define ActSch			(ActWebSvc +  14)

#define ActRefNewPubGblTL	(ActWebSvc +  15)
#define ActRefOldPubGblTL	(ActWebSvc +  16)
#define ActRcvPstGblTL		(ActWebSvc +  17)
#define ActRcvComGblTL		(ActWebSvc +  18)
#define ActShoHidComGblTL	(ActWebSvc +  19)
#define ActAllShaNotGblTL	(ActWebSvc +  20)
#define ActAllFavNotGblTL	(ActWebSvc +  21)
#define ActAllFavComGblTL	(ActWebSvc +  22)
#define ActShaNotGblTL		(ActWebSvc +  23)
#define ActUnsNotGblTL		(ActWebSvc +  24)
#define ActFavNotGblTL		(ActWebSvc +  25)
#define ActUnfNotGblTL		(ActWebSvc +  26)
#define ActFavComGblTL		(ActWebSvc +  27)
#define ActUnfComGblTL		(ActWebSvc +  28)
#define ActReqRemPubGblTL	(ActWebSvc +  29)
#define ActRemPubGblTL		(ActWebSvc +  30)
#define ActReqRemComGblTL	(ActWebSvc +  31)
#define ActRemComGblTL		(ActWebSvc +  32)

#define ActReqOthPubPrf		(ActWebSvc +  33)

#define ActRefOldPubUsrTL	(ActWebSvc +  34)
#define ActRcvPstUsrTL		(ActWebSvc +  35)
#define ActRcvComUsrTL		(ActWebSvc +  36)
#define ActShoHidComUsrTL	(ActWebSvc +  37)
#define ActAllShaNotUsrTL	(ActWebSvc +  38)
#define ActAllFavNotUsrTL	(ActWebSvc +  39)
#define ActAllFavComUsrTL	(ActWebSvc +  40)
#define ActShaNotUsrTL		(ActWebSvc +  41)
#define ActUnsNotUsrTL		(ActWebSvc +  42)
#define ActFavNotUsrTL		(ActWebSvc +  43)
#define ActUnfNotUsrTL		(ActWebSvc +  44)
#define ActFavComUsrTL		(ActWebSvc +  45)
#define ActUnfComUsrTL		(ActWebSvc +  46)
#define ActReqRemPubUsrTL	(ActWebSvc +  47)
#define ActRemPubUsrTL		(ActWebSvc +  48)
#define ActReqRemComUsrTL	(ActWebSvc +  49)
#define ActRemComUsrTL		(ActWebSvc +  50)

#define ActSeeOthPubPrf		(ActWebSvc +  51)
#define ActCalFig		(ActWebSvc +  52)

#define ActFolUsr		(ActWebSvc +  53)
#define ActUnfUsr		(ActWebSvc +  54)
#define ActSeeFlg		(ActWebSvc +  55)
#define ActSeeFlr		(ActWebSvc +  56)

#define ActPrnCal		(ActWebSvc +  57)
#define ActChgCal1stDay		(ActWebSvc +  58)

#define ActSeeNewNtf		(ActWebSvc +  59)
#define ActMrkNtfSee		(ActWebSvc +  60)
#define ActSeeMai		(ActWebSvc +  61)
#define ActEdiMai		(ActWebSvc +  62)
#define ActNewMai		(ActWebSvc +  63)
#define ActRemMai		(ActWebSvc +  64)
#define ActRenMaiSho		(ActWebSvc +  65)
#define ActRenMaiFul		(ActWebSvc +  66)

/*****************************************************************************/
/******************************** System tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeSysInf		(ActRenMaiFul +  1)
#define ActSeeCty		(ActRenMaiFul +  2)
#define ActSeePen		(ActRenMaiFul +  3)
#define ActSeeLnk		(ActRenMaiFul +  4)
#define ActLstPlg		(ActRenMaiFul +  5)
#define ActMtn			(ActRenMaiFul +  6)

// Secondary actions
#define ActPrnSysInf		(ActRenMaiFul +  7)

#define ActEdiCty		(ActRenMaiFul +  8)
#define ActNewCty		(ActRenMaiFul +  9)
#define ActRemCty		(ActRenMaiFul + 10)
#define ActRenCty		(ActRenMaiFul + 11)
#define ActChgCtyWWW		(ActRenMaiFul + 12)

#define ActSeeBan		(ActRenMaiFul + 13)
#define ActEdiBan		(ActRenMaiFul + 14)
#define ActNewBan		(ActRenMaiFul + 15)
#define ActRemBan		(ActRenMaiFul + 16)
#define ActUnhBan		(ActRenMaiFul + 17)
#define ActHidBan		(ActRenMaiFul + 18)
#define ActRenBanSho		(ActRenMaiFul + 19)
#define ActRenBanFul		(ActRenMaiFul + 20)
#define ActChgBanImg		(ActRenMaiFul + 21)
#define ActChgBanWWW		(ActRenMaiFul + 22)
#define ActClkBan		(ActRenMaiFul + 23)

#define ActEdiLnk		(ActRenMaiFul + 24)
#define ActNewLnk		(ActRenMaiFul + 25)
#define ActRemLnk		(ActRenMaiFul + 26)
#define ActRenLnkSho		(ActRenMaiFul + 27)
#define ActRenLnkFul		(ActRenMaiFul + 28)
#define ActChgLnkWWW		(ActRenMaiFul + 29)

#define ActEdiPlg		(ActRenMaiFul + 30)
#define ActNewPlg		(ActRenMaiFul + 31)
#define ActRemPlg		(ActRenMaiFul + 32)
#define ActRenPlg		(ActRenMaiFul + 33)
#define ActChgPlgDes		(ActRenMaiFul + 34)
#define ActChgPlgLog		(ActRenMaiFul + 35)
#define ActChgPlgAppKey		(ActRenMaiFul + 36)
#define ActChgPlgURL		(ActRenMaiFul + 37)
#define ActChgPlgIP		(ActRenMaiFul + 38)

#define ActSetUp		(ActRenMaiFul + 39)
#define ActReqRemOldCrs		(ActRenMaiFul + 40)
#define ActRemOldCrs		(ActRenMaiFul + 41)

/*****************************************************************************/
/******************************** Country tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCtyInf		(ActRemOldCrs +  1)
#define ActSeeIns		(ActRemOldCrs +  2)

// Secondary actions
#define ActPrnCtyInf		(ActRemOldCrs +  3)
#define ActChgCtyMapAtt		(ActRemOldCrs +  4)

#define ActEdiIns		(ActRemOldCrs +  5)
#define ActReqIns		(ActRemOldCrs +  6)
#define ActNewIns		(ActRemOldCrs +  7)
#define ActRemIns		(ActRemOldCrs +  8)
#define ActRenInsSho		(ActRemOldCrs +  9)
#define ActRenInsFul		(ActRemOldCrs + 10)
#define ActChgInsWWW		(ActRemOldCrs + 11)
#define ActChgInsSta		(ActRemOldCrs + 12)

/*****************************************************************************/
/****************************** Institution tab ******************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeInsInf		(ActChgInsSta +  1)
#define ActSeeCtr		(ActChgInsSta +  2)
#define ActSeePlc		(ActChgInsSta +  3)
#define ActSeeDpt		(ActChgInsSta +  4)
#define ActSeeHld		(ActChgInsSta +  5)

// Secondary actions
#define ActPrnInsInf		(ActChgInsSta +  6)
#define ActChgInsCtyCfg		(ActChgInsSta +  7)
#define ActRenInsShoCfg		(ActChgInsSta +  8)
#define ActRenInsFulCfg		(ActChgInsSta +  9)
#define ActChgInsWWWCfg		(ActChgInsSta + 10)
#define ActReqInsLog		(ActChgInsSta + 11)
#define ActRecInsLog		(ActChgInsSta + 12)
#define ActRemInsLog		(ActChgInsSta + 13)

#define ActEdiCtr		(ActChgInsSta + 14)
#define ActReqCtr		(ActChgInsSta + 15)
#define ActNewCtr		(ActChgInsSta + 16)
#define ActRemCtr		(ActChgInsSta + 17)
#define ActChgCtrPlc		(ActChgInsSta + 18)
#define ActRenCtrSho		(ActChgInsSta + 19)
#define ActRenCtrFul		(ActChgInsSta + 20)
#define ActChgCtrWWW		(ActChgInsSta + 21)
#define ActChgCtrSta		(ActChgInsSta + 22)

#define ActEdiPlc		(ActChgInsSta + 23)
#define ActNewPlc		(ActChgInsSta + 24)
#define ActRemPlc		(ActChgInsSta + 25)
#define ActRenPlcSho		(ActChgInsSta + 26)
#define ActRenPlcFul		(ActChgInsSta + 27)

#define ActEdiDpt		(ActChgInsSta + 28)
#define ActNewDpt		(ActChgInsSta + 29)
#define ActRemDpt		(ActChgInsSta + 30)
#define ActChgDptIns		(ActChgInsSta + 31)
#define ActRenDptSho		(ActChgInsSta + 32)
#define ActRenDptFul		(ActChgInsSta + 33)
#define ActChgDptWWW		(ActChgInsSta + 34)

#define ActEdiHld		(ActChgInsSta + 35)
#define ActNewHld		(ActChgInsSta + 36)
#define ActRemHld		(ActChgInsSta + 37)
#define ActChgHldPlc		(ActChgInsSta + 38)
#define ActChgHldTyp		(ActChgInsSta + 39)
#define ActChgHldStrDat		(ActChgInsSta + 40)
#define ActChgHldEndDat		(ActChgInsSta + 41)
#define ActRenHld		(ActChgInsSta + 42)

/*****************************************************************************/
/********************************* Center tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCtrInf		(ActRenHld +  1)
#define ActSeeDeg		(ActRenHld +  2)
#define ActSeeBld		(ActRenHld +  3)
#define ActSeeRoo		(ActRenHld +  4)

// Secondary actions
#define ActPrnCtrInf		(ActRenHld +  5)
#define ActChgCtrInsCfg		(ActRenHld +  6)
#define ActRenCtrShoCfg		(ActRenHld +  7)
#define ActRenCtrFulCfg		(ActRenHld +  8)
#define ActChgCtrPlcCfg		(ActRenHld +  9)
#define ActChgCtrLatCfg		(ActRenHld + 10)
#define ActChgCtrLgtCfg		(ActRenHld + 11)
#define ActChgCtrAltCfg		(ActRenHld + 12)
#define ActChgCtrWWWCfg		(ActRenHld + 13)
#define ActReqCtrLog		(ActRenHld + 14)
#define ActRecCtrLog		(ActRenHld + 15)
#define ActRemCtrLog		(ActRenHld + 16)
#define ActReqCtrPho		(ActRenHld + 17)
#define ActRecCtrPho		(ActRenHld + 18)
#define ActChgCtrPhoAtt		(ActRenHld + 19)

#define ActSeeDegTyp		(ActRenHld + 20)
#define ActEdiDegTyp		(ActRenHld + 21)
#define ActNewDegTyp		(ActRenHld + 22)
#define ActRemDegTyp		(ActRenHld + 23)
#define ActRenDegTyp		(ActRenHld + 24)

#define ActEdiDeg		(ActRenHld + 25)
#define ActReqDeg		(ActRenHld + 26)
#define ActNewDeg		(ActRenHld + 27)
#define ActRemDeg		(ActRenHld + 28)
#define ActRenDegSho		(ActRenHld + 29)
#define ActRenDegFul		(ActRenHld + 30)
#define ActChgDegTyp		(ActRenHld + 31)
#define ActChgDegWWW		(ActRenHld + 32)
#define ActChgDegSta		(ActRenHld + 33)

#define ActEdiBld		(ActRenHld + 34)
#define ActNewBld		(ActRenHld + 35)
#define ActRemBld		(ActRenHld + 36)
#define ActRenBldSho		(ActRenHld + 37)
#define ActRenBldFul		(ActRenHld + 38)
#define ActRenBldLoc		(ActRenHld + 39)

#define ActEdiRoo		(ActRenHld + 40)
#define ActNewRoo		(ActRenHld + 41)
#define ActRemRoo		(ActRenHld + 42)
#define ActChgRooBld		(ActRenHld + 43)
#define ActChgRooFlo		(ActRenHld + 44)
#define ActChgRooTyp		(ActRenHld + 45)
#define ActRenRooSho		(ActRenHld + 46)
#define ActRenRooFul		(ActRenHld + 47)
#define ActChgRooMaxUsr		(ActRenHld + 48)
#define ActChgRooMAC		(ActRenHld + 49)

/*****************************************************************************/
/********************************* Degree tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeDegInf		(ActChgRooMAC +  1)
#define ActSeeCrs		(ActChgRooMAC +  2)

// Secondary actions
#define ActPrnDegInf		(ActChgRooMAC +  3)
#define ActChgDegCtrCfg		(ActChgRooMAC +  4)
#define ActRenDegShoCfg		(ActChgRooMAC +  5)
#define ActRenDegFulCfg		(ActChgRooMAC +  6)
#define ActChgDegWWWCfg		(ActChgRooMAC +  7)
#define ActReqDegLog		(ActChgRooMAC +  8)
#define ActRecDegLog		(ActChgRooMAC +  9)
#define ActRemDegLog		(ActChgRooMAC + 10)

#define ActEdiCrs		(ActChgRooMAC + 11)
#define ActReqCrs		(ActChgRooMAC + 12)
#define ActNewCrs		(ActChgRooMAC + 13)
#define ActRemCrs		(ActChgRooMAC + 14)
#define ActChgInsCrsCod		(ActChgRooMAC + 15)
#define ActChgCrsYea		(ActChgRooMAC + 16)
#define ActRenCrsSho		(ActChgRooMAC + 17)
#define ActRenCrsFul		(ActChgRooMAC + 18)
#define ActChgCrsSta		(ActChgRooMAC + 19)

/*****************************************************************************/
/******************************** Course tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCrsInf		(ActChgCrsSta +   1)
#define ActSeePrg		(ActChgCrsSta +   2)
#define ActSeeTchGui		(ActChgCrsSta +   3)
#define ActSeeSyl		(ActChgCrsSta +   4)
#define ActSeeBib		(ActChgCrsSta +   5)
#define ActSeeFAQ		(ActChgCrsSta +   6)
#define ActSeeCrsLnk		(ActChgCrsSta +   7)
#define ActSeeAss		(ActChgCrsSta +   8)
#define ActSeeCrsTT		(ActChgCrsSta +   9)

// Secondary actions
#define ActPrnCrsInf		(ActChgCrsSta +  10)
#define ActChgCrsDegCfg		(ActChgCrsSta +  11)
#define ActRenCrsShoCfg		(ActChgCrsSta +  12)
#define ActRenCrsFulCfg		(ActChgCrsSta +  13)
#define ActChgInsCrsCodCfg	(ActChgCrsSta +  14)
#define ActChgCrsYeaCfg		(ActChgCrsSta +  15)
#define ActEdiCrsInf		(ActChgCrsSta +  16)
#define ActEdiPrg		(ActChgCrsSta +  17)
#define ActSeePrgItm		(ActChgCrsSta +  18)
#define ActFrmChgPrgItm		(ActChgCrsSta +  19)
#define ActFrmNewPrgItm		(ActChgCrsSta +  20)
#define ActChgPrgItm		(ActChgCrsSta +  21)
#define ActNewPrgItm		(ActChgCrsSta +  22)
#define ActReqRemPrgItm		(ActChgCrsSta +  23)
#define ActRemPrgItm		(ActChgCrsSta +  24)
#define ActHidPrgItm		(ActChgCrsSta +  25)
#define ActUnhPrgItm		(ActChgCrsSta +  26)
#define ActUp_PrgItm		(ActChgCrsSta +  27)
#define ActDwnPrgItm		(ActChgCrsSta +  28)
#define ActLftPrgItm		(ActChgCrsSta +  29)
#define ActRgtPrgItm		(ActChgCrsSta +  30)
#define ActExpSeePrgItm		(ActChgCrsSta +  31)
#define ActConSeePrgItm		(ActChgCrsSta +  32)
#define ActExpEdiPrgItm		(ActChgCrsSta +  33)
#define ActConEdiPrgItm		(ActChgCrsSta +  34)
#define ActFrmSeePrgRsc		(ActChgCrsSta +  35)
#define ActFrmEdiPrgRsc		(ActChgCrsSta +  36)
#define ActNewPrgRsc		(ActChgCrsSta +  37)
#define ActRenPrgRsc		(ActChgCrsSta +  38)
#define ActReqRemPrgRsc		(ActChgCrsSta +  39)
#define ActRemPrgRsc		(ActChgCrsSta +  40)
#define ActHidPrgRsc		(ActChgCrsSta +  41)
#define ActUnhPrgRsc		(ActChgCrsSta +  42)
#define ActUp_PrgRsc		(ActChgCrsSta +  43)
#define ActDwnPrgRsc		(ActChgCrsSta +  44)
#define ActSeeCliPrgRsc		(ActChgCrsSta +  45)
#define ActChgLnkPrgRsc		(ActChgCrsSta +  46)
#define ActEdiTchGui		(ActChgCrsSta +  47)
#define ActSeeSylLec		(ActChgCrsSta +  48)
#define ActSeeSylPra		(ActChgCrsSta +  49)
#define ActEdiSylLec		(ActChgCrsSta +  50)
#define ActEdiSylPra		(ActChgCrsSta +  51)
#define ActDelItmSylLec		(ActChgCrsSta +  52)
#define ActDelItmSylPra		(ActChgCrsSta +  53)
#define ActUp_IteSylLec		(ActChgCrsSta +  54)
#define ActUp_IteSylPra		(ActChgCrsSta +  55)
#define ActDwnIteSylLec		(ActChgCrsSta +  56)
#define ActDwnIteSylPra		(ActChgCrsSta +  57)
#define ActRgtIteSylLec		(ActChgCrsSta +  58)
#define ActRgtIteSylPra		(ActChgCrsSta +  59)
#define ActLftIteSylLec		(ActChgCrsSta +  60)
#define ActLftIteSylPra		(ActChgCrsSta +  61)
#define ActInsIteSylLec		(ActChgCrsSta +  62)
#define ActInsIteSylPra		(ActChgCrsSta +  63)
#define ActModIteSylLec		(ActChgCrsSta +  64)
#define ActModIteSylPra		(ActChgCrsSta +  65)

#define ActEdiBib		(ActChgCrsSta +  66)
#define ActEdiFAQ		(ActChgCrsSta +  67)
#define ActEdiCrsLnk		(ActChgCrsSta +  68)
#define ActEdiAss		(ActChgCrsSta +  69)

#define ActChgFrcReaCrsInf	(ActChgCrsSta +  70)
#define ActChgFrcReaTchGui	(ActChgCrsSta +  71)
#define ActChgFrcReaSylLec	(ActChgCrsSta +  72)
#define ActChgFrcReaSylPra	(ActChgCrsSta +  73)
#define ActChgFrcReaBib		(ActChgCrsSta +  74)
#define ActChgFrcReaFAQ		(ActChgCrsSta +  75)
#define ActChgFrcReaCrsLnk	(ActChgCrsSta +  76)
#define ActChgFrcReaAss		(ActChgCrsSta +  77)

#define ActChgHavReaCrsInf	(ActChgCrsSta +  78)
#define ActChgHavReaTchGui	(ActChgCrsSta +  79)
#define ActChgHavReaSylLec	(ActChgCrsSta +  80)
#define ActChgHavReaSylPra	(ActChgCrsSta +  81)
#define ActChgHavReaBib		(ActChgCrsSta +  82)
#define ActChgHavReaFAQ		(ActChgCrsSta +  83)
#define ActChgHavReaCrsLnk	(ActChgCrsSta +  84)
#define ActChgHavReaAss		(ActChgCrsSta +  85)

#define ActSelInfSrcCrsInf	(ActChgCrsSta +  86)
#define ActSelInfSrcTchGui	(ActChgCrsSta +  87)
#define ActSelInfSrcSylLec	(ActChgCrsSta +  88)
#define ActSelInfSrcSylPra	(ActChgCrsSta +  89)
#define ActSelInfSrcBib		(ActChgCrsSta +  90)
#define ActSelInfSrcFAQ		(ActChgCrsSta +  91)
#define ActSelInfSrcCrsLnk	(ActChgCrsSta +  92)
#define ActSelInfSrcAss		(ActChgCrsSta +  93)

#define ActRcvURLCrsInf		(ActChgCrsSta +  94)
#define ActRcvURLTchGui		(ActChgCrsSta +  95)
#define ActRcvURLSylLec		(ActChgCrsSta +  96)
#define ActRcvURLSylPra		(ActChgCrsSta +  97)
#define ActRcvURLBib		(ActChgCrsSta +  98)
#define ActRcvURLFAQ		(ActChgCrsSta +  99)
#define ActRcvURLCrsLnk		(ActChgCrsSta + 100)
#define ActRcvURLAss		(ActChgCrsSta + 101)

#define ActRcvPagCrsInf		(ActChgCrsSta + 102)
#define ActRcvPagTchGui		(ActChgCrsSta + 103)
#define ActRcvPagSylLec		(ActChgCrsSta + 104)
#define ActRcvPagSylPra		(ActChgCrsSta + 105)
#define ActRcvPagBib		(ActChgCrsSta + 106)
#define ActRcvPagFAQ		(ActChgCrsSta + 107)
#define ActRcvPagCrsLnk		(ActChgCrsSta + 108)
#define ActRcvPagAss		(ActChgCrsSta + 109)

#define ActEditorCrsInf		(ActChgCrsSta + 110)
#define ActEditorTchGui		(ActChgCrsSta + 111)
#define ActEditorSylLec		(ActChgCrsSta + 112)
#define ActEditorSylPra		(ActChgCrsSta + 113)
#define ActEditorBib		(ActChgCrsSta + 114)
#define ActEditorFAQ		(ActChgCrsSta + 115)
#define ActEditorCrsLnk		(ActChgCrsSta + 116)
#define ActEditorAss		(ActChgCrsSta + 117)

#define ActPlaTxtEdiCrsInf	(ActChgCrsSta + 118)
#define ActPlaTxtEdiTchGui	(ActChgCrsSta + 119)
#define ActPlaTxtEdiSylLec	(ActChgCrsSta + 120)
#define ActPlaTxtEdiSylPra	(ActChgCrsSta + 121)
#define ActPlaTxtEdiBib		(ActChgCrsSta + 122)
#define ActPlaTxtEdiFAQ		(ActChgCrsSta + 123)
#define ActPlaTxtEdiCrsLnk	(ActChgCrsSta + 124)
#define ActPlaTxtEdiAss		(ActChgCrsSta + 125)

#define ActRchTxtEdiCrsInf	(ActChgCrsSta + 126)
#define ActRchTxtEdiTchGui	(ActChgCrsSta + 127)
#define ActRchTxtEdiSylLec	(ActChgCrsSta + 128)
#define ActRchTxtEdiSylPra	(ActChgCrsSta + 129)
#define ActRchTxtEdiBib		(ActChgCrsSta + 130)
#define ActRchTxtEdiFAQ		(ActChgCrsSta + 131)
#define ActRchTxtEdiCrsLnk	(ActChgCrsSta + 132)
#define ActRchTxtEdiAss		(ActChgCrsSta + 133)

#define ActRcvPlaTxtCrsInf	(ActChgCrsSta + 134)
#define ActRcvPlaTxtTchGui	(ActChgCrsSta + 135)
#define ActRcvPlaTxtSylLec	(ActChgCrsSta + 136)
#define ActRcvPlaTxtSylPra	(ActChgCrsSta + 137)
#define ActRcvPlaTxtBib		(ActChgCrsSta + 138)
#define ActRcvPlaTxtFAQ		(ActChgCrsSta + 139)
#define ActRcvPlaTxtCrsLnk	(ActChgCrsSta + 140)
#define ActRcvPlaTxtAss		(ActChgCrsSta + 141)

#define ActRcvRchTxtCrsInf	(ActChgCrsSta + 142)
#define ActRcvRchTxtTchGui	(ActChgCrsSta + 143)
#define ActRcvRchTxtSylLec	(ActChgCrsSta + 144)
#define ActRcvRchTxtSylPra	(ActChgCrsSta + 145)
#define ActRcvRchTxtBib		(ActChgCrsSta + 146)
#define ActRcvRchTxtFAQ		(ActChgCrsSta + 147)
#define ActRcvRchTxtCrsLnk	(ActChgCrsSta + 148)
#define ActRcvRchTxtAss		(ActChgCrsSta + 149)

#define ActPrnCrsTT		(ActChgCrsSta + 150)
#define ActEdiCrsTT		(ActChgCrsSta + 151)
#define ActChgCrsTT		(ActChgCrsSta + 152)
#define ActChgCrsTT1stDay	(ActChgCrsSta + 153)

/*****************************************************************************/
/***************************** Assessment tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAsg		(ActChgCrsTT1stDay +   1)
#define ActSeePrj		(ActChgCrsTT1stDay +   2)
#define ActSeeAllCfe		(ActChgCrsTT1stDay +   3)
#define ActEdiTstQst		(ActChgCrsTT1stDay +   4)
#define ActReqTst		(ActChgCrsTT1stDay +   5)
#define ActSeeAllExa		(ActChgCrsTT1stDay +   6)
#define ActSeeAllGam		(ActChgCrsTT1stDay +   7)
#define ActSeeAllRub		(ActChgCrsTT1stDay +   8)

// Secondary actions
#define ActFrmNewAsg		(ActChgCrsTT1stDay +   9)
#define ActEdiOneAsg		(ActChgCrsTT1stDay +  10)
#define ActSeeOneAsg		(ActChgCrsTT1stDay +  11)
#define ActPrnOneAsg		(ActChgCrsTT1stDay +  12)
#define ActNewAsg		(ActChgCrsTT1stDay +  13)
#define ActChgAsg		(ActChgCrsTT1stDay +  14)
#define ActReqRemAsg		(ActChgCrsTT1stDay +  15)
#define ActRemAsg		(ActChgCrsTT1stDay +  16)
#define ActHidAsg		(ActChgCrsTT1stDay +  17)
#define ActUnhAsg		(ActChgCrsTT1stDay +  18)
#define ActReqLnkAsg		(ActChgCrsTT1stDay +  19)

#define ActReqUsrPrj		(ActChgCrsTT1stDay +  20)
#define ActSeeTblAllPrj		(ActChgCrsTT1stDay +  21)
#define ActCfgPrj		(ActChgCrsTT1stDay +  22)
#define ActRcvCfgPrj		(ActChgCrsTT1stDay +  23)
#define ActReqLckAllPrj		(ActChgCrsTT1stDay +  24)
#define ActReqUnlAllPrj		(ActChgCrsTT1stDay +  25)
#define ActLckAllPrj		(ActChgCrsTT1stDay +  26)
#define ActUnlAllPrj		(ActChgCrsTT1stDay +  27)
#define ActFrmNewPrj		(ActChgCrsTT1stDay +  28)
#define ActEdiOnePrj		(ActChgCrsTT1stDay +  29)
#define ActSeeOnePrj		(ActChgCrsTT1stDay +  30)
#define ActPrnOnePrj		(ActChgCrsTT1stDay +  31)
#define ActNewPrj		(ActChgCrsTT1stDay +  32)
#define ActChgPrj		(ActChgCrsTT1stDay +  33)
#define ActReqRemPrj		(ActChgCrsTT1stDay +  34)
#define ActRemPrj		(ActChgCrsTT1stDay +  35)
#define ActHidPrj		(ActChgCrsTT1stDay +  36)
#define ActUnhPrj		(ActChgCrsTT1stDay +  37)
#define ActLckPrj		(ActChgCrsTT1stDay +  38)
#define ActUnlPrj		(ActChgCrsTT1stDay +  39)
#define ActChgPrjRev		(ActChgCrsTT1stDay +  40)
#define ActReqAddStdPrj		(ActChgCrsTT1stDay +  41)
#define ActReqAddTutPrj		(ActChgCrsTT1stDay +  42)
#define ActReqAddEvlPrj		(ActChgCrsTT1stDay +  43)
#define ActAddStdPrj		(ActChgCrsTT1stDay +  44)
#define ActAddTutPrj		(ActChgCrsTT1stDay +  45)
#define ActAddEvlPrj		(ActChgCrsTT1stDay +  46)
#define ActReqRemStdPrj		(ActChgCrsTT1stDay +  47)
#define ActReqRemTutPrj		(ActChgCrsTT1stDay +  48)
#define ActReqRemEvlPrj		(ActChgCrsTT1stDay +  49)
#define ActRemStdPrj		(ActChgCrsTT1stDay +  50)
#define ActRemTutPrj		(ActChgCrsTT1stDay +  51)
#define ActRemEvlPrj		(ActChgCrsTT1stDay +  52)
#define ActReqLnkPrj		(ActChgCrsTT1stDay +  53)

#define ActAdmDocPrj		(ActChgCrsTT1stDay +  54)
#define ActReqRemFilDocPrj	(ActChgCrsTT1stDay +  55)
#define ActRemFilDocPrj		(ActChgCrsTT1stDay +  56)
#define ActRemFolDocPrj		(ActChgCrsTT1stDay +  57)
#define ActCopDocPrj		(ActChgCrsTT1stDay +  58)
#define ActPasDocPrj		(ActChgCrsTT1stDay +  59)
#define ActRemTreDocPrj		(ActChgCrsTT1stDay +  60)
#define ActFrmCreDocPrj		(ActChgCrsTT1stDay +  61)
#define ActCreFolDocPrj		(ActChgCrsTT1stDay +  62)
#define ActCreLnkDocPrj		(ActChgCrsTT1stDay +  63)
#define ActRenFolDocPrj		(ActChgCrsTT1stDay +  64)
#define ActRcvFilDocPrjDZ	(ActChgCrsTT1stDay +  65)
#define ActRcvFilDocPrjCla	(ActChgCrsTT1stDay +  66)
#define ActExpDocPrj		(ActChgCrsTT1stDay +  67)
#define ActConDocPrj		(ActChgCrsTT1stDay +  68)
#define ActZIPDocPrj		(ActChgCrsTT1stDay +  69)
#define ActReqDatDocPrj		(ActChgCrsTT1stDay +  70)
#define ActChgDatDocPrj		(ActChgCrsTT1stDay +  71)
#define ActDowDocPrj		(ActChgCrsTT1stDay +  72)

#define ActAdmAssPrj		(ActChgCrsTT1stDay +  73)
#define ActReqRemFilAssPrj	(ActChgCrsTT1stDay +  74)
#define ActRemFilAssPrj		(ActChgCrsTT1stDay +  75)
#define ActRemFolAssPrj		(ActChgCrsTT1stDay +  76)
#define ActCopAssPrj		(ActChgCrsTT1stDay +  77)
#define ActPasAssPrj		(ActChgCrsTT1stDay +  78)
#define ActRemTreAssPrj		(ActChgCrsTT1stDay +  79)
#define ActFrmCreAssPrj		(ActChgCrsTT1stDay +  80)
#define ActCreFolAssPrj		(ActChgCrsTT1stDay +  81)
#define ActCreLnkAssPrj		(ActChgCrsTT1stDay +  82)
#define ActRenFolAssPrj		(ActChgCrsTT1stDay +  83)
#define ActRcvFilAssPrjDZ	(ActChgCrsTT1stDay +  84)
#define ActRcvFilAssPrjCla	(ActChgCrsTT1stDay +  85)
#define ActExpAssPrj		(ActChgCrsTT1stDay +  86)
#define ActConAssPrj		(ActChgCrsTT1stDay +  87)
#define ActZIPAssPrj		(ActChgCrsTT1stDay +  88)
#define ActReqDatAssPrj		(ActChgCrsTT1stDay +  89)
#define ActChgDatAssPrj		(ActChgCrsTT1stDay +  90)
#define ActDowAssPrj		(ActChgCrsTT1stDay +  91)

#define ActSeeOneCfe		(ActChgCrsTT1stDay +  92)
#define ActSeeDatCfe		(ActChgCrsTT1stDay +  93)
#define ActEdiCfe		(ActChgCrsTT1stDay +  94)
#define ActRcvCfe		(ActChgCrsTT1stDay +  95)
#define ActPrnCfe		(ActChgCrsTT1stDay +  96)
#define ActReqRemCfe		(ActChgCrsTT1stDay +  97)
#define ActRemCfe		(ActChgCrsTT1stDay +  98)
#define ActHidCfe		(ActChgCrsTT1stDay +  99)
#define ActUnhCfe		(ActChgCrsTT1stDay + 100)
#define ActReqLnkCfe		(ActChgCrsTT1stDay + 101)

#define ActEdiOneTstQst		(ActChgCrsTT1stDay + 102)
#define ActReqImpTstQst		(ActChgCrsTT1stDay + 103)
#define ActImpTstQst		(ActChgCrsTT1stDay + 104)
#define ActLstTstQst		(ActChgCrsTT1stDay + 105)
#define ActRcvTstQst		(ActChgCrsTT1stDay + 106)
#define ActReqRemSevTstQst	(ActChgCrsTT1stDay + 107)
#define ActRemSevTstQst		(ActChgCrsTT1stDay + 108)
#define ActReqRemOneTstQst	(ActChgCrsTT1stDay + 109)
#define ActRemOneTstQst		(ActChgCrsTT1stDay + 110)
#define ActChgShfTstQst		(ActChgCrsTT1stDay + 111)

#define ActEdiTag		(ActChgCrsTT1stDay + 112)
#define ActEnaTag		(ActChgCrsTT1stDay + 113)
#define ActDisTag		(ActChgCrsTT1stDay + 114)
#define ActRenTag		(ActChgCrsTT1stDay + 115)

#define ActSeeTst		(ActChgCrsTT1stDay + 116)
#define ActReqAssTst		(ActChgCrsTT1stDay + 117)
#define ActAssTst		(ActChgCrsTT1stDay + 118)
#define ActCfgTst		(ActChgCrsTT1stDay + 119)
#define ActRcvCfgTst		(ActChgCrsTT1stDay + 120)

#define ActReqSeeMyTstRes	(ActChgCrsTT1stDay + 121)
#define ActSeeMyTstResCrs	(ActChgCrsTT1stDay + 122)
#define ActSeeOneTstResMe	(ActChgCrsTT1stDay + 123)
#define ActReqSeeUsrTstRes	(ActChgCrsTT1stDay + 124)
#define ActSeeUsrTstResCrs	(ActChgCrsTT1stDay + 125)
#define ActSeeOneTstResOth	(ActChgCrsTT1stDay + 126)

#define ActSeeExa		(ActChgCrsTT1stDay + 127)

#define ActFrmNewExa		(ActChgCrsTT1stDay + 128)
#define ActEdiOneExa		(ActChgCrsTT1stDay + 129)
#define ActNewExa		(ActChgCrsTT1stDay + 130)
#define ActChgExa		(ActChgCrsTT1stDay + 131)
#define ActReqRemExa		(ActChgCrsTT1stDay + 132)
#define ActRemExa		(ActChgCrsTT1stDay + 133)
#define ActHidExa		(ActChgCrsTT1stDay + 134)
#define ActUnhExa		(ActChgCrsTT1stDay + 135)
#define ActReqLnkExa		(ActChgCrsTT1stDay + 136)

#define ActFrmNewExaSet		(ActChgCrsTT1stDay + 137)
#define ActNewExaSet		(ActChgCrsTT1stDay + 138)
#define ActReqRemExaSet		(ActChgCrsTT1stDay + 139)
#define ActRemExaSet		(ActChgCrsTT1stDay + 140)
#define ActUp_ExaSet		(ActChgCrsTT1stDay + 141)
#define ActDwnExaSet		(ActChgCrsTT1stDay + 142)
#define ActChgTitExaSet		(ActChgCrsTT1stDay + 143)
#define ActChgNumQstExaSet	(ActChgCrsTT1stDay + 144)

#define ActReqAddQstExaSet	(ActChgCrsTT1stDay + 145)
#define ActLstTstQstForSet	(ActChgCrsTT1stDay + 146)
#define ActAddQstToExa		(ActChgCrsTT1stDay + 147)
#define ActReqRemSetQst		(ActChgCrsTT1stDay + 148)
#define ActRemExaQst		(ActChgCrsTT1stDay + 149)
#define ActValSetQst		(ActChgCrsTT1stDay + 150)
#define ActInvSetQst		(ActChgCrsTT1stDay + 151)

#define ActReqNewExaSes		(ActChgCrsTT1stDay + 152)
#define ActEdiOneExaSes		(ActChgCrsTT1stDay + 153)
#define ActNewExaSes		(ActChgCrsTT1stDay + 154)
#define ActChgExaSes		(ActChgCrsTT1stDay + 155)
#define ActReqRemExaSes		(ActChgCrsTT1stDay + 156)
#define ActRemExaSes		(ActChgCrsTT1stDay + 157)
#define ActHidExaSes		(ActChgCrsTT1stDay + 158)
#define ActUnhExaSes		(ActChgCrsTT1stDay + 159)

#define ActSeeExaPrn		(ActChgCrsTT1stDay + 160)
#define ActAnsExaPrn		(ActChgCrsTT1stDay + 161)
#define ActEndExaPrn		(ActChgCrsTT1stDay + 162)

#define ActSeeMyExaResCrs	(ActChgCrsTT1stDay + 163)
#define ActSeeMyExaResExa	(ActChgCrsTT1stDay + 164)
#define ActSeeMyExaResSes	(ActChgCrsTT1stDay + 165)
#define ActSeeOneExaResMe	(ActChgCrsTT1stDay + 166)
#define ActReqSeeUsrExaRes	(ActChgCrsTT1stDay + 167)
#define ActSeeUsrExaResCrs	(ActChgCrsTT1stDay + 168)
#define ActSeeUsrExaResExa	(ActChgCrsTT1stDay + 169)
#define ActSeeUsrExaResSes	(ActChgCrsTT1stDay + 170)
#define ActSeeOneExaResOth	(ActChgCrsTT1stDay + 171)
#define ActChgVisExaRes		(ActChgCrsTT1stDay + 172)

#define ActSeeGam		(ActChgCrsTT1stDay + 173)
#define ActReqRemMch		(ActChgCrsTT1stDay + 174)
#define ActRemMch		(ActChgCrsTT1stDay + 175)
#define ActEdiMch		(ActChgCrsTT1stDay + 176)
#define ActChgMch		(ActChgCrsTT1stDay + 177)
#define ActReqNewMch		(ActChgCrsTT1stDay + 178)
#define ActNewMch		(ActChgCrsTT1stDay + 179)
#define ActResMch		(ActChgCrsTT1stDay + 180)
#define ActBckMch		(ActChgCrsTT1stDay + 181)
#define ActPlyPauMch		(ActChgCrsTT1stDay + 182)
#define ActFwdMch		(ActChgCrsTT1stDay + 183)
#define ActChgNumColMch		(ActChgCrsTT1stDay + 184)
#define ActChgVisResMchQst	(ActChgCrsTT1stDay + 185)
#define ActMchCntDwn		(ActChgCrsTT1stDay + 186)
#define ActRefMchTch		(ActChgCrsTT1stDay + 187)

#define ActJoiMch		(ActChgCrsTT1stDay + 188)
#define ActSeeMchAnsQstStd	(ActChgCrsTT1stDay + 189)
#define ActRemMchAnsQstStd	(ActChgCrsTT1stDay + 190)
#define ActAnsMchQstStd		(ActChgCrsTT1stDay + 191)
#define ActRefMchStd		(ActChgCrsTT1stDay + 192)

#define ActSeeMyMchResCrs	(ActChgCrsTT1stDay + 193)
#define ActSeeMyMchResGam	(ActChgCrsTT1stDay + 194)
#define ActSeeMyMchResMch	(ActChgCrsTT1stDay + 195)
#define ActSeeOneMchResMe	(ActChgCrsTT1stDay + 196)

#define ActReqSeeUsrMchRes	(ActChgCrsTT1stDay + 197)
#define ActSeeUsrMchResCrs	(ActChgCrsTT1stDay + 198)
#define ActSeeUsrMchResGam	(ActChgCrsTT1stDay + 199)
#define ActSeeUsrMchResMch	(ActChgCrsTT1stDay + 200)
#define ActSeeOneMchResOth	(ActChgCrsTT1stDay + 201)

#define ActChgVisResMchUsr	(ActChgCrsTT1stDay + 202)

#define ActLstOneGam		(ActChgCrsTT1stDay + 203)

#define ActFrmNewGam		(ActChgCrsTT1stDay + 204)
#define ActEdiOneGam		(ActChgCrsTT1stDay + 205)
#define ActNewGam		(ActChgCrsTT1stDay + 206)
#define ActChgGam		(ActChgCrsTT1stDay + 207)
#define ActReqRemGam		(ActChgCrsTT1stDay + 208)
#define ActRemGam		(ActChgCrsTT1stDay + 209)
#define ActHidGam		(ActChgCrsTT1stDay + 210)
#define ActUnhGam		(ActChgCrsTT1stDay + 211)
#define ActAddOneGamQst		(ActChgCrsTT1stDay + 212)
#define ActGamLstTstQst		(ActChgCrsTT1stDay + 213)
#define ActAddTstQstToGam	(ActChgCrsTT1stDay + 214)
#define ActReqRemGamQst		(ActChgCrsTT1stDay + 215)
#define ActRemGamQst		(ActChgCrsTT1stDay + 216)
#define ActUp_GamQst		(ActChgCrsTT1stDay + 217)
#define ActDwnGamQst		(ActChgCrsTT1stDay + 218)
#define ActReqLnkGam		(ActChgCrsTT1stDay + 219)

/*****************************************************************************/
/******************************** Files tab **********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAdmDocIns		(ActReqLnkGam +   1)
#define ActAdmShaIns		(ActReqLnkGam +   2)
#define ActSeeAdmDocCtr		(ActReqLnkGam +   3)
#define ActAdmShaCtr		(ActReqLnkGam +   4)
#define ActSeeAdmDocDeg		(ActReqLnkGam +   5)
#define ActAdmShaDeg		(ActReqLnkGam +   6)
#define ActSeeAdmDocCrsGrp	(ActReqLnkGam +   7)
#define ActAdmTchCrsGrp		(ActReqLnkGam +   8)
#define ActAdmShaCrsGrp		(ActReqLnkGam +   9)
#define ActAdmAsgWrkUsr		(ActReqLnkGam +  10)
#define ActReqAsgWrkCrs		(ActReqLnkGam +  11)
#define ActSeeAdmMrk		(ActReqLnkGam +  12)
#define ActAdmBrf		(ActReqLnkGam +  13)
// Secondary actions
#define ActChgToSeeDocIns	(ActReqLnkGam +  14)
#define ActSeeDocIns		(ActReqLnkGam +  15)
#define ActExpSeeDocIns		(ActReqLnkGam +  16)
#define ActConSeeDocIns		(ActReqLnkGam +  17)
#define ActZIPSeeDocIns		(ActReqLnkGam +  18)
#define ActReqDatSeeDocIns	(ActReqLnkGam +  19)
#define ActDowSeeDocIns		(ActReqLnkGam +  20)
#define ActChgToAdmDocIns	(ActReqLnkGam +  21)
#define ActAdmDocIns		(ActReqLnkGam +  22)
#define ActReqRemFilDocIns	(ActReqLnkGam +  23)
#define ActRemFilDocIns		(ActReqLnkGam +  24)
#define ActRemFolDocIns		(ActReqLnkGam +  25)
#define ActCopDocIns		(ActReqLnkGam +  26)
#define ActPasDocIns		(ActReqLnkGam +  27)
#define ActRemTreDocIns		(ActReqLnkGam +  28)
#define ActFrmCreDocIns		(ActReqLnkGam +  29)
#define ActCreFolDocIns		(ActReqLnkGam +  30)
#define ActCreLnkDocIns		(ActReqLnkGam +  31)
#define ActRenFolDocIns		(ActReqLnkGam +  32)
#define ActRcvFilDocInsDZ	(ActReqLnkGam +  33)
#define ActRcvFilDocInsCla	(ActReqLnkGam +  34)
#define ActExpAdmDocIns		(ActReqLnkGam +  35)
#define ActConAdmDocIns		(ActReqLnkGam +  36)
#define ActZIPAdmDocIns		(ActReqLnkGam +  37)
#define ActUnhDocIns		(ActReqLnkGam +  38)
#define ActHidDocIns		(ActReqLnkGam +  39)
#define ActReqDatAdmDocIns	(ActReqLnkGam +  40)
#define ActChgDatAdmDocIns	(ActReqLnkGam +  41)
#define ActDowAdmDocIns		(ActReqLnkGam +  42)

#define ActReqRemFilShaIns	(ActReqLnkGam +  43)
#define ActRemFilShaIns		(ActReqLnkGam +  44)
#define ActRemFolShaIns		(ActReqLnkGam +  45)
#define ActCopShaIns		(ActReqLnkGam +  46)
#define ActPasShaIns		(ActReqLnkGam +  47)
#define ActRemTreShaIns		(ActReqLnkGam +  48)
#define ActFrmCreShaIns		(ActReqLnkGam +  49)
#define ActCreFolShaIns		(ActReqLnkGam +  50)
#define ActCreLnkShaIns		(ActReqLnkGam +  51)
#define ActRenFolShaIns		(ActReqLnkGam +  52)
#define ActRcvFilShaInsDZ	(ActReqLnkGam +  53)
#define ActRcvFilShaInsCla	(ActReqLnkGam +  54)
#define ActExpShaIns		(ActReqLnkGam +  55)
#define ActConShaIns		(ActReqLnkGam +  56)
#define ActZIPShaIns		(ActReqLnkGam +  57)
#define ActReqDatShaIns		(ActReqLnkGam +  58)
#define ActChgDatShaIns		(ActReqLnkGam +  59)
#define ActDowShaIns		(ActReqLnkGam +  60)

#define ActChgToSeeDocCtr	(ActReqLnkGam +  61)
#define ActSeeDocCtr		(ActReqLnkGam +  62)
#define ActExpSeeDocCtr		(ActReqLnkGam +  63)
#define ActConSeeDocCtr		(ActReqLnkGam +  64)
#define ActZIPSeeDocCtr		(ActReqLnkGam +  65)
#define ActReqDatSeeDocCtr	(ActReqLnkGam +  66)
#define ActDowSeeDocCtr		(ActReqLnkGam +  67)
#define ActChgToAdmDocCtr	(ActReqLnkGam +  68)
#define ActAdmDocCtr		(ActReqLnkGam +  69)
#define ActReqRemFilDocCtr	(ActReqLnkGam +  70)
#define ActRemFilDocCtr		(ActReqLnkGam +  71)
#define ActRemFolDocCtr		(ActReqLnkGam +  72)
#define ActCopDocCtr		(ActReqLnkGam +  73)
#define ActPasDocCtr		(ActReqLnkGam +  74)
#define ActRemTreDocCtr		(ActReqLnkGam +  75)
#define ActFrmCreDocCtr		(ActReqLnkGam +  76)
#define ActCreFolDocCtr		(ActReqLnkGam +  77)
#define ActCreLnkDocCtr		(ActReqLnkGam +  78)
#define ActRenFolDocCtr		(ActReqLnkGam +  79)
#define ActRcvFilDocCtrDZ	(ActReqLnkGam +  80)
#define ActRcvFilDocCtrCla	(ActReqLnkGam +  81)
#define ActExpAdmDocCtr		(ActReqLnkGam +  82)
#define ActConAdmDocCtr		(ActReqLnkGam +  83)
#define ActZIPAdmDocCtr		(ActReqLnkGam +  84)
#define ActUnhDocCtr		(ActReqLnkGam +  85)
#define ActHidDocCtr		(ActReqLnkGam +  86)
#define ActReqDatAdmDocCtr	(ActReqLnkGam +  87)
#define ActChgDatAdmDocCtr	(ActReqLnkGam +  88)
#define ActDowAdmDocCtr		(ActReqLnkGam +  89)

#define ActReqRemFilShaCtr	(ActReqLnkGam +  90)
#define ActRemFilShaCtr		(ActReqLnkGam +  91)
#define ActRemFolShaCtr		(ActReqLnkGam +  92)
#define ActCopShaCtr		(ActReqLnkGam +  93)
#define ActPasShaCtr		(ActReqLnkGam +  94)
#define ActRemTreShaCtr		(ActReqLnkGam +  95)
#define ActFrmCreShaCtr		(ActReqLnkGam +  96)
#define ActCreFolShaCtr		(ActReqLnkGam +  97)
#define ActCreLnkShaCtr		(ActReqLnkGam +  98)
#define ActRenFolShaCtr		(ActReqLnkGam +  99)
#define ActRcvFilShaCtrDZ	(ActReqLnkGam + 100)
#define ActRcvFilShaCtrCla	(ActReqLnkGam + 101)
#define ActExpShaCtr		(ActReqLnkGam + 102)
#define ActConShaCtr		(ActReqLnkGam + 103)
#define ActZIPShaCtr		(ActReqLnkGam + 104)
#define ActReqDatShaCtr		(ActReqLnkGam + 105)
#define ActChgDatShaCtr		(ActReqLnkGam + 106)
#define ActDowShaCtr		(ActReqLnkGam + 107)

#define ActChgToSeeDocDeg	(ActReqLnkGam + 108)
#define ActSeeDocDeg		(ActReqLnkGam + 109)
#define ActExpSeeDocDeg		(ActReqLnkGam + 110)
#define ActConSeeDocDeg		(ActReqLnkGam + 111)
#define ActZIPSeeDocDeg		(ActReqLnkGam + 112)
#define ActReqDatSeeDocDeg	(ActReqLnkGam + 113)
#define ActDowSeeDocDeg		(ActReqLnkGam + 114)
#define ActChgToAdmDocDeg	(ActReqLnkGam + 115)
#define ActAdmDocDeg		(ActReqLnkGam + 116)
#define ActReqRemFilDocDeg	(ActReqLnkGam + 117)
#define ActRemFilDocDeg		(ActReqLnkGam + 118)
#define ActRemFolDocDeg		(ActReqLnkGam + 119)
#define ActCopDocDeg		(ActReqLnkGam + 120)
#define ActPasDocDeg		(ActReqLnkGam + 121)
#define ActRemTreDocDeg		(ActReqLnkGam + 122)
#define ActFrmCreDocDeg		(ActReqLnkGam + 123)
#define ActCreFolDocDeg		(ActReqLnkGam + 124)
#define ActCreLnkDocDeg		(ActReqLnkGam + 125)
#define ActRenFolDocDeg		(ActReqLnkGam + 126)
#define ActRcvFilDocDegDZ	(ActReqLnkGam + 127)
#define ActRcvFilDocDegCla	(ActReqLnkGam + 128)
#define ActExpAdmDocDeg		(ActReqLnkGam + 129)
#define ActConAdmDocDeg		(ActReqLnkGam + 130)
#define ActZIPAdmDocDeg		(ActReqLnkGam + 131)
#define ActUnhDocDeg		(ActReqLnkGam + 132)
#define ActHidDocDeg		(ActReqLnkGam + 133)
#define ActReqDatAdmDocDeg	(ActReqLnkGam + 134)
#define ActChgDatAdmDocDeg	(ActReqLnkGam + 135)
#define ActDowAdmDocDeg		(ActReqLnkGam + 136)

#define ActReqRemFilShaDeg	(ActReqLnkGam + 137)
#define ActRemFilShaDeg		(ActReqLnkGam + 138)
#define ActRemFolShaDeg		(ActReqLnkGam + 139)
#define ActCopShaDeg		(ActReqLnkGam + 140)
#define ActPasShaDeg		(ActReqLnkGam + 141)
#define ActRemTreShaDeg		(ActReqLnkGam + 142)
#define ActFrmCreShaDeg		(ActReqLnkGam + 143)
#define ActCreFolShaDeg		(ActReqLnkGam + 144)
#define ActCreLnkShaDeg		(ActReqLnkGam + 145)
#define ActRenFolShaDeg		(ActReqLnkGam + 146)
#define ActRcvFilShaDegDZ	(ActReqLnkGam + 147)
#define ActRcvFilShaDegCla	(ActReqLnkGam + 148)
#define ActExpShaDeg		(ActReqLnkGam + 149)
#define ActConShaDeg		(ActReqLnkGam + 150)
#define ActZIPShaDeg		(ActReqLnkGam + 151)
#define ActReqDatShaDeg		(ActReqLnkGam + 152)
#define ActChgDatShaDeg		(ActReqLnkGam + 153)
#define ActDowShaDeg		(ActReqLnkGam + 154)

#define ActChgToSeeDocCrs	(ActReqLnkGam + 155)
#define ActSeeDocCrs		(ActReqLnkGam + 156)
#define ActExpSeeDocCrs		(ActReqLnkGam + 157)
#define ActConSeeDocCrs		(ActReqLnkGam + 158)
#define ActZIPSeeDocCrs		(ActReqLnkGam + 159)
#define ActReqDatSeeDocCrs	(ActReqLnkGam + 160)
#define ActReqLnkSeeDocCrs	(ActReqLnkGam + 161)
#define ActDowSeeDocCrs		(ActReqLnkGam + 162)

#define ActSeeDocGrp		(ActReqLnkGam + 163)
#define ActExpSeeDocGrp		(ActReqLnkGam + 164)
#define ActConSeeDocGrp		(ActReqLnkGam + 165)
#define ActZIPSeeDocGrp		(ActReqLnkGam + 166)
#define ActReqDatSeeDocGrp	(ActReqLnkGam + 167)
#define ActDowSeeDocGrp		(ActReqLnkGam + 168)

#define ActChgToAdmDocCrs	(ActReqLnkGam + 169)
#define ActAdmDocCrs		(ActReqLnkGam + 170)
#define ActReqRemFilDocCrs	(ActReqLnkGam + 171)
#define ActRemFilDocCrs		(ActReqLnkGam + 172)
#define ActRemFolDocCrs		(ActReqLnkGam + 173)
#define ActCopDocCrs		(ActReqLnkGam + 174)
#define ActPasDocCrs		(ActReqLnkGam + 175)
#define ActRemTreDocCrs		(ActReqLnkGam + 176)
#define ActFrmCreDocCrs		(ActReqLnkGam + 177)
#define ActCreFolDocCrs		(ActReqLnkGam + 178)
#define ActCreLnkDocCrs		(ActReqLnkGam + 179)
#define ActRenFolDocCrs		(ActReqLnkGam + 180)
#define ActRcvFilDocCrsDZ	(ActReqLnkGam + 181)
#define ActRcvFilDocCrsCla	(ActReqLnkGam + 182)
#define ActExpAdmDocCrs		(ActReqLnkGam + 183)
#define ActConAdmDocCrs		(ActReqLnkGam + 184)
#define ActZIPAdmDocCrs		(ActReqLnkGam + 185)
#define ActUnhDocCrs		(ActReqLnkGam + 186)
#define ActHidDocCrs		(ActReqLnkGam + 187)
#define ActReqDatAdmDocCrs	(ActReqLnkGam + 188)
#define ActChgDatAdmDocCrs	(ActReqLnkGam + 189)
#define ActReqLnkAdmDocCrs	(ActReqLnkGam + 190)
#define ActDowAdmDocCrs		(ActReqLnkGam + 191)

#define ActAdmDocGrp		(ActReqLnkGam + 192)
#define ActReqRemFilDocGrp	(ActReqLnkGam + 193)
#define ActRemFilDocGrp		(ActReqLnkGam + 194)
#define ActRemFolDocGrp		(ActReqLnkGam + 195)
#define ActCopDocGrp		(ActReqLnkGam + 196)
#define ActPasDocGrp		(ActReqLnkGam + 197)
#define ActRemTreDocGrp		(ActReqLnkGam + 198)
#define ActFrmCreDocGrp		(ActReqLnkGam + 199)
#define ActCreFolDocGrp		(ActReqLnkGam + 200)
#define ActCreLnkDocGrp		(ActReqLnkGam + 201)
#define ActRenFolDocGrp		(ActReqLnkGam + 202)
#define ActRcvFilDocGrpDZ	(ActReqLnkGam + 203)
#define ActRcvFilDocGrpCla	(ActReqLnkGam + 204)
#define ActExpAdmDocGrp		(ActReqLnkGam + 205)
#define ActConAdmDocGrp		(ActReqLnkGam + 206)
#define ActZIPAdmDocGrp		(ActReqLnkGam + 207)
#define ActUnhDocGrp		(ActReqLnkGam + 208)
#define ActHidDocGrp		(ActReqLnkGam + 209)
#define ActReqDatAdmDocGrp	(ActReqLnkGam + 210)
#define ActChgDatAdmDocGrp	(ActReqLnkGam + 211)
#define ActDowAdmDocGrp		(ActReqLnkGam + 212)

#define ActChgToAdmTch		(ActReqLnkGam + 213)

#define ActAdmTchCrs		(ActReqLnkGam + 214)
#define ActReqRemFilTchCrs	(ActReqLnkGam + 215)
#define ActRemFilTchCrs		(ActReqLnkGam + 216)
#define ActRemFolTchCrs		(ActReqLnkGam + 217)
#define ActCopTchCrs		(ActReqLnkGam + 218)
#define ActPasTchCrs		(ActReqLnkGam + 219)
#define ActRemTreTchCrs		(ActReqLnkGam + 220)
#define ActFrmCreTchCrs		(ActReqLnkGam + 221)
#define ActCreFolTchCrs		(ActReqLnkGam + 222)
#define ActCreLnkTchCrs		(ActReqLnkGam + 223)
#define ActRenFolTchCrs		(ActReqLnkGam + 224)
#define ActRcvFilTchCrsDZ	(ActReqLnkGam + 225)
#define ActRcvFilTchCrsCla	(ActReqLnkGam + 226)
#define ActExpTchCrs		(ActReqLnkGam + 227)
#define ActConTchCrs		(ActReqLnkGam + 228)
#define ActZIPTchCrs		(ActReqLnkGam + 229)
#define ActReqDatTchCrs		(ActReqLnkGam + 230)
#define ActChgDatTchCrs		(ActReqLnkGam + 231)
#define ActDowTchCrs		(ActReqLnkGam + 232)

#define ActAdmTchGrp		(ActReqLnkGam + 233)
#define ActReqRemFilTchGrp	(ActReqLnkGam + 234)
#define ActRemFilTchGrp		(ActReqLnkGam + 235)
#define ActRemFolTchGrp		(ActReqLnkGam + 236)
#define ActCopTchGrp		(ActReqLnkGam + 237)
#define ActPasTchGrp		(ActReqLnkGam + 238)
#define ActRemTreTchGrp		(ActReqLnkGam + 239)
#define ActFrmCreTchGrp		(ActReqLnkGam + 240)
#define ActCreFolTchGrp		(ActReqLnkGam + 241)
#define ActCreLnkTchGrp		(ActReqLnkGam + 242)
#define ActRenFolTchGrp		(ActReqLnkGam + 243)
#define ActRcvFilTchGrpDZ	(ActReqLnkGam + 244)
#define ActRcvFilTchGrpCla	(ActReqLnkGam + 245)
#define ActExpTchGrp		(ActReqLnkGam + 246)
#define ActConTchGrp		(ActReqLnkGam + 247)
#define ActZIPTchGrp		(ActReqLnkGam + 248)
#define ActReqDatTchGrp		(ActReqLnkGam + 249)
#define ActChgDatTchGrp		(ActReqLnkGam + 250)
#define ActDowTchGrp		(ActReqLnkGam + 251)

#define ActChgToAdmSha		(ActReqLnkGam + 252)

#define ActAdmShaCrs		(ActReqLnkGam + 253)
#define ActReqRemFilShaCrs	(ActReqLnkGam + 254)
#define ActRemFilShaCrs		(ActReqLnkGam + 255)
#define ActRemFolShaCrs		(ActReqLnkGam + 256)
#define ActCopShaCrs		(ActReqLnkGam + 257)
#define ActPasShaCrs		(ActReqLnkGam + 258)
#define ActRemTreShaCrs		(ActReqLnkGam + 259)
#define ActFrmCreShaCrs		(ActReqLnkGam + 260)
#define ActCreFolShaCrs		(ActReqLnkGam + 261)
#define ActCreLnkShaCrs		(ActReqLnkGam + 262)
#define ActRenFolShaCrs		(ActReqLnkGam + 263)
#define ActRcvFilShaCrsDZ	(ActReqLnkGam + 264)
#define ActRcvFilShaCrsCla	(ActReqLnkGam + 265)
#define ActExpShaCrs		(ActReqLnkGam + 266)
#define ActConShaCrs		(ActReqLnkGam + 267)
#define ActZIPShaCrs		(ActReqLnkGam + 268)
#define ActReqDatShaCrs		(ActReqLnkGam + 269)
#define ActChgDatShaCrs		(ActReqLnkGam + 270)
#define ActDowShaCrs		(ActReqLnkGam + 271)

#define ActAdmShaGrp		(ActReqLnkGam + 272)
#define ActReqRemFilShaGrp	(ActReqLnkGam + 273)
#define ActRemFilShaGrp		(ActReqLnkGam + 274)
#define ActRemFolShaGrp		(ActReqLnkGam + 275)
#define ActCopShaGrp		(ActReqLnkGam + 276)
#define ActPasShaGrp		(ActReqLnkGam + 277)
#define ActRemTreShaGrp		(ActReqLnkGam + 278)
#define ActFrmCreShaGrp		(ActReqLnkGam + 279)
#define ActCreFolShaGrp		(ActReqLnkGam + 280)
#define ActCreLnkShaGrp		(ActReqLnkGam + 281)
#define ActRenFolShaGrp		(ActReqLnkGam + 282)
#define ActRcvFilShaGrpDZ	(ActReqLnkGam + 283)
#define ActRcvFilShaGrpCla	(ActReqLnkGam + 284)
#define ActExpShaGrp		(ActReqLnkGam + 285)
#define ActConShaGrp		(ActReqLnkGam + 286)
#define ActZIPShaGrp		(ActReqLnkGam + 287)
#define ActReqDatShaGrp		(ActReqLnkGam + 288)
#define ActChgDatShaGrp		(ActReqLnkGam + 289)
#define ActDowShaGrp		(ActReqLnkGam + 290)

#define ActAdmAsgWrkCrs		(ActReqLnkGam + 291)

#define ActReqRemFilAsgUsr	(ActReqLnkGam + 292)
#define ActRemFilAsgUsr		(ActReqLnkGam + 293)
#define ActRemFolAsgUsr		(ActReqLnkGam + 294)
#define ActCopAsgUsr		(ActReqLnkGam + 295)
#define ActPasAsgUsr		(ActReqLnkGam + 296)
#define ActRemTreAsgUsr		(ActReqLnkGam + 297)
#define ActFrmCreAsgUsr		(ActReqLnkGam + 298)
#define ActCreFolAsgUsr		(ActReqLnkGam + 299)
#define ActCreLnkAsgUsr		(ActReqLnkGam + 300)
#define ActRenFolAsgUsr		(ActReqLnkGam + 301)
#define ActRcvFilAsgUsrDZ	(ActReqLnkGam + 302)
#define ActRcvFilAsgUsrCla	(ActReqLnkGam + 303)
#define ActExpAsgUsr		(ActReqLnkGam + 304)
#define ActConAsgUsr		(ActReqLnkGam + 305)
#define ActZIPAsgUsr		(ActReqLnkGam + 306)
#define ActReqDatAsgUsr		(ActReqLnkGam + 307)
#define ActChgDatAsgUsr		(ActReqLnkGam + 308)
#define ActDowAsgUsr		(ActReqLnkGam + 309)

#define ActReqRemFilWrkUsr	(ActReqLnkGam + 310)
#define ActRemFilWrkUsr		(ActReqLnkGam + 311)
#define ActRemFolWrkUsr		(ActReqLnkGam + 312)
#define ActCopWrkUsr		(ActReqLnkGam + 313)
#define ActPasWrkUsr		(ActReqLnkGam + 314)
#define ActRemTreWrkUsr		(ActReqLnkGam + 315)
#define ActFrmCreWrkUsr		(ActReqLnkGam + 316)
#define ActCreFolWrkUsr		(ActReqLnkGam + 317)
#define ActCreLnkWrkUsr		(ActReqLnkGam + 318)
#define ActRenFolWrkUsr		(ActReqLnkGam + 319)
#define ActRcvFilWrkUsrDZ	(ActReqLnkGam + 320)
#define ActRcvFilWrkUsrCla	(ActReqLnkGam + 321)
#define ActExpWrkUsr		(ActReqLnkGam + 322)
#define ActConWrkUsr		(ActReqLnkGam + 323)
#define ActZIPWrkUsr		(ActReqLnkGam + 324)
#define ActReqDatWrkUsr		(ActReqLnkGam + 325)
#define ActChgDatWrkUsr		(ActReqLnkGam + 326)
#define ActDowWrkUsr		(ActReqLnkGam + 327)

#define ActReqRemFilAsgCrs	(ActReqLnkGam + 328)
#define ActRemFilAsgCrs		(ActReqLnkGam + 329)
#define ActRemFolAsgCrs		(ActReqLnkGam + 330)
#define ActCopAsgCrs		(ActReqLnkGam + 331)
#define ActPasAsgCrs		(ActReqLnkGam + 332)
#define ActRemTreAsgCrs		(ActReqLnkGam + 333)
#define ActFrmCreAsgCrs		(ActReqLnkGam + 334)
#define ActCreFolAsgCrs		(ActReqLnkGam + 335)
#define ActCreLnkAsgCrs		(ActReqLnkGam + 336)
#define ActRenFolAsgCrs		(ActReqLnkGam + 337)
#define ActRcvFilAsgCrsDZ	(ActReqLnkGam + 338)
#define ActRcvFilAsgCrsCla	(ActReqLnkGam + 339)
#define ActExpAsgCrs		(ActReqLnkGam + 340)
#define ActConAsgCrs		(ActReqLnkGam + 341)
#define ActZIPAsgCrs		(ActReqLnkGam + 342)
#define ActReqDatAsgCrs		(ActReqLnkGam + 343)
#define ActChgDatAsgCrs		(ActReqLnkGam + 344)
#define ActDowAsgCrs		(ActReqLnkGam + 345)

#define ActReqRemFilWrkCrs	(ActReqLnkGam + 346)
#define ActRemFilWrkCrs		(ActReqLnkGam + 347)
#define ActRemFolWrkCrs		(ActReqLnkGam + 348)
#define ActCopWrkCrs		(ActReqLnkGam + 349)
#define ActPasWrkCrs		(ActReqLnkGam + 350)
#define ActRemTreWrkCrs		(ActReqLnkGam + 351)
#define ActFrmCreWrkCrs		(ActReqLnkGam + 352)
#define ActCreFolWrkCrs		(ActReqLnkGam + 353)
#define ActCreLnkWrkCrs		(ActReqLnkGam + 354)
#define ActRenFolWrkCrs		(ActReqLnkGam + 355)
#define ActRcvFilWrkCrsDZ	(ActReqLnkGam + 356)
#define ActRcvFilWrkCrsCla	(ActReqLnkGam + 357)
#define ActExpWrkCrs		(ActReqLnkGam + 358)
#define ActConWrkCrs		(ActReqLnkGam + 359)
#define ActZIPWrkCrs		(ActReqLnkGam + 360)
#define ActReqDatWrkCrs		(ActReqLnkGam + 361)
#define ActChgDatWrkCrs		(ActReqLnkGam + 362)
#define ActDowWrkCrs		(ActReqLnkGam + 363)

#define ActChgToSeeMrk		(ActReqLnkGam + 364)

#define ActSeeMrkCrs		(ActReqLnkGam + 365)
#define ActExpSeeMrkCrs		(ActReqLnkGam + 366)
#define ActConSeeMrkCrs		(ActReqLnkGam + 367)
#define ActReqDatSeeMrkCrs	(ActReqLnkGam + 368)
#define ActReqLnkSeeMrkCrs	(ActReqLnkGam + 369)
#define ActSeeMyMrkCrs		(ActReqLnkGam + 370)

#define ActSeeMrkGrp		(ActReqLnkGam + 371)
#define ActExpSeeMrkGrp		(ActReqLnkGam + 372)
#define ActConSeeMrkGrp		(ActReqLnkGam + 373)
#define ActReqDatSeeMrkGrp	(ActReqLnkGam + 374)
#define ActSeeMyMrkGrp		(ActReqLnkGam + 375)

#define ActChgToAdmMrk		(ActReqLnkGam + 376)

#define ActAdmMrkCrs		(ActReqLnkGam + 377)
#define ActReqRemFilMrkCrs	(ActReqLnkGam + 378)
#define ActRemFilMrkCrs		(ActReqLnkGam + 379)
#define ActRemFolMrkCrs		(ActReqLnkGam + 380)
#define ActCopMrkCrs		(ActReqLnkGam + 381)
#define ActPasMrkCrs		(ActReqLnkGam + 382)
#define ActRemTreMrkCrs		(ActReqLnkGam + 383)
#define ActFrmCreMrkCrs		(ActReqLnkGam + 384)
#define ActCreFolMrkCrs		(ActReqLnkGam + 385)
#define ActRenFolMrkCrs		(ActReqLnkGam + 386)
#define ActRcvFilMrkCrsDZ	(ActReqLnkGam + 387)
#define ActRcvFilMrkCrsCla	(ActReqLnkGam + 388)
#define ActExpAdmMrkCrs		(ActReqLnkGam + 389)
#define ActConAdmMrkCrs		(ActReqLnkGam + 390)
#define ActZIPAdmMrkCrs		(ActReqLnkGam + 391)
#define ActUnhMrkCrs		(ActReqLnkGam + 392)
#define ActHidMrkCrs		(ActReqLnkGam + 393)
#define ActReqDatAdmMrkCrs	(ActReqLnkGam + 394)
#define ActChgDatAdmMrkCrs	(ActReqLnkGam + 395)
#define ActReqLnkAdmMrkCrs	(ActReqLnkGam + 396)
#define ActDowAdmMrkCrs		(ActReqLnkGam + 397)
#define ActChgNumRowHeaCrs	(ActReqLnkGam + 398)
#define ActChgNumRowFooCrs	(ActReqLnkGam + 399)

#define ActAdmMrkGrp		(ActReqLnkGam + 400)
#define ActReqRemFilMrkGrp	(ActReqLnkGam + 401)
#define ActRemFilMrkGrp		(ActReqLnkGam + 402)
#define ActRemFolMrkGrp		(ActReqLnkGam + 403)
#define ActCopMrkGrp		(ActReqLnkGam + 404)
#define ActPasMrkGrp		(ActReqLnkGam + 405)
#define ActRemTreMrkGrp		(ActReqLnkGam + 406)
#define ActFrmCreMrkGrp		(ActReqLnkGam + 407)
#define ActCreFolMrkGrp		(ActReqLnkGam + 408)
#define ActRenFolMrkGrp		(ActReqLnkGam + 409)
#define ActRcvFilMrkGrpDZ	(ActReqLnkGam + 410)
#define ActRcvFilMrkGrpCla	(ActReqLnkGam + 411)
#define ActExpAdmMrkGrp		(ActReqLnkGam + 412)
#define ActConAdmMrkGrp		(ActReqLnkGam + 413)
#define ActZIPAdmMrkGrp		(ActReqLnkGam + 414)
#define ActUnhMrkGrp		(ActReqLnkGam + 415)
#define ActHidMrkGrp		(ActReqLnkGam + 416)
#define ActReqDatAdmMrkGrp	(ActReqLnkGam + 417)
#define ActChgDatAdmMrkGrp	(ActReqLnkGam + 418)
#define ActDowAdmMrkGrp		(ActReqLnkGam + 419)
#define ActChgNumRowHeaGrp	(ActReqLnkGam + 420)
#define ActChgNumRowFooGrp	(ActReqLnkGam + 421)

#define ActReqRemFilBrf		(ActReqLnkGam + 422)
#define ActRemFilBrf		(ActReqLnkGam + 423)
#define ActRemFolBrf		(ActReqLnkGam + 424)
#define ActCopBrf		(ActReqLnkGam + 425)
#define ActPasBrf		(ActReqLnkGam + 426)
#define ActRemTreBrf		(ActReqLnkGam + 427)
#define ActFrmCreBrf		(ActReqLnkGam + 428)
#define ActCreFolBrf		(ActReqLnkGam + 429)
#define ActCreLnkBrf		(ActReqLnkGam + 430)
#define ActRenFolBrf		(ActReqLnkGam + 431)
#define ActRcvFilBrfDZ		(ActReqLnkGam + 432)
#define ActRcvFilBrfCla		(ActReqLnkGam + 433)
#define ActExpBrf		(ActReqLnkGam + 434)
#define ActConBrf		(ActReqLnkGam + 435)
#define ActZIPBrf		(ActReqLnkGam + 436)
#define ActReqDatBrf		(ActReqLnkGam + 437)
#define ActChgDatBrf		(ActReqLnkGam + 438)
#define ActDowBrf		(ActReqLnkGam + 439)
#define ActReqRemOldBrf		(ActReqLnkGam + 440)
#define ActRemOldBrf		(ActReqLnkGam + 441)

/*****************************************************************************/
/******************************* Users tab ***********************************/
/*****************************************************************************/
// Actions in menu
#define ActReqSelGrp		(ActRemOldBrf +   1)
#define ActLstStd		(ActRemOldBrf +   2)
#define ActLstTch		(ActRemOldBrf +   3)
#define ActLstOth		(ActRemOldBrf +   4)
#define ActSeeAtt		(ActRemOldBrf +   5)
#define ActReqSignUp		(ActRemOldBrf +   6)
#define ActSeeSignUpReq		(ActRemOldBrf +   7)
#define ActLstCon		(ActRemOldBrf +   8)

// Secondary actions
#define ActChgGrp		(ActRemOldBrf +   9)
#define ActReqEdiGrp		(ActRemOldBrf +  10)
#define ActNewGrpTyp		(ActRemOldBrf +  11)
#define ActReqRemGrpTyp		(ActRemOldBrf +  12)
#define ActRemGrpTyp		(ActRemOldBrf +  13)
#define ActRenGrpTyp		(ActRemOldBrf +  14)
#define ActChgMdtGrpTyp		(ActRemOldBrf +  15)
#define ActChgMulGrpTyp		(ActRemOldBrf +  16)
#define ActChgTimGrpTyp		(ActRemOldBrf +  17)
#define ActNewGrp		(ActRemOldBrf +  18)
#define ActReqRemGrp		(ActRemOldBrf +  19)
#define ActRemGrp		(ActRemOldBrf +  20)
#define ActOpeGrp		(ActRemOldBrf +  21)
#define ActCloGrp		(ActRemOldBrf +  22)
#define ActEnaFilZonGrp		(ActRemOldBrf +  23)
#define ActDisFilZonGrp		(ActRemOldBrf +  24)
#define ActChgGrpTyp		(ActRemOldBrf +  25)
#define ActRenGrp		(ActRemOldBrf +  26)
#define ActChgGrpRoo		(ActRemOldBrf +  27)
#define ActChgMaxStdGrp		(ActRemOldBrf +  28)

#define ActLstGst		(ActRemOldBrf +  29)

#define ActPrnGstPho		(ActRemOldBrf +  30)
#define ActPrnStdPho		(ActRemOldBrf +  31)
#define ActPrnTchPho		(ActRemOldBrf +  32)
#define ActLstGstAll		(ActRemOldBrf +  33)
#define ActLstStdAll		(ActRemOldBrf +  34)
#define ActLstTchAll		(ActRemOldBrf +  35)

#define ActSeeRecOneStd		(ActRemOldBrf +  36)
#define ActSeeRecOneTch		(ActRemOldBrf +  37)
#define ActDoActOnSevGst	(ActRemOldBrf +  38)
#define ActDoActOnSevStd	(ActRemOldBrf +  39)
#define ActDoActOnSevTch	(ActRemOldBrf +  40)
#define ActSeeRecSevGst		(ActRemOldBrf +  41)
#define ActSeeRecSevStd		(ActRemOldBrf +  42)
#define ActSeeRecSevTch		(ActRemOldBrf +  43)
#define ActPrnRecSevGst		(ActRemOldBrf +  44)
#define ActPrnRecSevStd		(ActRemOldBrf +  45)
#define ActPrnRecSevTch		(ActRemOldBrf +  46)
#define ActRcvRecOthUsr		(ActRemOldBrf +  47)
#define ActEdiRecFie		(ActRemOldBrf +  48)
#define ActNewFie		(ActRemOldBrf +  49)
#define ActReqRemFie		(ActRemOldBrf +  50)
#define ActRemFie		(ActRemOldBrf +  51)
#define ActRenFie		(ActRemOldBrf +  52)
#define ActChgRowFie		(ActRemOldBrf +  53)
#define ActChgVisFie		(ActRemOldBrf +  54)
#define ActRcvRecCrs		(ActRemOldBrf +  55)

#define ActFrmLogInUsrAgd	(ActRemOldBrf +  56)
#define ActLogInUsrAgd		(ActRemOldBrf +  57)
#define ActLogInUsrAgdLan	(ActRemOldBrf +  58)
#define ActSeeUsrAgd		(ActRemOldBrf +  59)

#define ActReqEnrSevStd		(ActRemOldBrf +  60)
#define ActReqEnrSevNET		(ActRemOldBrf +  61)
#define ActReqEnrSevTch		(ActRemOldBrf +  62)

#define ActReqLstUsrAtt		(ActRemOldBrf +  63)
#define ActSeeLstMyAtt		(ActRemOldBrf +  64)
#define ActPrnLstMyAtt		(ActRemOldBrf +  65)
#define ActSeeLstUsrAtt		(ActRemOldBrf +  66)
#define ActPrnLstUsrAtt		(ActRemOldBrf +  67)
#define ActFrmNewAtt		(ActRemOldBrf +  68)
#define ActEdiOneAtt		(ActRemOldBrf +  69)
#define ActNewAtt		(ActRemOldBrf +  70)
#define ActChgAtt		(ActRemOldBrf +  71)
#define ActReqRemAtt		(ActRemOldBrf +  72)
#define ActRemAtt		(ActRemOldBrf +  73)
#define ActHidAtt		(ActRemOldBrf +  74)
#define ActUnhAtt		(ActRemOldBrf +  75)
#define ActSeeOneAtt		(ActRemOldBrf +  76)
#define ActReqLnkAtt		(ActRemOldBrf +  77)
#define ActRecAttStd		(ActRemOldBrf +  78)
#define ActRecAttMe		(ActRemOldBrf +  79)

#define ActSignUp		(ActRemOldBrf +  80)
#define ActUpdSignUpReq		(ActRemOldBrf +  81)
#define ActReqRejSignUp		(ActRemOldBrf +  82)
#define ActRejSignUp		(ActRemOldBrf +  83)

#define ActReqMdfOneOth		(ActRemOldBrf +  84)
#define ActReqMdfOneStd		(ActRemOldBrf +  85)
#define ActReqMdfOneTch		(ActRemOldBrf +  86)

#define ActReqMdfOth		(ActRemOldBrf +  87)
#define ActReqMdfStd		(ActRemOldBrf +  88)
#define ActReqMdfNET		(ActRemOldBrf +  89)
#define ActReqMdfTch		(ActRemOldBrf +  90)

#define ActReqOthPho		(ActRemOldBrf +  91)
#define ActReqStdPho		(ActRemOldBrf +  92)
#define ActReqTchPho		(ActRemOldBrf +  93)
#define ActDetOthPho		(ActRemOldBrf +  94)
#define ActDetStdPho		(ActRemOldBrf +  95)
#define ActDetTchPho		(ActRemOldBrf +  96)
#define ActUpdOthPho		(ActRemOldBrf +  97)
#define ActUpdStdPho		(ActRemOldBrf +  98)
#define ActUpdTchPho		(ActRemOldBrf +  99)
#define ActReqRemOthPho		(ActRemOldBrf + 100)
#define ActReqRemStdPho		(ActRemOldBrf + 101)
#define ActReqRemTchPho		(ActRemOldBrf + 102)
#define ActRemOthPho		(ActRemOldBrf + 103)
#define ActRemStdPho		(ActRemOldBrf + 104)
#define ActRemTchPho		(ActRemOldBrf + 105)
#define ActCreOth		(ActRemOldBrf + 106)
#define ActCreStd		(ActRemOldBrf + 107)
#define ActCreNET		(ActRemOldBrf + 108)
#define ActCreTch		(ActRemOldBrf + 109)
#define ActUpdOth		(ActRemOldBrf + 110)
#define ActUpdStd		(ActRemOldBrf + 111)
#define ActUpdNET		(ActRemOldBrf + 112)
#define ActUpdTch		(ActRemOldBrf + 113)

#define ActReqAccEnrStd		(ActRemOldBrf + 114)
#define ActReqAccEnrNET		(ActRemOldBrf + 115)
#define ActReqAccEnrTch		(ActRemOldBrf + 116)
#define ActAccEnrStd		(ActRemOldBrf + 117)
#define ActAccEnrNET		(ActRemOldBrf + 118)
#define ActAccEnrTch		(ActRemOldBrf + 119)
#define ActRemMe_Std		(ActRemOldBrf + 120)
#define ActRemMe_NET		(ActRemOldBrf + 121)
#define ActRemMe_Tch		(ActRemOldBrf + 122)

#define ActNewAdmIns		(ActRemOldBrf + 123)
#define ActRemAdmIns		(ActRemOldBrf + 124)
#define ActNewAdmCtr		(ActRemOldBrf + 125)
#define ActRemAdmCtr		(ActRemOldBrf + 126)
#define ActNewAdmDeg		(ActRemOldBrf + 127)
#define ActRemAdmDeg		(ActRemOldBrf + 128)

#define ActRcvFrmEnrSevStd	(ActRemOldBrf + 129)
#define ActRcvFrmEnrSevNET	(ActRemOldBrf + 130)
#define ActRcvFrmEnrSevTch	(ActRemOldBrf + 131)

#define ActCnfID_Oth		(ActRemOldBrf + 132)
#define ActCnfID_Std		(ActRemOldBrf + 133)
#define ActCnfID_Tch		(ActRemOldBrf + 134)

#define ActFrmAccOth		(ActRemOldBrf + 135)
#define ActFrmAccStd		(ActRemOldBrf + 136)
#define ActFrmAccTch		(ActRemOldBrf + 137)

#define ActRemOldNicOth		(ActRemOldBrf + 138)
#define ActRemOldNicStd		(ActRemOldBrf + 139)
#define ActRemOldNicTch		(ActRemOldBrf + 140)
#define ActChgNicOth		(ActRemOldBrf + 141)
#define ActChgNicStd		(ActRemOldBrf + 142)
#define ActChgNicTch		(ActRemOldBrf + 143)

#define ActRemID_Oth		(ActRemOldBrf + 144)
#define ActRemID_Std		(ActRemOldBrf + 145)
#define ActRemID_Tch		(ActRemOldBrf + 146)
#define ActNewID_Oth		(ActRemOldBrf + 147)
#define ActNewID_Std		(ActRemOldBrf + 148)
#define ActNewID_Tch		(ActRemOldBrf + 149)
#define ActChgPwdOth		(ActRemOldBrf + 150)
#define ActChgPwdStd		(ActRemOldBrf + 151)
#define ActChgPwdTch		(ActRemOldBrf + 152)
#define ActRemMaiOth		(ActRemOldBrf + 153)
#define ActRemMaiStd		(ActRemOldBrf + 154)
#define ActRemMaiTch		(ActRemOldBrf + 155)
#define ActNewMaiOth		(ActRemOldBrf + 156)
#define ActNewMaiStd		(ActRemOldBrf + 157)
#define ActNewMaiTch		(ActRemOldBrf + 158)

#define ActRemStdCrs		(ActRemOldBrf + 159)
#define ActRemNETCrs		(ActRemOldBrf + 160)
#define ActRemTchCrs		(ActRemOldBrf + 161)
#define ActRemUsrGbl		(ActRemOldBrf + 162)

#define ActReqRemAllStdCrs	(ActRemOldBrf + 163)
#define ActRemAllStdCrs		(ActRemOldBrf + 164)

#define ActReqRemOldUsr		(ActRemOldBrf + 165)
#define ActRemOldUsr		(ActRemOldBrf + 166)

#define ActLstDupUsr		(ActRemOldBrf + 167)
#define ActLstSimUsr		(ActRemOldBrf + 168)
#define ActRemDupUsr		(ActRemOldBrf + 169)

#define ActReqFolSevStd		(ActRemOldBrf + 170)
#define ActReqFolSevTch		(ActRemOldBrf + 171)
#define ActReqUnfSevStd		(ActRemOldBrf + 172)
#define ActReqUnfSevTch		(ActRemOldBrf + 173)
#define ActFolSevStd		(ActRemOldBrf + 174)
#define ActFolSevTch		(ActRemOldBrf + 175)
#define ActUnfSevStd		(ActRemOldBrf + 176)
#define ActUnfSevTch		(ActRemOldBrf + 177)

/*****************************************************************************/
/******************************* Messages tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAnn		(ActUnfSevTch +   1)
#define ActSeeAllNot		(ActUnfSevTch +   2)
#define ActSeeFor		(ActUnfSevTch +   3)
#define ActSeeChtRms		(ActUnfSevTch +   4)
#define ActSeeRcvMsg		(ActUnfSevTch +   5)
#define ActReqMaiUsr		(ActUnfSevTch +   6)
// Secondary actions
#define ActWriAnn		(ActUnfSevTch +   7)
#define ActRcvAnn		(ActUnfSevTch +   8)
#define ActHidAnn		(ActUnfSevTch +   9)
#define ActUnhAnn		(ActUnfSevTch +  10)
#define ActRemAnn		(ActUnfSevTch +  11)
#define ActSeeOneNot		(ActUnfSevTch +  12)
#define ActWriNot		(ActUnfSevTch +  13)
#define ActRcvNot		(ActUnfSevTch +  14)
#define ActHidNot		(ActUnfSevTch +  15)
#define ActUnhNot		(ActUnfSevTch +  16)
#define ActReqRemNot		(ActUnfSevTch +  17)
#define ActRemNot		(ActUnfSevTch +  18)

#define ActSeeForCrsUsr		(ActUnfSevTch +  19)
#define ActSeeForCrsTch		(ActUnfSevTch +  20)
#define ActSeeForDegUsr		(ActUnfSevTch +  21)
#define ActSeeForDegTch		(ActUnfSevTch +  22)
#define ActSeeForCtrUsr		(ActUnfSevTch +  23)
#define ActSeeForCtrTch		(ActUnfSevTch +  24)
#define ActSeeForInsUsr		(ActUnfSevTch +  25)
#define ActSeeForInsTch		(ActUnfSevTch +  26)
#define ActSeeForGenUsr		(ActUnfSevTch +  27)
#define ActSeeForGenTch		(ActUnfSevTch +  28)
#define ActSeeForSWAUsr		(ActUnfSevTch +  29)
#define ActSeeForSWATch		(ActUnfSevTch +  30)
#define ActSeePstForCrsUsr	(ActUnfSevTch +  31)
#define ActSeePstForCrsTch	(ActUnfSevTch +  32)
#define ActSeePstForDegUsr	(ActUnfSevTch +  33)
#define ActSeePstForDegTch	(ActUnfSevTch +  34)
#define ActSeePstForCtrUsr	(ActUnfSevTch +  35)
#define ActSeePstForCtrTch	(ActUnfSevTch +  36)
#define ActSeePstForInsUsr	(ActUnfSevTch +  37)
#define ActSeePstForInsTch	(ActUnfSevTch +  38)
#define ActSeePstForGenUsr	(ActUnfSevTch +  39)
#define ActSeePstForGenTch	(ActUnfSevTch +  40)
#define ActSeePstForSWAUsr	(ActUnfSevTch +  41)
#define ActSeePstForSWATch	(ActUnfSevTch +  42)
#define ActRcvThrForCrsUsr	(ActUnfSevTch +  43)
#define ActRcvThrForCrsTch	(ActUnfSevTch +  44)
#define ActRcvThrForDegUsr	(ActUnfSevTch +  45)
#define ActRcvThrForDegTch	(ActUnfSevTch +  46)
#define ActRcvThrForCtrUsr	(ActUnfSevTch +  47)
#define ActRcvThrForCtrTch	(ActUnfSevTch +  48)
#define ActRcvThrForInsUsr	(ActUnfSevTch +  49)
#define ActRcvThrForInsTch	(ActUnfSevTch +  50)
#define ActRcvThrForGenUsr	(ActUnfSevTch +  51)
#define ActRcvThrForGenTch	(ActUnfSevTch +  52)
#define ActRcvThrForSWAUsr	(ActUnfSevTch +  53)
#define ActRcvThrForSWATch	(ActUnfSevTch +  54)
#define ActRcvRepForCrsUsr	(ActUnfSevTch +  55)
#define ActRcvRepForCrsTch	(ActUnfSevTch +  56)
#define ActRcvRepForDegUsr	(ActUnfSevTch +  57)
#define ActRcvRepForDegTch	(ActUnfSevTch +  58)
#define ActRcvRepForCtrUsr	(ActUnfSevTch +  59)
#define ActRcvRepForCtrTch	(ActUnfSevTch +  60)
#define ActRcvRepForInsUsr	(ActUnfSevTch +  61)
#define ActRcvRepForInsTch	(ActUnfSevTch +  62)
#define ActRcvRepForGenUsr	(ActUnfSevTch +  63)
#define ActRcvRepForGenTch	(ActUnfSevTch +  64)
#define ActRcvRepForSWAUsr	(ActUnfSevTch +  65)
#define ActRcvRepForSWATch	(ActUnfSevTch +  66)
#define ActReqDelThrCrsUsr	(ActUnfSevTch +  67)
#define ActReqDelThrCrsTch	(ActUnfSevTch +  68)
#define ActReqDelThrDegUsr	(ActUnfSevTch +  69)
#define ActReqDelThrDegTch	(ActUnfSevTch +  70)
#define ActReqDelThrCtrUsr	(ActUnfSevTch +  71)
#define ActReqDelThrCtrTch	(ActUnfSevTch +  72)
#define ActReqDelThrInsUsr	(ActUnfSevTch +  73)
#define ActReqDelThrInsTch	(ActUnfSevTch +  74)
#define ActReqDelThrGenUsr	(ActUnfSevTch +  75)
#define ActReqDelThrGenTch	(ActUnfSevTch +  76)
#define ActReqDelThrSWAUsr	(ActUnfSevTch +  77)
#define ActReqDelThrSWATch	(ActUnfSevTch +  78)
#define ActDelThrForCrsUsr	(ActUnfSevTch +  79)
#define ActDelThrForCrsTch	(ActUnfSevTch +  80)
#define ActDelThrForDegUsr	(ActUnfSevTch +  81)
#define ActDelThrForDegTch	(ActUnfSevTch +  82)
#define ActDelThrForCtrUsr	(ActUnfSevTch +  83)
#define ActDelThrForCtrTch	(ActUnfSevTch +  84)
#define ActDelThrForInsUsr	(ActUnfSevTch +  85)
#define ActDelThrForInsTch	(ActUnfSevTch +  86)
#define ActDelThrForGenUsr	(ActUnfSevTch +  87)
#define ActDelThrForGenTch	(ActUnfSevTch +  88)
#define ActDelThrForSWAUsr	(ActUnfSevTch +  89)
#define ActDelThrForSWATch	(ActUnfSevTch +  90)
#define ActCutThrForCrsUsr	(ActUnfSevTch +  91)
#define ActCutThrForCrsTch	(ActUnfSevTch +  92)
#define ActCutThrForDegUsr	(ActUnfSevTch +  93)
#define ActCutThrForDegTch	(ActUnfSevTch +  94)
#define ActCutThrForCtrUsr	(ActUnfSevTch +  95)
#define ActCutThrForCtrTch	(ActUnfSevTch +  96)
#define ActCutThrForInsUsr	(ActUnfSevTch +  97)
#define ActCutThrForInsTch	(ActUnfSevTch +  98)
#define ActCutThrForGenUsr	(ActUnfSevTch +  99)
#define ActCutThrForGenTch	(ActUnfSevTch + 100)
#define ActCutThrForSWAUsr	(ActUnfSevTch + 101)
#define ActCutThrForSWATch	(ActUnfSevTch + 102)
#define ActPasThrForCrsUsr	(ActUnfSevTch + 103)
#define ActPasThrForCrsTch	(ActUnfSevTch + 104)
#define ActPasThrForDegUsr	(ActUnfSevTch + 105)
#define ActPasThrForDegTch	(ActUnfSevTch + 106)
#define ActPasThrForCtrUsr	(ActUnfSevTch + 107)
#define ActPasThrForCtrTch	(ActUnfSevTch + 108)
#define ActPasThrForInsUsr	(ActUnfSevTch + 109)
#define ActPasThrForInsTch	(ActUnfSevTch + 110)
#define ActPasThrForGenUsr	(ActUnfSevTch + 111)
#define ActPasThrForGenTch	(ActUnfSevTch + 112)
#define ActPasThrForSWAUsr	(ActUnfSevTch + 113)
#define ActPasThrForSWATch	(ActUnfSevTch + 114)
#define ActDelPstForCrsUsr	(ActUnfSevTch + 115)
#define ActDelPstForCrsTch	(ActUnfSevTch + 116)
#define ActDelPstForDegUsr	(ActUnfSevTch + 117)
#define ActDelPstForDegTch	(ActUnfSevTch + 118)
#define ActDelPstForCtrUsr	(ActUnfSevTch + 119)
#define ActDelPstForCtrTch	(ActUnfSevTch + 120)
#define ActDelPstForInsUsr	(ActUnfSevTch + 121)
#define ActDelPstForInsTch	(ActUnfSevTch + 122)
#define ActDelPstForGenUsr	(ActUnfSevTch + 123)
#define ActDelPstForGenTch	(ActUnfSevTch + 124)
#define ActDelPstForSWAUsr	(ActUnfSevTch + 125)
#define ActDelPstForSWATch	(ActUnfSevTch + 126)
#define ActEnbPstForCrsUsr	(ActUnfSevTch + 127)
#define ActEnbPstForCrsTch	(ActUnfSevTch + 128)
#define ActEnbPstForDegUsr	(ActUnfSevTch + 129)
#define ActEnbPstForDegTch	(ActUnfSevTch + 130)
#define ActEnbPstForCtrUsr	(ActUnfSevTch + 131)
#define ActEnbPstForCtrTch	(ActUnfSevTch + 132)
#define ActEnbPstForInsUsr	(ActUnfSevTch + 133)
#define ActEnbPstForInsTch	(ActUnfSevTch + 134)
#define ActEnbPstForGenUsr	(ActUnfSevTch + 135)
#define ActEnbPstForGenTch	(ActUnfSevTch + 136)
#define ActEnbPstForSWAUsr	(ActUnfSevTch + 137)
#define ActEnbPstForSWATch	(ActUnfSevTch + 138)
#define ActDisPstForCrsUsr	(ActUnfSevTch + 139)
#define ActDisPstForCrsTch	(ActUnfSevTch + 140)
#define ActDisPstForDegUsr	(ActUnfSevTch + 141)
#define ActDisPstForDegTch	(ActUnfSevTch + 142)
#define ActDisPstForCtrUsr	(ActUnfSevTch + 143)
#define ActDisPstForCtrTch	(ActUnfSevTch + 144)
#define ActDisPstForInsUsr	(ActUnfSevTch + 145)
#define ActDisPstForInsTch	(ActUnfSevTch + 146)
#define ActDisPstForGenUsr	(ActUnfSevTch + 147)
#define ActDisPstForGenTch	(ActUnfSevTch + 148)
#define ActDisPstForSWAUsr	(ActUnfSevTch + 149)
#define ActDisPstForSWATch	(ActUnfSevTch + 150)
#define ActReqLnkForCrsUsr	(ActUnfSevTch + 151)

#define ActCht			(ActUnfSevTch + 152)

#define ActReqMsgUsr		(ActUnfSevTch + 153)
#define ActSeeSntMsg		(ActUnfSevTch + 154)

#define ActRcvMsgUsr		(ActUnfSevTch + 155)
#define ActReqDelAllSntMsg	(ActUnfSevTch + 156)
#define ActReqDelAllRcvMsg	(ActUnfSevTch + 157)
#define ActDelAllSntMsg		(ActUnfSevTch + 158)
#define ActDelAllRcvMsg		(ActUnfSevTch + 159)
#define ActDelSntMsg		(ActUnfSevTch + 160)
#define ActDelRcvMsg		(ActUnfSevTch + 161)
#define ActExpSntMsg		(ActUnfSevTch + 162)
#define ActExpRcvMsg		(ActUnfSevTch + 163)
#define ActConSntMsg		(ActUnfSevTch + 164)
#define ActConRcvMsg		(ActUnfSevTch + 165)
#define ActLstBanUsr		(ActUnfSevTch + 166)
#define ActBanUsrMsg		(ActUnfSevTch + 167)
#define ActUnbUsrMsg		(ActUnfSevTch + 168)
#define ActUnbUsrLst		(ActUnfSevTch + 169)

#define ActMaiUsr		(ActUnfSevTch + 170)

/*****************************************************************************/
/****************************** Analytics tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActReqUseGbl		(ActMaiUsr +  1)
#define ActSeePhoDeg		(ActMaiUsr +  2)
#define ActReqStaCrs		(ActMaiUsr +  3)
#define ActSeeAllSvy		(ActMaiUsr +  4)
#define ActReqAccGbl		(ActMaiUsr +  5)
#define ActReqMyUsgRep		(ActMaiUsr +  6)
#define ActMFUAct		(ActMaiUsr +  7)

// Secondary actions
#define ActSeeUseGbl		(ActMaiUsr +  8)
#define ActPrnPhoDeg		(ActMaiUsr +  9)
#define ActCalPhoDeg		(ActMaiUsr + 10)

#define ActSeeAllStaCrs		(ActMaiUsr + 11)

#define ActSeeSvy		(ActMaiUsr + 12)
#define ActAnsSvy		(ActMaiUsr + 13)
#define ActFrmNewSvy		(ActMaiUsr + 14)
#define ActEdiOneSvy		(ActMaiUsr + 15)
#define ActNewSvy		(ActMaiUsr + 16)
#define ActChgSvy		(ActMaiUsr + 17)
#define ActReqRemSvy		(ActMaiUsr + 18)
#define ActRemSvy		(ActMaiUsr + 19)
#define ActReqRstSvy		(ActMaiUsr + 20)
#define ActRstSvy		(ActMaiUsr + 21)
#define ActHidSvy		(ActMaiUsr + 22)
#define ActUnhSvy		(ActMaiUsr + 23)
#define ActReqLnkSvy		(ActMaiUsr + 24)

#define ActEdiOneSvyQst		(ActMaiUsr + 25)
#define ActRcvSvyQst		(ActMaiUsr + 26)
#define ActReqRemSvyQst		(ActMaiUsr + 27)
#define ActRemSvyQst		(ActMaiUsr + 28)

#define ActSeeAccGbl		(ActMaiUsr + 29)
#define ActReqAccCrs		(ActMaiUsr + 30)
#define ActSeeAccCrs		(ActMaiUsr + 31)

#define ActLstClk		(ActMaiUsr + 32)
#define ActRefLstClk		(ActMaiUsr + 33)

#define ActSeeMyUsgRep		(ActMaiUsr + 34)

/*****************************************************************************/
/******************************** Profile tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActFrmRolSes		(ActSeeMyUsgRep +  1)
#define ActMyCrs		(ActSeeMyUsgRep +  2)
#define ActSeeMyTT		(ActSeeMyUsgRep +  3)
#define ActSeeMyAgd		(ActSeeMyUsgRep +  4)
#define ActFrmMyAcc		(ActSeeMyUsgRep +  5)
#define ActReqEdiRecSha		(ActSeeMyUsgRep +  6)
#define ActReqEdiSet		(ActSeeMyUsgRep +  7)
// Secondary actions
#define ActChgMyRol		(ActSeeMyUsgRep +  8)
#define ActFrmNewEvtMyAgd	(ActSeeMyUsgRep +  9)
#define ActEdiOneEvtMyAgd	(ActSeeMyUsgRep + 10)
#define ActNewEvtMyAgd		(ActSeeMyUsgRep + 11)
#define ActChgEvtMyAgd		(ActSeeMyUsgRep + 12)
#define ActReqRemEvtMyAgd	(ActSeeMyUsgRep + 13)
#define ActRemEvtMyAgd		(ActSeeMyUsgRep + 14)
#define ActHidEvtMyAgd		(ActSeeMyUsgRep + 15)
#define ActUnhEvtMyAgd		(ActSeeMyUsgRep + 16)
#define ActPrvEvtMyAgd		(ActSeeMyUsgRep + 17)
#define ActPubEvtMyAgd		(ActSeeMyUsgRep + 18)
#define ActPrnAgdQR		(ActSeeMyUsgRep + 19)

#define ActChkUsrAcc		(ActSeeMyUsgRep + 20)
#define ActCreMyAcc		(ActSeeMyUsgRep + 21)
#define ActCreUsrAcc		(ActSeeMyUsgRep + 22)
#define ActRemMyID		(ActSeeMyUsgRep + 23)
#define ActChgMyID		(ActSeeMyUsgRep + 24)
#define ActRemMyNck		(ActSeeMyUsgRep + 25)
#define ActChgMyNck		(ActSeeMyUsgRep + 26)
#define ActRemMyMai		(ActSeeMyUsgRep + 27)
#define ActChgMyMai		(ActSeeMyUsgRep + 28)
#define ActCnfMai		(ActSeeMyUsgRep + 29)
#define ActChgMyPwd		(ActSeeMyUsgRep + 30)
#define ActReqRemMyAcc		(ActSeeMyUsgRep + 31)
#define ActRemMyAcc		(ActSeeMyUsgRep + 32)

#define ActChgMyData		(ActSeeMyUsgRep + 33)

#define ActReqMyPho		(ActSeeMyUsgRep + 34)
#define ActDetMyPho		(ActSeeMyUsgRep + 35)
#define ActUpdMyPho		(ActSeeMyUsgRep + 36)
#define ActReqRemMyPho		(ActSeeMyUsgRep + 37)
#define ActRemMyPho		(ActSeeMyUsgRep + 38)

#define ActChgCtyMyIns		(ActSeeMyUsgRep + 39)
#define ActChgMyIns		(ActSeeMyUsgRep + 40)
#define ActChgMyCtr		(ActSeeMyUsgRep + 41)
#define ActChgMyDpt		(ActSeeMyUsgRep + 42)
#define ActChgMyOff		(ActSeeMyUsgRep + 43)
#define ActChgMyOffPho		(ActSeeMyUsgRep + 44)

#define ActReqEdiMyNet		(ActSeeMyUsgRep + 45)
#define ActChgMyNet		(ActSeeMyUsgRep + 46)

#define ActChgThe		(ActSeeMyUsgRep + 47)
#define ActReqChgLan		(ActSeeMyUsgRep + 48)
#define ActChgLan		(ActSeeMyUsgRep + 49)
#define ActChg1stDay		(ActSeeMyUsgRep + 50)
#define ActChgDatFmt		(ActSeeMyUsgRep + 51)
#define ActChgCol		(ActSeeMyUsgRep + 52)
#define ActChgIco		(ActSeeMyUsgRep + 53)
#define ActChgMnu		(ActSeeMyUsgRep + 54)
#define ActChgUsrPho		(ActSeeMyUsgRep + 55)
#define ActChgPriPho		(ActSeeMyUsgRep + 56)
#define ActChgBasPriPrf		(ActSeeMyUsgRep + 57)
#define ActChgExtPriPrf		(ActSeeMyUsgRep + 58)
#define ActChgCooPrf		(ActSeeMyUsgRep + 59)
#define ActChgNtfPrf		(ActSeeMyUsgRep + 60)

#define ActPrnUsrQR		(ActSeeMyUsgRep + 61)

#define ActPrnMyTT		(ActSeeMyUsgRep + 62)
#define ActEdiTut		(ActSeeMyUsgRep + 63)
#define ActChgTut		(ActSeeMyUsgRep + 64)
#define ActChgMyTT1stDay	(ActSeeMyUsgRep + 65)

//-----------------------------------------------------------------------------

#define ActLst_NUM_ACTIONS		(ActChgMyTT1stDay + 1)

#define ActLst_MAX_ACTION_COD		1951

#define ActLst_DEFAULT_ACTION_AFTER_LOGIN ActSeeGblTL

#endif
