// swad_action.h: actions

#ifndef _SWAD_ACT
#define _SWAD_ACT
/*
    SWAD (Shared Workspace At a Distance),
    is a web platform developed at the University of Granada (Spain),
    and used to support university teaching.

    This file is part of SWAD core.
    Copyright (C) 1999-2022 Antonio Cañas Vargas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*****************************************************************************/
/********************************** Headers **********************************/
/*****************************************************************************/

#include <stdbool.h>		// For boolean type

#include "swad_constant.h"
#include "swad_cryptography.h"
#include "swad_language.h"
#include "swad_string.h"
#include "swad_tab.h"

/*****************************************************************************/
/****************************** Public constants *****************************/
/*****************************************************************************/

#define Act_MAX_CHARS_ACTION_TXT	(256 - 1)			// 255
#define Act_MAX_BYTES_ACTION_TXT	Act_MAX_CHARS_ACTION_TXT	// 255

#define Act_NUM_CONTENTS 2
typedef enum
  {
   Act_CONT_NORM,
   Act_CONT_DATA,
  } Act_Content_t;

typedef enum
  {
   Act_BRW_UNK_TAB,	// Unknown tab
   Act_BRW_1ST_TAB,	// The main (original, first) tab in the browser
   Act_BRW_NEW_TAB,	// A new (second) blank tab in the browser
   Act_BRW_2ND_TAB,	// The second tab in the browser
   Act_AJAX_NORMAL,	// Update a zone of the page using AJAX
   Act_AJAX_RFRESH,	// Update a zone of the page using AJAX, with auto-refresh
   Act_UPLOAD_FILE,	// Upload a file. Do not write HTML content. Write Status code instead for Dropzone.js
   Act_DOWNLD_FILE,	// Download a file in a new tab. Do not write HTML content.
   Act_204_NO_CONT,	// Do not write HTML content. HTTP will return Status 204 No Content
   Act_WEB_SERVICE,	// Web service. Send output to client using SOAP.
  } Act_BrowserTab_t;

typedef signed int Act_Action_t;	// Must be a signed type, because -1 is used to indicate obsolete action

#define Act_MAX_ACTION_COD		1950

#define Act_MAX_OPTIONS_IN_MENU_PER_TAB	  13

/*****************************************************************************/
/************************* Not asociates with tabs ***************************/
/*****************************************************************************/
#define ActAll			 0

#define ActUnk			 1
#define ActMnu			 2

#define ActRefCon		 3

#define ActWebSvc		 4

/*****************************************************************************/
/********************************* Start tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActFrmLogIn		(ActWebSvc +   1)
#define ActReqSch		(ActWebSvc +   2)
#define ActSeeGblTL		(ActWebSvc +   3)
#define ActSeeSocPrf		(ActWebSvc +   4)
#define ActSeeCal		(ActWebSvc +   5)
#define ActSeeNtf		(ActWebSvc +   6)

// Secondary actions
#define ActLogIn		(ActWebSvc +   7)
#define ActLogInNew		(ActWebSvc +   8)
#define ActLogInLan		(ActWebSvc +   9)
#define ActAnnSee		(ActWebSvc +  10)
#define ActReqSndNewPwd		(ActWebSvc +  11)
#define ActSndNewPwd		(ActWebSvc +  12)
#define ActLogOut		(ActWebSvc +  13)

#define ActSch			(ActWebSvc +  14)

#define ActRefNewPubGblTL	(ActWebSvc +  15)
#define ActRefOldPubGblTL	(ActWebSvc +  16)
#define ActRcvPstGblTL		(ActWebSvc +  17)
#define ActRcvComGblTL		(ActWebSvc +  18)
#define ActShoHidComGblTL	(ActWebSvc +  19)
#define ActAllShaNotGblTL	(ActWebSvc +  20)
#define ActAllFavNotGblTL	(ActWebSvc +  21)
#define ActAllFavComGblTL	(ActWebSvc +  22)
#define ActShaNotGblTL		(ActWebSvc +  23)
#define ActUnsNotGblTL		(ActWebSvc +  24)
#define ActFavNotGblTL		(ActWebSvc +  25)
#define ActUnfNotGblTL		(ActWebSvc +  26)
#define ActFavComGblTL		(ActWebSvc +  27)
#define ActUnfComGblTL		(ActWebSvc +  28)
#define ActReqRemPubGblTL	(ActWebSvc +  29)
#define ActRemPubGblTL		(ActWebSvc +  30)
#define ActReqRemComGblTL	(ActWebSvc +  31)
#define ActRemComGblTL		(ActWebSvc +  32)

#define ActReqOthPubPrf		(ActWebSvc +  33)

#define ActRefOldPubUsrTL	(ActWebSvc +  34)
#define ActRcvPstUsrTL		(ActWebSvc +  35)
#define ActRcvComUsrTL		(ActWebSvc +  36)
#define ActShoHidComUsrTL	(ActWebSvc +  37)
#define ActAllShaNotUsrTL	(ActWebSvc +  38)
#define ActAllFavNotUsrTL	(ActWebSvc +  39)
#define ActAllFavComUsrTL	(ActWebSvc +  40)
#define ActShaNotUsrTL		(ActWebSvc +  41)
#define ActUnsNotUsrTL		(ActWebSvc +  42)
#define ActFavNotUsrTL		(ActWebSvc +  43)
#define ActUnfNotUsrTL		(ActWebSvc +  44)
#define ActFavComUsrTL		(ActWebSvc +  45)
#define ActUnfComUsrTL		(ActWebSvc +  46)
#define ActReqRemPubUsrTL	(ActWebSvc +  47)
#define ActRemPubUsrTL		(ActWebSvc +  48)
#define ActReqRemComUsrTL	(ActWebSvc +  49)
#define ActRemComUsrTL		(ActWebSvc +  50)

#define ActSeeOthPubPrf		(ActWebSvc +  51)
#define ActCalFig		(ActWebSvc +  52)

#define ActFolUsr		(ActWebSvc +  53)
#define ActUnfUsr		(ActWebSvc +  54)
#define ActSeeFlg		(ActWebSvc +  55)
#define ActSeeFlr		(ActWebSvc +  56)

#define ActPrnCal		(ActWebSvc +  57)
#define ActChgCal1stDay		(ActWebSvc +  58)

#define ActSeeNewNtf		(ActWebSvc +  59)
#define ActMrkNtfSee		(ActWebSvc +  60)
#define ActSeeMai		(ActWebSvc +  61)
#define ActEdiMai		(ActWebSvc +  62)
#define ActNewMai		(ActWebSvc +  63)
#define ActRemMai		(ActWebSvc +  64)
#define ActRenMaiSho		(ActWebSvc +  65)
#define ActRenMaiFul		(ActWebSvc +  66)

/*****************************************************************************/
/******************************** System tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeSysInf		(ActRenMaiFul +  1)
#define ActSeeCty		(ActRenMaiFul +  2)
#define ActSeePen		(ActRenMaiFul +  3)
#define ActSeeLnk		(ActRenMaiFul +  4)
#define ActLstPlg		(ActRenMaiFul +  5)
#define ActMtn			(ActRenMaiFul +  6)

// Secondary actions
#define ActPrnSysInf		(ActRenMaiFul +  7)

#define ActEdiCty		(ActRenMaiFul +  8)
#define ActNewCty		(ActRenMaiFul +  9)
#define ActRemCty		(ActRenMaiFul + 10)
#define ActRenCty		(ActRenMaiFul + 11)
#define ActChgCtyWWW		(ActRenMaiFul + 12)

#define ActSeeBan		(ActRenMaiFul + 13)
#define ActEdiBan		(ActRenMaiFul + 14)
#define ActNewBan		(ActRenMaiFul + 15)
#define ActRemBan		(ActRenMaiFul + 16)
#define ActUnhBan		(ActRenMaiFul + 17)
#define ActHidBan		(ActRenMaiFul + 18)
#define ActRenBanSho		(ActRenMaiFul + 19)
#define ActRenBanFul		(ActRenMaiFul + 20)
#define ActChgBanImg		(ActRenMaiFul + 21)
#define ActChgBanWWW		(ActRenMaiFul + 22)
#define ActClkBan		(ActRenMaiFul + 23)

#define ActEdiLnk		(ActRenMaiFul + 24)
#define ActNewLnk		(ActRenMaiFul + 25)
#define ActRemLnk		(ActRenMaiFul + 26)
#define ActRenLnkSho		(ActRenMaiFul + 27)
#define ActRenLnkFul		(ActRenMaiFul + 28)
#define ActChgLnkWWW		(ActRenMaiFul + 29)

#define ActEdiPlg		(ActRenMaiFul + 30)
#define ActNewPlg		(ActRenMaiFul + 31)
#define ActRemPlg		(ActRenMaiFul + 32)
#define ActRenPlg		(ActRenMaiFul + 33)
#define ActChgPlgDes		(ActRenMaiFul + 34)
#define ActChgPlgLog		(ActRenMaiFul + 35)
#define ActChgPlgAppKey		(ActRenMaiFul + 36)
#define ActChgPlgURL		(ActRenMaiFul + 37)
#define ActChgPlgIP		(ActRenMaiFul + 38)

#define ActSetUp		(ActRenMaiFul + 39)
#define ActReqRemOldCrs		(ActRenMaiFul + 40)
#define ActRemOldCrs		(ActRenMaiFul + 41)

/*****************************************************************************/
/******************************** Country tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCtyInf		(ActRemOldCrs +  1)
#define ActSeeIns		(ActRemOldCrs +  2)

// Secondary actions
#define ActPrnCtyInf		(ActRemOldCrs +  3)
#define ActChgCtyMapAtt		(ActRemOldCrs +  4)

#define ActEdiIns		(ActRemOldCrs +  5)
#define ActReqIns		(ActRemOldCrs +  6)
#define ActNewIns		(ActRemOldCrs +  7)
#define ActRemIns		(ActRemOldCrs +  8)
#define ActRenInsSho		(ActRemOldCrs +  9)
#define ActRenInsFul		(ActRemOldCrs + 10)
#define ActChgInsWWW		(ActRemOldCrs + 11)
#define ActChgInsSta		(ActRemOldCrs + 12)

/*****************************************************************************/
/****************************** Institution tab ******************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeInsInf		(ActChgInsSta +  1)
#define ActSeeCtr		(ActChgInsSta +  2)
#define ActSeePlc		(ActChgInsSta +  3)
#define ActSeeDpt		(ActChgInsSta +  4)
#define ActSeeHld		(ActChgInsSta +  5)

// Secondary actions
#define ActPrnInsInf		(ActChgInsSta +  6)
#define ActChgInsCtyCfg		(ActChgInsSta +  7)
#define ActRenInsShoCfg		(ActChgInsSta +  8)
#define ActRenInsFulCfg		(ActChgInsSta +  9)
#define ActChgInsWWWCfg		(ActChgInsSta + 10)
#define ActReqInsLog		(ActChgInsSta + 11)
#define ActRecInsLog		(ActChgInsSta + 12)
#define ActRemInsLog		(ActChgInsSta + 13)

#define ActEdiCtr		(ActChgInsSta + 14)
#define ActReqCtr		(ActChgInsSta + 15)
#define ActNewCtr		(ActChgInsSta + 16)
#define ActRemCtr		(ActChgInsSta + 17)
#define ActChgCtrPlc		(ActChgInsSta + 18)
#define ActRenCtrSho		(ActChgInsSta + 19)
#define ActRenCtrFul		(ActChgInsSta + 20)
#define ActChgCtrWWW		(ActChgInsSta + 21)
#define ActChgCtrSta		(ActChgInsSta + 22)

#define ActEdiPlc		(ActChgInsSta + 23)
#define ActNewPlc		(ActChgInsSta + 24)
#define ActRemPlc		(ActChgInsSta + 25)
#define ActRenPlcSho		(ActChgInsSta + 26)
#define ActRenPlcFul		(ActChgInsSta + 27)

#define ActEdiDpt		(ActChgInsSta + 28)
#define ActNewDpt		(ActChgInsSta + 29)
#define ActRemDpt		(ActChgInsSta + 30)
#define ActChgDptIns		(ActChgInsSta + 31)
#define ActRenDptSho		(ActChgInsSta + 32)
#define ActRenDptFul		(ActChgInsSta + 33)
#define ActChgDptWWW		(ActChgInsSta + 34)

#define ActEdiHld		(ActChgInsSta + 35)
#define ActNewHld		(ActChgInsSta + 36)
#define ActRemHld		(ActChgInsSta + 37)
#define ActChgHldPlc		(ActChgInsSta + 38)
#define ActChgHldTyp		(ActChgInsSta + 39)
#define ActChgHldStrDat		(ActChgInsSta + 40)
#define ActChgHldEndDat		(ActChgInsSta + 41)
#define ActRenHld		(ActChgInsSta + 42)

/*****************************************************************************/
/********************************* Center tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCtrInf		(ActRenHld +  1)
#define ActSeeDeg		(ActRenHld +  2)
#define ActSeeBld		(ActRenHld +  3)
#define ActSeeRoo		(ActRenHld +  4)

// Secondary actions
#define ActPrnCtrInf		(ActRenHld +  5)
#define ActChgCtrInsCfg		(ActRenHld +  6)
#define ActRenCtrShoCfg		(ActRenHld +  7)
#define ActRenCtrFulCfg		(ActRenHld +  8)
#define ActChgCtrPlcCfg		(ActRenHld +  9)
#define ActChgCtrLatCfg		(ActRenHld + 10)
#define ActChgCtrLgtCfg		(ActRenHld + 11)
#define ActChgCtrAltCfg		(ActRenHld + 12)
#define ActChgCtrWWWCfg		(ActRenHld + 13)
#define ActReqCtrLog		(ActRenHld + 14)
#define ActRecCtrLog		(ActRenHld + 15)
#define ActRemCtrLog		(ActRenHld + 16)
#define ActReqCtrPho		(ActRenHld + 17)
#define ActRecCtrPho		(ActRenHld + 18)
#define ActChgCtrPhoAtt		(ActRenHld + 19)

#define ActSeeDegTyp		(ActRenHld + 20)
#define ActEdiDegTyp		(ActRenHld + 21)
#define ActNewDegTyp		(ActRenHld + 22)
#define ActRemDegTyp		(ActRenHld + 23)
#define ActRenDegTyp		(ActRenHld + 24)

#define ActEdiDeg		(ActRenHld + 25)
#define ActReqDeg		(ActRenHld + 26)
#define ActNewDeg		(ActRenHld + 27)
#define ActRemDeg		(ActRenHld + 28)
#define ActRenDegSho		(ActRenHld + 29)
#define ActRenDegFul		(ActRenHld + 30)
#define ActChgDegTyp		(ActRenHld + 31)
#define ActChgDegWWW		(ActRenHld + 32)
#define ActChgDegSta		(ActRenHld + 33)

#define ActEdiBld		(ActRenHld + 34)
#define ActNewBld		(ActRenHld + 35)
#define ActRemBld		(ActRenHld + 36)
#define ActRenBldSho		(ActRenHld + 37)
#define ActRenBldFul		(ActRenHld + 38)
#define ActRenBldLoc		(ActRenHld + 39)

#define ActEdiRoo		(ActRenHld + 40)
#define ActNewRoo		(ActRenHld + 41)
#define ActRemRoo		(ActRenHld + 42)
#define ActChgRooBld		(ActRenHld + 43)
#define ActChgRooFlo		(ActRenHld + 44)
#define ActChgRooTyp		(ActRenHld + 45)
#define ActRenRooSho		(ActRenHld + 46)
#define ActRenRooFul		(ActRenHld + 47)
#define ActChgRooMaxUsr		(ActRenHld + 48)
#define ActChgRooMAC		(ActRenHld + 49)

/*****************************************************************************/
/********************************* Degree tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeDegInf		(ActChgRooMAC +  1)
#define ActSeeCrs		(ActChgRooMAC +  2)

// Secondary actions
#define ActPrnDegInf		(ActChgRooMAC +  3)
#define ActChgDegCtrCfg		(ActChgRooMAC +  4)
#define ActRenDegShoCfg		(ActChgRooMAC +  5)
#define ActRenDegFulCfg		(ActChgRooMAC +  6)
#define ActChgDegWWWCfg		(ActChgRooMAC +  7)
#define ActReqDegLog		(ActChgRooMAC +  8)
#define ActRecDegLog		(ActChgRooMAC +  9)
#define ActRemDegLog		(ActChgRooMAC + 10)

#define ActEdiCrs		(ActChgRooMAC + 11)
#define ActReqCrs		(ActChgRooMAC + 12)
#define ActNewCrs		(ActChgRooMAC + 13)
#define ActRemCrs		(ActChgRooMAC + 14)
#define ActChgInsCrsCod		(ActChgRooMAC + 15)
#define ActChgCrsYea		(ActChgRooMAC + 16)
#define ActRenCrsSho		(ActChgRooMAC + 17)
#define ActRenCrsFul		(ActChgRooMAC + 18)
#define ActChgCrsSta		(ActChgRooMAC + 19)

/*****************************************************************************/
/******************************** Course tab *********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeCrsInf		(ActChgCrsSta +   1)
#define ActSeePrg		(ActChgCrsSta +   2)
#define ActSeeTchGui		(ActChgCrsSta +   3)
#define ActSeeSyl		(ActChgCrsSta +   4)
#define ActSeeBib		(ActChgCrsSta +   5)
#define ActSeeFAQ		(ActChgCrsSta +   6)
#define ActSeeCrsLnk		(ActChgCrsSta +   7)
#define ActSeeCrsTT		(ActChgCrsSta +   8)

// Secondary actions
#define ActPrnCrsInf		(ActChgCrsSta +   9)
#define ActChgCrsDegCfg		(ActChgCrsSta +  10)
#define ActRenCrsShoCfg		(ActChgCrsSta +  11)
#define ActRenCrsFulCfg		(ActChgCrsSta +  12)
#define ActChgInsCrsCodCfg	(ActChgCrsSta +  13)
#define ActChgCrsYeaCfg		(ActChgCrsSta +  14)
#define ActEdiCrsInf		(ActChgCrsSta +  15)
#define ActEdiPrg		(ActChgCrsSta +  16)
#define ActSeePrgItm		(ActChgCrsSta +  17)
#define ActFrmChgPrgItm		(ActChgCrsSta +  18)
#define ActFrmNewPrgItm		(ActChgCrsSta +  19)
#define ActChgPrgItm		(ActChgCrsSta +  20)
#define ActNewPrgItm		(ActChgCrsSta +  21)
#define ActReqRemPrgItm		(ActChgCrsSta +  22)
#define ActRemPrgItm		(ActChgCrsSta +  23)
#define ActHidPrgItm		(ActChgCrsSta +  24)
#define ActUnhPrgItm		(ActChgCrsSta +  25)
#define ActUp_PrgItm		(ActChgCrsSta +  26)
#define ActDwnPrgItm		(ActChgCrsSta +  27)
#define ActLftPrgItm		(ActChgCrsSta +  28)
#define ActRgtPrgItm		(ActChgCrsSta +  29)
#define ActExpSeePrgItm		(ActChgCrsSta +  30)
#define ActConSeePrgItm		(ActChgCrsSta +  31)
#define ActExpEdiPrgItm		(ActChgCrsSta +  32)
#define ActConEdiPrgItm		(ActChgCrsSta +  33)
#define ActFrmSeePrgRsc		(ActChgCrsSta +  34)
#define ActFrmEdiPrgRsc		(ActChgCrsSta +  35)
#define ActNewPrgRsc		(ActChgCrsSta +  36)
#define ActRenPrgRsc		(ActChgCrsSta +  37)
#define ActReqRemPrgRsc		(ActChgCrsSta +  38)
#define ActRemPrgRsc		(ActChgCrsSta +  39)
#define ActHidPrgRsc		(ActChgCrsSta +  40)
#define ActUnhPrgRsc		(ActChgCrsSta +  41)
#define ActUp_PrgRsc		(ActChgCrsSta +  42)
#define ActDwnPrgRsc		(ActChgCrsSta +  43)
#define ActSeeCliPrgRsc		(ActChgCrsSta +  44)
#define ActChgLnkPrgRsc		(ActChgCrsSta +  45)
#define ActEdiTchGui		(ActChgCrsSta +  46)
#define ActSeeSylLec		(ActChgCrsSta +  47)
#define ActSeeSylPra		(ActChgCrsSta +  48)
#define ActEdiSylLec		(ActChgCrsSta +  49)
#define ActEdiSylPra		(ActChgCrsSta +  50)
#define ActDelItmSylLec		(ActChgCrsSta +  51)
#define ActDelItmSylPra		(ActChgCrsSta +  52)
#define ActUp_IteSylLec		(ActChgCrsSta +  53)
#define ActUp_IteSylPra		(ActChgCrsSta +  54)
#define ActDwnIteSylLec		(ActChgCrsSta +  55)
#define ActDwnIteSylPra		(ActChgCrsSta +  56)
#define ActRgtIteSylLec		(ActChgCrsSta +  57)
#define ActRgtIteSylPra		(ActChgCrsSta +  58)
#define ActLftIteSylLec		(ActChgCrsSta +  59)
#define ActLftIteSylPra		(ActChgCrsSta +  60)
#define ActInsIteSylLec		(ActChgCrsSta +  61)
#define ActInsIteSylPra		(ActChgCrsSta +  62)
#define ActModIteSylLec		(ActChgCrsSta +  63)
#define ActModIteSylPra		(ActChgCrsSta +  64)

#define ActEdiBib		(ActChgCrsSta +  65)
#define ActEdiFAQ		(ActChgCrsSta +  66)
#define ActEdiCrsLnk		(ActChgCrsSta +  67)

#define ActChgFrcReaCrsInf	(ActChgCrsSta +  68)
#define ActChgFrcReaTchGui	(ActChgCrsSta +  69)
#define ActChgFrcReaSylLec	(ActChgCrsSta +  70)
#define ActChgFrcReaSylPra	(ActChgCrsSta +  71)
#define ActChgFrcReaBib		(ActChgCrsSta +  72)
#define ActChgFrcReaFAQ		(ActChgCrsSta +  73)
#define ActChgFrcReaCrsLnk	(ActChgCrsSta +  74)

#define ActChgHavReaCrsInf	(ActChgCrsSta +  75)
#define ActChgHavReaTchGui	(ActChgCrsSta +  76)
#define ActChgHavReaSylLec	(ActChgCrsSta +  77)
#define ActChgHavReaSylPra	(ActChgCrsSta +  78)
#define ActChgHavReaBib		(ActChgCrsSta +  79)
#define ActChgHavReaFAQ		(ActChgCrsSta +  80)
#define ActChgHavReaCrsLnk	(ActChgCrsSta +  81)

#define ActSelInfSrcCrsInf	(ActChgCrsSta +  82)
#define ActSelInfSrcTchGui	(ActChgCrsSta +  83)
#define ActSelInfSrcSylLec	(ActChgCrsSta +  84)
#define ActSelInfSrcSylPra	(ActChgCrsSta +  85)
#define ActSelInfSrcBib		(ActChgCrsSta +  86)
#define ActSelInfSrcFAQ		(ActChgCrsSta +  87)
#define ActSelInfSrcCrsLnk	(ActChgCrsSta +  88)
#define ActRcvURLCrsInf		(ActChgCrsSta +  89)
#define ActRcvURLTchGui		(ActChgCrsSta +  90)
#define ActRcvURLSylLec		(ActChgCrsSta +  91)
#define ActRcvURLSylPra		(ActChgCrsSta +  92)
#define ActRcvURLBib		(ActChgCrsSta +  93)
#define ActRcvURLFAQ		(ActChgCrsSta +  94)
#define ActRcvURLCrsLnk		(ActChgCrsSta +  95)
#define ActRcvPagCrsInf		(ActChgCrsSta +  96)
#define ActRcvPagTchGui		(ActChgCrsSta +  97)
#define ActRcvPagSylLec		(ActChgCrsSta +  98)
#define ActRcvPagSylPra		(ActChgCrsSta +  99)
#define ActRcvPagBib		(ActChgCrsSta + 100)
#define ActRcvPagFAQ		(ActChgCrsSta + 101)
#define ActRcvPagCrsLnk		(ActChgCrsSta + 102)
#define ActEditorCrsInf		(ActChgCrsSta + 103)
#define ActEditorTchGui		(ActChgCrsSta + 104)
#define ActEditorSylLec		(ActChgCrsSta + 105)
#define ActEditorSylPra		(ActChgCrsSta + 106)
#define ActEditorBib		(ActChgCrsSta + 107)
#define ActEditorFAQ		(ActChgCrsSta + 108)
#define ActEditorCrsLnk		(ActChgCrsSta + 109)
#define ActPlaTxtEdiCrsInf	(ActChgCrsSta + 110)
#define ActPlaTxtEdiTchGui	(ActChgCrsSta + 111)
#define ActPlaTxtEdiSylLec	(ActChgCrsSta + 112)
#define ActPlaTxtEdiSylPra	(ActChgCrsSta + 113)
#define ActPlaTxtEdiBib		(ActChgCrsSta + 114)
#define ActPlaTxtEdiFAQ		(ActChgCrsSta + 115)
#define ActPlaTxtEdiCrsLnk	(ActChgCrsSta + 116)
#define ActRchTxtEdiCrsInf	(ActChgCrsSta + 117)
#define ActRchTxtEdiTchGui	(ActChgCrsSta + 118)
#define ActRchTxtEdiSylLec	(ActChgCrsSta + 119)
#define ActRchTxtEdiSylPra	(ActChgCrsSta + 120)
#define ActRchTxtEdiBib		(ActChgCrsSta + 121)
#define ActRchTxtEdiFAQ		(ActChgCrsSta + 122)
#define ActRchTxtEdiCrsLnk	(ActChgCrsSta + 123)
#define ActRcvPlaTxtCrsInf	(ActChgCrsSta + 124)
#define ActRcvPlaTxtTchGui	(ActChgCrsSta + 125)
#define ActRcvPlaTxtSylLec	(ActChgCrsSta + 126)
#define ActRcvPlaTxtSylPra	(ActChgCrsSta + 127)
#define ActRcvPlaTxtBib		(ActChgCrsSta + 128)
#define ActRcvPlaTxtFAQ		(ActChgCrsSta + 129)
#define ActRcvPlaTxtCrsLnk	(ActChgCrsSta + 130)
#define ActRcvRchTxtCrsInf	(ActChgCrsSta + 131)
#define ActRcvRchTxtTchGui	(ActChgCrsSta + 132)
#define ActRcvRchTxtSylLec	(ActChgCrsSta + 133)
#define ActRcvRchTxtSylPra	(ActChgCrsSta + 134)
#define ActRcvRchTxtBib		(ActChgCrsSta + 135)
#define ActRcvRchTxtFAQ		(ActChgCrsSta + 136)
#define ActRcvRchTxtCrsLnk	(ActChgCrsSta + 137)

#define ActPrnCrsTT		(ActChgCrsSta + 138)
#define ActEdiCrsTT		(ActChgCrsSta + 139)
#define ActChgCrsTT		(ActChgCrsSta + 140)
#define ActChgCrsTT1stDay	(ActChgCrsSta + 141)

/*****************************************************************************/
/***************************** Assessment tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAss		(ActChgCrsTT1stDay +   1)
#define ActSeeAsg		(ActChgCrsTT1stDay +   2)
#define ActSeePrj		(ActChgCrsTT1stDay +   3)
#define ActSeeAllCfe		(ActChgCrsTT1stDay +   4)
#define ActEdiTstQst		(ActChgCrsTT1stDay +   5)
#define ActReqTst		(ActChgCrsTT1stDay +   6)
#define ActSeeAllExa		(ActChgCrsTT1stDay +   7)
#define ActSeeAllGam		(ActChgCrsTT1stDay +   8)
#define ActSeeAllSvy		(ActChgCrsTT1stDay +   9)

// Secondary actions
#define ActEdiAss		(ActChgCrsTT1stDay +  10)
#define ActChgFrcReaAss		(ActChgCrsTT1stDay +  11)
#define ActChgHavReaAss		(ActChgCrsTT1stDay +  12)
#define ActSelInfSrcAss		(ActChgCrsTT1stDay +  13)
#define ActRcvURLAss		(ActChgCrsTT1stDay +  14)
#define ActRcvPagAss		(ActChgCrsTT1stDay +  15)
#define ActEditorAss		(ActChgCrsTT1stDay +  16)
#define ActPlaTxtEdiAss		(ActChgCrsTT1stDay +  17)
#define ActRchTxtEdiAss		(ActChgCrsTT1stDay +  18)
#define ActRcvPlaTxtAss		(ActChgCrsTT1stDay +  19)
#define ActRcvRchTxtAss		(ActChgCrsTT1stDay +  20)

#define ActFrmNewAsg		(ActChgCrsTT1stDay +  21)
#define ActEdiOneAsg		(ActChgCrsTT1stDay +  22)
#define ActSeeOneAsg		(ActChgCrsTT1stDay +  23)
#define ActPrnOneAsg		(ActChgCrsTT1stDay +  24)
#define ActNewAsg		(ActChgCrsTT1stDay +  25)
#define ActChgAsg		(ActChgCrsTT1stDay +  26)
#define ActReqRemAsg		(ActChgCrsTT1stDay +  27)
#define ActRemAsg		(ActChgCrsTT1stDay +  28)
#define ActHidAsg		(ActChgCrsTT1stDay +  29)
#define ActUnhAsg		(ActChgCrsTT1stDay +  30)
#define ActReqLnkAsg		(ActChgCrsTT1stDay +  31)

#define ActReqUsrPrj		(ActChgCrsTT1stDay +  32)
#define ActSeeTblAllPrj		(ActChgCrsTT1stDay +  33)
#define ActCfgPrj		(ActChgCrsTT1stDay +  34)
#define ActRcvCfgPrj		(ActChgCrsTT1stDay +  35)
#define ActReqLckAllPrj		(ActChgCrsTT1stDay +  36)
#define ActReqUnlAllPrj		(ActChgCrsTT1stDay +  37)
#define ActLckAllPrj		(ActChgCrsTT1stDay +  38)
#define ActUnlAllPrj		(ActChgCrsTT1stDay +  39)
#define ActFrmNewPrj		(ActChgCrsTT1stDay +  40)
#define ActEdiOnePrj		(ActChgCrsTT1stDay +  41)
#define ActSeeOnePrj		(ActChgCrsTT1stDay +  42)
#define ActPrnOnePrj		(ActChgCrsTT1stDay +  43)
#define ActNewPrj		(ActChgCrsTT1stDay +  44)
#define ActChgPrj		(ActChgCrsTT1stDay +  45)
#define ActReqRemPrj		(ActChgCrsTT1stDay +  46)
#define ActRemPrj		(ActChgCrsTT1stDay +  47)
#define ActHidPrj		(ActChgCrsTT1stDay +  48)
#define ActUnhPrj		(ActChgCrsTT1stDay +  49)
#define ActLckPrj		(ActChgCrsTT1stDay +  50)
#define ActUnlPrj		(ActChgCrsTT1stDay +  51)
#define ActChgPrjRev		(ActChgCrsTT1stDay +  52)
#define ActReqAddStdPrj		(ActChgCrsTT1stDay +  53)
#define ActReqAddTutPrj		(ActChgCrsTT1stDay +  54)
#define ActReqAddEvlPrj		(ActChgCrsTT1stDay +  55)
#define ActAddStdPrj		(ActChgCrsTT1stDay +  56)
#define ActAddTutPrj		(ActChgCrsTT1stDay +  57)
#define ActAddEvlPrj		(ActChgCrsTT1stDay +  58)
#define ActReqRemStdPrj		(ActChgCrsTT1stDay +  59)
#define ActReqRemTutPrj		(ActChgCrsTT1stDay +  60)
#define ActReqRemEvlPrj		(ActChgCrsTT1stDay +  61)
#define ActRemStdPrj		(ActChgCrsTT1stDay +  62)
#define ActRemTutPrj		(ActChgCrsTT1stDay +  63)
#define ActRemEvlPrj		(ActChgCrsTT1stDay +  64)
#define ActReqLnkPrj		(ActChgCrsTT1stDay +  65)

#define ActAdmDocPrj		(ActChgCrsTT1stDay +  66)
#define ActReqRemFilDocPrj	(ActChgCrsTT1stDay +  67)
#define ActRemFilDocPrj		(ActChgCrsTT1stDay +  68)
#define ActRemFolDocPrj		(ActChgCrsTT1stDay +  69)
#define ActCopDocPrj		(ActChgCrsTT1stDay +  70)
#define ActPasDocPrj		(ActChgCrsTT1stDay +  71)
#define ActRemTreDocPrj		(ActChgCrsTT1stDay +  72)
#define ActFrmCreDocPrj		(ActChgCrsTT1stDay +  73)
#define ActCreFolDocPrj		(ActChgCrsTT1stDay +  74)
#define ActCreLnkDocPrj		(ActChgCrsTT1stDay +  75)
#define ActRenFolDocPrj		(ActChgCrsTT1stDay +  76)
#define ActRcvFilDocPrjDZ	(ActChgCrsTT1stDay +  77)
#define ActRcvFilDocPrjCla	(ActChgCrsTT1stDay +  78)
#define ActExpDocPrj		(ActChgCrsTT1stDay +  79)
#define ActConDocPrj		(ActChgCrsTT1stDay +  80)
#define ActZIPDocPrj		(ActChgCrsTT1stDay +  81)
#define ActReqDatDocPrj		(ActChgCrsTT1stDay +  82)
#define ActChgDatDocPrj		(ActChgCrsTT1stDay +  83)
#define ActDowDocPrj		(ActChgCrsTT1stDay +  84)

#define ActAdmAssPrj		(ActChgCrsTT1stDay +  85)
#define ActReqRemFilAssPrj	(ActChgCrsTT1stDay +  86)
#define ActRemFilAssPrj		(ActChgCrsTT1stDay +  87)
#define ActRemFolAssPrj		(ActChgCrsTT1stDay +  88)
#define ActCopAssPrj		(ActChgCrsTT1stDay +  89)
#define ActPasAssPrj		(ActChgCrsTT1stDay +  90)
#define ActRemTreAssPrj		(ActChgCrsTT1stDay +  91)
#define ActFrmCreAssPrj		(ActChgCrsTT1stDay +  92)
#define ActCreFolAssPrj		(ActChgCrsTT1stDay +  93)
#define ActCreLnkAssPrj		(ActChgCrsTT1stDay +  94)
#define ActRenFolAssPrj		(ActChgCrsTT1stDay +  95)
#define ActRcvFilAssPrjDZ	(ActChgCrsTT1stDay +  96)
#define ActRcvFilAssPrjCla	(ActChgCrsTT1stDay +  97)
#define ActExpAssPrj		(ActChgCrsTT1stDay +  98)
#define ActConAssPrj		(ActChgCrsTT1stDay +  99)
#define ActZIPAssPrj		(ActChgCrsTT1stDay + 100)
#define ActReqDatAssPrj		(ActChgCrsTT1stDay + 101)
#define ActChgDatAssPrj		(ActChgCrsTT1stDay + 102)
#define ActDowAssPrj		(ActChgCrsTT1stDay + 103)

#define ActSeeOneCfe		(ActChgCrsTT1stDay + 104)
#define ActSeeDatCfe		(ActChgCrsTT1stDay + 105)
#define ActEdiCfe		(ActChgCrsTT1stDay + 106)
#define ActRcvCfe		(ActChgCrsTT1stDay + 107)
#define ActPrnCfe		(ActChgCrsTT1stDay + 108)
#define ActReqRemCfe		(ActChgCrsTT1stDay + 109)
#define ActRemCfe		(ActChgCrsTT1stDay + 110)
#define ActHidCfe		(ActChgCrsTT1stDay + 111)
#define ActUnhCfe		(ActChgCrsTT1stDay + 112)
#define ActReqLnkCfe		(ActChgCrsTT1stDay + 113)

#define ActEdiOneTstQst		(ActChgCrsTT1stDay + 114)
#define ActReqImpTstQst		(ActChgCrsTT1stDay + 115)
#define ActImpTstQst		(ActChgCrsTT1stDay + 116)
#define ActLstTstQst		(ActChgCrsTT1stDay + 117)
#define ActRcvTstQst		(ActChgCrsTT1stDay + 118)
#define ActReqRemSevTstQst	(ActChgCrsTT1stDay + 119)
#define ActRemSevTstQst		(ActChgCrsTT1stDay + 120)
#define ActReqRemOneTstQst	(ActChgCrsTT1stDay + 121)
#define ActRemOneTstQst		(ActChgCrsTT1stDay + 122)
#define ActChgShfTstQst		(ActChgCrsTT1stDay + 123)

#define ActEdiTag		(ActChgCrsTT1stDay + 124)
#define ActEnaTag		(ActChgCrsTT1stDay + 125)
#define ActDisTag		(ActChgCrsTT1stDay + 126)
#define ActRenTag		(ActChgCrsTT1stDay + 127)

#define ActSeeTst		(ActChgCrsTT1stDay + 128)
#define ActReqAssTst		(ActChgCrsTT1stDay + 129)
#define ActAssTst		(ActChgCrsTT1stDay + 130)
#define ActCfgTst		(ActChgCrsTT1stDay + 131)
#define ActRcvCfgTst		(ActChgCrsTT1stDay + 132)

#define ActReqSeeMyTstRes	(ActChgCrsTT1stDay + 133)
#define ActSeeMyTstResCrs	(ActChgCrsTT1stDay + 134)
#define ActSeeOneTstResMe	(ActChgCrsTT1stDay + 135)
#define ActReqSeeUsrTstRes	(ActChgCrsTT1stDay + 136)
#define ActSeeUsrTstResCrs	(ActChgCrsTT1stDay + 137)
#define ActSeeOneTstResOth	(ActChgCrsTT1stDay + 138)

#define ActSeeExa		(ActChgCrsTT1stDay + 139)

#define ActFrmNewExa		(ActChgCrsTT1stDay + 140)
#define ActEdiOneExa		(ActChgCrsTT1stDay + 141)
#define ActNewExa		(ActChgCrsTT1stDay + 142)
#define ActChgExa		(ActChgCrsTT1stDay + 143)
#define ActReqRemExa		(ActChgCrsTT1stDay + 144)
#define ActRemExa		(ActChgCrsTT1stDay + 145)
#define ActHidExa		(ActChgCrsTT1stDay + 146)
#define ActUnhExa		(ActChgCrsTT1stDay + 147)
#define ActReqLnkExa		(ActChgCrsTT1stDay + 148)

#define ActFrmNewExaSet		(ActChgCrsTT1stDay + 149)
#define ActNewExaSet		(ActChgCrsTT1stDay + 150)
#define ActReqRemExaSet		(ActChgCrsTT1stDay + 151)
#define ActRemExaSet		(ActChgCrsTT1stDay + 152)
#define ActUp_ExaSet		(ActChgCrsTT1stDay + 153)
#define ActDwnExaSet		(ActChgCrsTT1stDay + 154)
#define ActChgTitExaSet		(ActChgCrsTT1stDay + 155)
#define ActChgNumQstExaSet	(ActChgCrsTT1stDay + 156)

#define ActReqAddQstExaSet	(ActChgCrsTT1stDay + 157)
#define ActLstTstQstForSet	(ActChgCrsTT1stDay + 158)
#define ActAddQstToExa		(ActChgCrsTT1stDay + 159)
#define ActReqRemSetQst		(ActChgCrsTT1stDay + 160)
#define ActRemExaQst		(ActChgCrsTT1stDay + 161)
#define ActValSetQst		(ActChgCrsTT1stDay + 162)
#define ActInvSetQst		(ActChgCrsTT1stDay + 163)

#define ActReqNewExaSes		(ActChgCrsTT1stDay + 164)
#define ActEdiOneExaSes		(ActChgCrsTT1stDay + 165)
#define ActNewExaSes		(ActChgCrsTT1stDay + 166)
#define ActChgExaSes		(ActChgCrsTT1stDay + 167)
#define ActReqRemExaSes		(ActChgCrsTT1stDay + 168)
#define ActRemExaSes		(ActChgCrsTT1stDay + 169)
#define ActHidExaSes		(ActChgCrsTT1stDay + 170)
#define ActUnhExaSes		(ActChgCrsTT1stDay + 171)

#define ActSeeExaPrn		(ActChgCrsTT1stDay + 172)
#define ActAnsExaPrn		(ActChgCrsTT1stDay + 173)
#define ActEndExaPrn		(ActChgCrsTT1stDay + 174)

#define ActSeeMyExaResCrs	(ActChgCrsTT1stDay + 175)
#define ActSeeMyExaResExa	(ActChgCrsTT1stDay + 176)
#define ActSeeMyExaResSes	(ActChgCrsTT1stDay + 177)
#define ActSeeOneExaResMe	(ActChgCrsTT1stDay + 178)
#define ActReqSeeUsrExaRes	(ActChgCrsTT1stDay + 179)
#define ActSeeUsrExaResCrs	(ActChgCrsTT1stDay + 180)
#define ActSeeUsrExaResExa	(ActChgCrsTT1stDay + 181)
#define ActSeeUsrExaResSes	(ActChgCrsTT1stDay + 182)
#define ActSeeOneExaResOth	(ActChgCrsTT1stDay + 183)
#define ActChgVisExaRes		(ActChgCrsTT1stDay + 184)

#define ActSeeGam		(ActChgCrsTT1stDay + 185)
#define ActReqRemMch		(ActChgCrsTT1stDay + 186)
#define ActRemMch		(ActChgCrsTT1stDay + 187)
#define ActEdiMch		(ActChgCrsTT1stDay + 188)
#define ActChgMch		(ActChgCrsTT1stDay + 189)
#define ActReqNewMch		(ActChgCrsTT1stDay + 190)
#define ActNewMch		(ActChgCrsTT1stDay + 191)
#define ActResMch		(ActChgCrsTT1stDay + 192)
#define ActBckMch		(ActChgCrsTT1stDay + 193)
#define ActPlyPauMch		(ActChgCrsTT1stDay + 194)
#define ActFwdMch		(ActChgCrsTT1stDay + 195)
#define ActChgNumColMch		(ActChgCrsTT1stDay + 196)
#define ActChgVisResMchQst	(ActChgCrsTT1stDay + 197)
#define ActMchCntDwn		(ActChgCrsTT1stDay + 198)
#define ActRefMchTch		(ActChgCrsTT1stDay + 199)

#define ActJoiMch		(ActChgCrsTT1stDay + 200)
#define ActSeeMchAnsQstStd	(ActChgCrsTT1stDay + 201)
#define ActRemMchAnsQstStd	(ActChgCrsTT1stDay + 202)
#define ActAnsMchQstStd		(ActChgCrsTT1stDay + 203)
#define ActRefMchStd		(ActChgCrsTT1stDay + 204)

#define ActSeeMyMchResCrs	(ActChgCrsTT1stDay + 205)
#define ActSeeMyMchResGam	(ActChgCrsTT1stDay + 206)
#define ActSeeMyMchResMch	(ActChgCrsTT1stDay + 207)
#define ActSeeOneMchResMe	(ActChgCrsTT1stDay + 208)

#define ActReqSeeUsrMchRes	(ActChgCrsTT1stDay + 209)
#define ActSeeUsrMchResCrs	(ActChgCrsTT1stDay + 210)
#define ActSeeUsrMchResGam	(ActChgCrsTT1stDay + 211)
#define ActSeeUsrMchResMch	(ActChgCrsTT1stDay + 212)
#define ActSeeOneMchResOth	(ActChgCrsTT1stDay + 213)

#define ActChgVisResMchUsr	(ActChgCrsTT1stDay + 214)

#define ActLstOneGam		(ActChgCrsTT1stDay + 215)

#define ActFrmNewGam		(ActChgCrsTT1stDay + 216)
#define ActEdiOneGam		(ActChgCrsTT1stDay + 217)
#define ActNewGam		(ActChgCrsTT1stDay + 218)
#define ActChgGam		(ActChgCrsTT1stDay + 219)
#define ActReqRemGam		(ActChgCrsTT1stDay + 220)
#define ActRemGam		(ActChgCrsTT1stDay + 221)
#define ActHidGam		(ActChgCrsTT1stDay + 222)
#define ActUnhGam		(ActChgCrsTT1stDay + 223)
#define ActAddOneGamQst		(ActChgCrsTT1stDay + 224)
#define ActGamLstTstQst		(ActChgCrsTT1stDay + 225)
#define ActAddTstQstToGam	(ActChgCrsTT1stDay + 226)
#define ActReqRemGamQst		(ActChgCrsTT1stDay + 227)
#define ActRemGamQst		(ActChgCrsTT1stDay + 228)
#define ActUp_GamQst		(ActChgCrsTT1stDay + 229)
#define ActDwnGamQst		(ActChgCrsTT1stDay + 230)
#define ActReqLnkGam		(ActChgCrsTT1stDay + 231)

#define ActSeeSvy		(ActChgCrsTT1stDay + 232)
#define ActAnsSvy		(ActChgCrsTT1stDay + 233)
#define ActFrmNewSvy		(ActChgCrsTT1stDay + 234)
#define ActEdiOneSvy		(ActChgCrsTT1stDay + 235)
#define ActNewSvy		(ActChgCrsTT1stDay + 236)
#define ActChgSvy		(ActChgCrsTT1stDay + 237)
#define ActReqRemSvy		(ActChgCrsTT1stDay + 238)
#define ActRemSvy		(ActChgCrsTT1stDay + 239)
#define ActReqRstSvy		(ActChgCrsTT1stDay + 240)
#define ActRstSvy		(ActChgCrsTT1stDay + 241)
#define ActHidSvy		(ActChgCrsTT1stDay + 242)
#define ActUnhSvy		(ActChgCrsTT1stDay + 243)
#define ActReqLnkSvy		(ActChgCrsTT1stDay + 244)

#define ActEdiOneSvyQst		(ActChgCrsTT1stDay + 245)
#define ActRcvSvyQst		(ActChgCrsTT1stDay + 246)
#define ActReqRemSvyQst		(ActChgCrsTT1stDay + 247)
#define ActRemSvyQst		(ActChgCrsTT1stDay + 248)

/*****************************************************************************/
/******************************** Files tab **********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAdmDocIns		(ActRemSvyQst +   1)
#define ActAdmShaIns		(ActRemSvyQst +   2)
#define ActSeeAdmDocCtr		(ActRemSvyQst +   3)
#define ActAdmShaCtr		(ActRemSvyQst +   4)
#define ActSeeAdmDocDeg		(ActRemSvyQst +   5)
#define ActAdmShaDeg		(ActRemSvyQst +   6)
#define ActSeeAdmDocCrsGrp	(ActRemSvyQst +   7)
#define ActAdmTchCrsGrp		(ActRemSvyQst +   8)
#define ActAdmShaCrsGrp		(ActRemSvyQst +   9)
#define ActAdmAsgWrkUsr		(ActRemSvyQst +  10)
#define ActReqAsgWrkCrs		(ActRemSvyQst +  11)
#define ActSeeAdmMrk		(ActRemSvyQst +  12)
#define ActAdmBrf		(ActRemSvyQst +  13)
// Secondary actions
#define ActChgToSeeDocIns	(ActRemSvyQst +  14)
#define ActSeeDocIns		(ActRemSvyQst +  15)
#define ActExpSeeDocIns		(ActRemSvyQst +  16)
#define ActConSeeDocIns		(ActRemSvyQst +  17)
#define ActZIPSeeDocIns		(ActRemSvyQst +  18)
#define ActReqDatSeeDocIns	(ActRemSvyQst +  19)
#define ActDowSeeDocIns		(ActRemSvyQst +  20)
#define ActChgToAdmDocIns	(ActRemSvyQst +  21)
#define ActAdmDocIns		(ActRemSvyQst +  22)
#define ActReqRemFilDocIns	(ActRemSvyQst +  23)
#define ActRemFilDocIns		(ActRemSvyQst +  24)
#define ActRemFolDocIns		(ActRemSvyQst +  25)
#define ActCopDocIns		(ActRemSvyQst +  26)
#define ActPasDocIns		(ActRemSvyQst +  27)
#define ActRemTreDocIns		(ActRemSvyQst +  28)
#define ActFrmCreDocIns		(ActRemSvyQst +  29)
#define ActCreFolDocIns		(ActRemSvyQst +  30)
#define ActCreLnkDocIns		(ActRemSvyQst +  31)
#define ActRenFolDocIns		(ActRemSvyQst +  32)
#define ActRcvFilDocInsDZ	(ActRemSvyQst +  33)
#define ActRcvFilDocInsCla	(ActRemSvyQst +  34)
#define ActExpAdmDocIns		(ActRemSvyQst +  35)
#define ActConAdmDocIns		(ActRemSvyQst +  36)
#define ActZIPAdmDocIns		(ActRemSvyQst +  37)
#define ActUnhDocIns		(ActRemSvyQst +  38)
#define ActHidDocIns		(ActRemSvyQst +  39)
#define ActReqDatAdmDocIns	(ActRemSvyQst +  40)
#define ActChgDatAdmDocIns	(ActRemSvyQst +  41)
#define ActDowAdmDocIns		(ActRemSvyQst +  42)

#define ActReqRemFilShaIns	(ActRemSvyQst +  43)
#define ActRemFilShaIns		(ActRemSvyQst +  44)
#define ActRemFolShaIns		(ActRemSvyQst +  45)
#define ActCopShaIns		(ActRemSvyQst +  46)
#define ActPasShaIns		(ActRemSvyQst +  47)
#define ActRemTreShaIns		(ActRemSvyQst +  48)
#define ActFrmCreShaIns		(ActRemSvyQst +  49)
#define ActCreFolShaIns		(ActRemSvyQst +  50)
#define ActCreLnkShaIns		(ActRemSvyQst +  51)
#define ActRenFolShaIns		(ActRemSvyQst +  52)
#define ActRcvFilShaInsDZ	(ActRemSvyQst +  53)
#define ActRcvFilShaInsCla	(ActRemSvyQst +  54)
#define ActExpShaIns		(ActRemSvyQst +  55)
#define ActConShaIns		(ActRemSvyQst +  56)
#define ActZIPShaIns		(ActRemSvyQst +  57)
#define ActReqDatShaIns		(ActRemSvyQst +  58)
#define ActChgDatShaIns		(ActRemSvyQst +  59)
#define ActDowShaIns		(ActRemSvyQst +  60)

#define ActChgToSeeDocCtr	(ActRemSvyQst +  61)
#define ActSeeDocCtr		(ActRemSvyQst +  62)
#define ActExpSeeDocCtr		(ActRemSvyQst +  63)
#define ActConSeeDocCtr		(ActRemSvyQst +  64)
#define ActZIPSeeDocCtr		(ActRemSvyQst +  65)
#define ActReqDatSeeDocCtr	(ActRemSvyQst +  66)
#define ActDowSeeDocCtr		(ActRemSvyQst +  67)
#define ActChgToAdmDocCtr	(ActRemSvyQst +  68)
#define ActAdmDocCtr		(ActRemSvyQst +  69)
#define ActReqRemFilDocCtr	(ActRemSvyQst +  70)
#define ActRemFilDocCtr		(ActRemSvyQst +  71)
#define ActRemFolDocCtr		(ActRemSvyQst +  72)
#define ActCopDocCtr		(ActRemSvyQst +  73)
#define ActPasDocCtr		(ActRemSvyQst +  74)
#define ActRemTreDocCtr		(ActRemSvyQst +  75)
#define ActFrmCreDocCtr		(ActRemSvyQst +  76)
#define ActCreFolDocCtr		(ActRemSvyQst +  77)
#define ActCreLnkDocCtr		(ActRemSvyQst +  78)
#define ActRenFolDocCtr		(ActRemSvyQst +  79)
#define ActRcvFilDocCtrDZ	(ActRemSvyQst +  80)
#define ActRcvFilDocCtrCla	(ActRemSvyQst +  81)
#define ActExpAdmDocCtr		(ActRemSvyQst +  82)
#define ActConAdmDocCtr		(ActRemSvyQst +  83)
#define ActZIPAdmDocCtr		(ActRemSvyQst +  84)
#define ActUnhDocCtr		(ActRemSvyQst +  85)
#define ActHidDocCtr		(ActRemSvyQst +  86)
#define ActReqDatAdmDocCtr	(ActRemSvyQst +  87)
#define ActChgDatAdmDocCtr	(ActRemSvyQst +  88)
#define ActDowAdmDocCtr		(ActRemSvyQst +  89)

#define ActReqRemFilShaCtr	(ActRemSvyQst +  90)
#define ActRemFilShaCtr		(ActRemSvyQst +  91)
#define ActRemFolShaCtr		(ActRemSvyQst +  92)
#define ActCopShaCtr		(ActRemSvyQst +  93)
#define ActPasShaCtr		(ActRemSvyQst +  94)
#define ActRemTreShaCtr		(ActRemSvyQst +  95)
#define ActFrmCreShaCtr		(ActRemSvyQst +  96)
#define ActCreFolShaCtr		(ActRemSvyQst +  97)
#define ActCreLnkShaCtr		(ActRemSvyQst +  98)
#define ActRenFolShaCtr		(ActRemSvyQst +  99)
#define ActRcvFilShaCtrDZ	(ActRemSvyQst + 100)
#define ActRcvFilShaCtrCla	(ActRemSvyQst + 101)
#define ActExpShaCtr		(ActRemSvyQst + 102)
#define ActConShaCtr		(ActRemSvyQst + 103)
#define ActZIPShaCtr		(ActRemSvyQst + 104)
#define ActReqDatShaCtr		(ActRemSvyQst + 105)
#define ActChgDatShaCtr		(ActRemSvyQst + 106)
#define ActDowShaCtr		(ActRemSvyQst + 107)

#define ActChgToSeeDocDeg	(ActRemSvyQst + 108)
#define ActSeeDocDeg		(ActRemSvyQst + 109)
#define ActExpSeeDocDeg		(ActRemSvyQst + 110)
#define ActConSeeDocDeg		(ActRemSvyQst + 111)
#define ActZIPSeeDocDeg		(ActRemSvyQst + 112)
#define ActReqDatSeeDocDeg	(ActRemSvyQst + 113)
#define ActDowSeeDocDeg		(ActRemSvyQst + 114)
#define ActChgToAdmDocDeg	(ActRemSvyQst + 115)
#define ActAdmDocDeg		(ActRemSvyQst + 116)
#define ActReqRemFilDocDeg	(ActRemSvyQst + 117)
#define ActRemFilDocDeg		(ActRemSvyQst + 118)
#define ActRemFolDocDeg		(ActRemSvyQst + 119)
#define ActCopDocDeg		(ActRemSvyQst + 120)
#define ActPasDocDeg		(ActRemSvyQst + 121)
#define ActRemTreDocDeg		(ActRemSvyQst + 122)
#define ActFrmCreDocDeg		(ActRemSvyQst + 123)
#define ActCreFolDocDeg		(ActRemSvyQst + 124)
#define ActCreLnkDocDeg		(ActRemSvyQst + 125)
#define ActRenFolDocDeg		(ActRemSvyQst + 126)
#define ActRcvFilDocDegDZ	(ActRemSvyQst + 127)
#define ActRcvFilDocDegCla	(ActRemSvyQst + 128)
#define ActExpAdmDocDeg		(ActRemSvyQst + 129)
#define ActConAdmDocDeg		(ActRemSvyQst + 130)
#define ActZIPAdmDocDeg		(ActRemSvyQst + 131)
#define ActUnhDocDeg		(ActRemSvyQst + 132)
#define ActHidDocDeg		(ActRemSvyQst + 133)
#define ActReqDatAdmDocDeg	(ActRemSvyQst + 134)
#define ActChgDatAdmDocDeg	(ActRemSvyQst + 135)
#define ActDowAdmDocDeg		(ActRemSvyQst + 136)

#define ActReqRemFilShaDeg	(ActRemSvyQst + 137)
#define ActRemFilShaDeg		(ActRemSvyQst + 138)
#define ActRemFolShaDeg		(ActRemSvyQst + 139)
#define ActCopShaDeg		(ActRemSvyQst + 140)
#define ActPasShaDeg		(ActRemSvyQst + 141)
#define ActRemTreShaDeg		(ActRemSvyQst + 142)
#define ActFrmCreShaDeg		(ActRemSvyQst + 143)
#define ActCreFolShaDeg		(ActRemSvyQst + 144)
#define ActCreLnkShaDeg		(ActRemSvyQst + 145)
#define ActRenFolShaDeg		(ActRemSvyQst + 146)
#define ActRcvFilShaDegDZ	(ActRemSvyQst + 147)
#define ActRcvFilShaDegCla	(ActRemSvyQst + 148)
#define ActExpShaDeg		(ActRemSvyQst + 149)
#define ActConShaDeg		(ActRemSvyQst + 150)
#define ActZIPShaDeg		(ActRemSvyQst + 151)
#define ActReqDatShaDeg		(ActRemSvyQst + 152)
#define ActChgDatShaDeg		(ActRemSvyQst + 153)
#define ActDowShaDeg		(ActRemSvyQst + 154)

#define ActChgToSeeDocCrs	(ActRemSvyQst + 155)
#define ActSeeDocCrs		(ActRemSvyQst + 156)
#define ActExpSeeDocCrs		(ActRemSvyQst + 157)
#define ActConSeeDocCrs		(ActRemSvyQst + 158)
#define ActZIPSeeDocCrs		(ActRemSvyQst + 159)
#define ActReqDatSeeDocCrs	(ActRemSvyQst + 160)
#define ActReqLnkSeeDocCrs	(ActRemSvyQst + 161)
#define ActDowSeeDocCrs		(ActRemSvyQst + 162)

#define ActSeeDocGrp		(ActRemSvyQst + 163)
#define ActExpSeeDocGrp		(ActRemSvyQst + 164)
#define ActConSeeDocGrp		(ActRemSvyQst + 165)
#define ActZIPSeeDocGrp		(ActRemSvyQst + 166)
#define ActReqDatSeeDocGrp	(ActRemSvyQst + 167)
#define ActDowSeeDocGrp		(ActRemSvyQst + 168)

#define ActChgToAdmDocCrs	(ActRemSvyQst + 169)
#define ActAdmDocCrs		(ActRemSvyQst + 170)
#define ActReqRemFilDocCrs	(ActRemSvyQst + 171)
#define ActRemFilDocCrs		(ActRemSvyQst + 172)
#define ActRemFolDocCrs		(ActRemSvyQst + 173)
#define ActCopDocCrs		(ActRemSvyQst + 174)
#define ActPasDocCrs		(ActRemSvyQst + 175)
#define ActRemTreDocCrs		(ActRemSvyQst + 176)
#define ActFrmCreDocCrs		(ActRemSvyQst + 177)
#define ActCreFolDocCrs		(ActRemSvyQst + 178)
#define ActCreLnkDocCrs		(ActRemSvyQst + 179)
#define ActRenFolDocCrs		(ActRemSvyQst + 180)
#define ActRcvFilDocCrsDZ	(ActRemSvyQst + 181)
#define ActRcvFilDocCrsCla	(ActRemSvyQst + 182)
#define ActExpAdmDocCrs		(ActRemSvyQst + 183)
#define ActConAdmDocCrs		(ActRemSvyQst + 184)
#define ActZIPAdmDocCrs		(ActRemSvyQst + 185)
#define ActUnhDocCrs		(ActRemSvyQst + 186)
#define ActHidDocCrs		(ActRemSvyQst + 187)
#define ActReqDatAdmDocCrs	(ActRemSvyQst + 188)
#define ActChgDatAdmDocCrs	(ActRemSvyQst + 189)
#define ActReqLnkAdmDocCrs	(ActRemSvyQst + 190)
#define ActDowAdmDocCrs		(ActRemSvyQst + 191)

#define ActAdmDocGrp		(ActRemSvyQst + 192)
#define ActReqRemFilDocGrp	(ActRemSvyQst + 193)
#define ActRemFilDocGrp		(ActRemSvyQst + 194)
#define ActRemFolDocGrp		(ActRemSvyQst + 195)
#define ActCopDocGrp		(ActRemSvyQst + 196)
#define ActPasDocGrp		(ActRemSvyQst + 197)
#define ActRemTreDocGrp		(ActRemSvyQst + 198)
#define ActFrmCreDocGrp		(ActRemSvyQst + 199)
#define ActCreFolDocGrp		(ActRemSvyQst + 200)
#define ActCreLnkDocGrp		(ActRemSvyQst + 201)
#define ActRenFolDocGrp		(ActRemSvyQst + 202)
#define ActRcvFilDocGrpDZ	(ActRemSvyQst + 203)
#define ActRcvFilDocGrpCla	(ActRemSvyQst + 204)
#define ActExpAdmDocGrp		(ActRemSvyQst + 205)
#define ActConAdmDocGrp		(ActRemSvyQst + 206)
#define ActZIPAdmDocGrp		(ActRemSvyQst + 207)
#define ActUnhDocGrp		(ActRemSvyQst + 208)
#define ActHidDocGrp		(ActRemSvyQst + 209)
#define ActReqDatAdmDocGrp	(ActRemSvyQst + 210)
#define ActChgDatAdmDocGrp	(ActRemSvyQst + 211)
#define ActDowAdmDocGrp		(ActRemSvyQst + 212)

#define ActChgToAdmTch		(ActRemSvyQst + 213)

#define ActAdmTchCrs		(ActRemSvyQst + 214)
#define ActReqRemFilTchCrs	(ActRemSvyQst + 215)
#define ActRemFilTchCrs		(ActRemSvyQst + 216)
#define ActRemFolTchCrs		(ActRemSvyQst + 217)
#define ActCopTchCrs		(ActRemSvyQst + 218)
#define ActPasTchCrs		(ActRemSvyQst + 219)
#define ActRemTreTchCrs		(ActRemSvyQst + 220)
#define ActFrmCreTchCrs		(ActRemSvyQst + 221)
#define ActCreFolTchCrs		(ActRemSvyQst + 222)
#define ActCreLnkTchCrs		(ActRemSvyQst + 223)
#define ActRenFolTchCrs		(ActRemSvyQst + 224)
#define ActRcvFilTchCrsDZ	(ActRemSvyQst + 225)
#define ActRcvFilTchCrsCla	(ActRemSvyQst + 226)
#define ActExpTchCrs		(ActRemSvyQst + 227)
#define ActConTchCrs		(ActRemSvyQst + 228)
#define ActZIPTchCrs		(ActRemSvyQst + 229)
#define ActReqDatTchCrs		(ActRemSvyQst + 230)
#define ActChgDatTchCrs		(ActRemSvyQst + 231)
#define ActDowTchCrs		(ActRemSvyQst + 232)

#define ActAdmTchGrp		(ActRemSvyQst + 233)
#define ActReqRemFilTchGrp	(ActRemSvyQst + 234)
#define ActRemFilTchGrp		(ActRemSvyQst + 235)
#define ActRemFolTchGrp		(ActRemSvyQst + 236)
#define ActCopTchGrp		(ActRemSvyQst + 237)
#define ActPasTchGrp		(ActRemSvyQst + 238)
#define ActRemTreTchGrp		(ActRemSvyQst + 239)
#define ActFrmCreTchGrp		(ActRemSvyQst + 240)
#define ActCreFolTchGrp		(ActRemSvyQst + 241)
#define ActCreLnkTchGrp		(ActRemSvyQst + 242)
#define ActRenFolTchGrp		(ActRemSvyQst + 243)
#define ActRcvFilTchGrpDZ	(ActRemSvyQst + 244)
#define ActRcvFilTchGrpCla	(ActRemSvyQst + 245)
#define ActExpTchGrp		(ActRemSvyQst + 246)
#define ActConTchGrp		(ActRemSvyQst + 247)
#define ActZIPTchGrp		(ActRemSvyQst + 248)
#define ActReqDatTchGrp		(ActRemSvyQst + 249)
#define ActChgDatTchGrp		(ActRemSvyQst + 250)
#define ActDowTchGrp		(ActRemSvyQst + 251)

#define ActChgToAdmSha		(ActRemSvyQst + 252)

#define ActAdmShaCrs		(ActRemSvyQst + 253)
#define ActReqRemFilShaCrs	(ActRemSvyQst + 254)
#define ActRemFilShaCrs		(ActRemSvyQst + 255)
#define ActRemFolShaCrs		(ActRemSvyQst + 256)
#define ActCopShaCrs		(ActRemSvyQst + 257)
#define ActPasShaCrs		(ActRemSvyQst + 258)
#define ActRemTreShaCrs		(ActRemSvyQst + 259)
#define ActFrmCreShaCrs		(ActRemSvyQst + 260)
#define ActCreFolShaCrs		(ActRemSvyQst + 261)
#define ActCreLnkShaCrs		(ActRemSvyQst + 262)
#define ActRenFolShaCrs		(ActRemSvyQst + 263)
#define ActRcvFilShaCrsDZ	(ActRemSvyQst + 264)
#define ActRcvFilShaCrsCla	(ActRemSvyQst + 265)
#define ActExpShaCrs		(ActRemSvyQst + 266)
#define ActConShaCrs		(ActRemSvyQst + 267)
#define ActZIPShaCrs		(ActRemSvyQst + 268)
#define ActReqDatShaCrs		(ActRemSvyQst + 269)
#define ActChgDatShaCrs		(ActRemSvyQst + 270)
#define ActDowShaCrs		(ActRemSvyQst + 271)

#define ActAdmShaGrp		(ActRemSvyQst + 272)
#define ActReqRemFilShaGrp	(ActRemSvyQst + 273)
#define ActRemFilShaGrp		(ActRemSvyQst + 274)
#define ActRemFolShaGrp		(ActRemSvyQst + 275)
#define ActCopShaGrp		(ActRemSvyQst + 276)
#define ActPasShaGrp		(ActRemSvyQst + 277)
#define ActRemTreShaGrp		(ActRemSvyQst + 278)
#define ActFrmCreShaGrp		(ActRemSvyQst + 279)
#define ActCreFolShaGrp		(ActRemSvyQst + 280)
#define ActCreLnkShaGrp		(ActRemSvyQst + 281)
#define ActRenFolShaGrp		(ActRemSvyQst + 282)
#define ActRcvFilShaGrpDZ	(ActRemSvyQst + 283)
#define ActRcvFilShaGrpCla	(ActRemSvyQst + 284)
#define ActExpShaGrp		(ActRemSvyQst + 285)
#define ActConShaGrp		(ActRemSvyQst + 286)
#define ActZIPShaGrp		(ActRemSvyQst + 287)
#define ActReqDatShaGrp		(ActRemSvyQst + 288)
#define ActChgDatShaGrp		(ActRemSvyQst + 289)
#define ActDowShaGrp		(ActRemSvyQst + 290)

#define ActAdmAsgWrkCrs		(ActRemSvyQst + 291)

#define ActReqRemFilAsgUsr	(ActRemSvyQst + 292)
#define ActRemFilAsgUsr		(ActRemSvyQst + 293)
#define ActRemFolAsgUsr		(ActRemSvyQst + 294)
#define ActCopAsgUsr		(ActRemSvyQst + 295)
#define ActPasAsgUsr		(ActRemSvyQst + 296)
#define ActRemTreAsgUsr		(ActRemSvyQst + 297)
#define ActFrmCreAsgUsr		(ActRemSvyQst + 298)
#define ActCreFolAsgUsr		(ActRemSvyQst + 299)
#define ActCreLnkAsgUsr		(ActRemSvyQst + 300)
#define ActRenFolAsgUsr		(ActRemSvyQst + 301)
#define ActRcvFilAsgUsrDZ	(ActRemSvyQst + 302)
#define ActRcvFilAsgUsrCla	(ActRemSvyQst + 303)
#define ActExpAsgUsr		(ActRemSvyQst + 304)
#define ActConAsgUsr		(ActRemSvyQst + 305)
#define ActZIPAsgUsr		(ActRemSvyQst + 306)
#define ActReqDatAsgUsr		(ActRemSvyQst + 307)
#define ActChgDatAsgUsr		(ActRemSvyQst + 308)
#define ActDowAsgUsr		(ActRemSvyQst + 309)

#define ActReqRemFilWrkUsr	(ActRemSvyQst + 310)
#define ActRemFilWrkUsr		(ActRemSvyQst + 311)
#define ActRemFolWrkUsr		(ActRemSvyQst + 312)
#define ActCopWrkUsr		(ActRemSvyQst + 313)
#define ActPasWrkUsr		(ActRemSvyQst + 314)
#define ActRemTreWrkUsr		(ActRemSvyQst + 315)
#define ActFrmCreWrkUsr		(ActRemSvyQst + 316)
#define ActCreFolWrkUsr		(ActRemSvyQst + 317)
#define ActCreLnkWrkUsr		(ActRemSvyQst + 318)
#define ActRenFolWrkUsr		(ActRemSvyQst + 319)
#define ActRcvFilWrkUsrDZ	(ActRemSvyQst + 320)
#define ActRcvFilWrkUsrCla	(ActRemSvyQst + 321)
#define ActExpWrkUsr		(ActRemSvyQst + 322)
#define ActConWrkUsr		(ActRemSvyQst + 323)
#define ActZIPWrkUsr		(ActRemSvyQst + 324)
#define ActReqDatWrkUsr		(ActRemSvyQst + 325)
#define ActChgDatWrkUsr		(ActRemSvyQst + 326)
#define ActDowWrkUsr		(ActRemSvyQst + 327)

#define ActReqRemFilAsgCrs	(ActRemSvyQst + 328)
#define ActRemFilAsgCrs		(ActRemSvyQst + 329)
#define ActRemFolAsgCrs		(ActRemSvyQst + 330)
#define ActCopAsgCrs		(ActRemSvyQst + 331)
#define ActPasAsgCrs		(ActRemSvyQst + 332)
#define ActRemTreAsgCrs		(ActRemSvyQst + 333)
#define ActFrmCreAsgCrs		(ActRemSvyQst + 334)
#define ActCreFolAsgCrs		(ActRemSvyQst + 335)
#define ActCreLnkAsgCrs		(ActRemSvyQst + 336)
#define ActRenFolAsgCrs		(ActRemSvyQst + 337)
#define ActRcvFilAsgCrsDZ	(ActRemSvyQst + 338)
#define ActRcvFilAsgCrsCla	(ActRemSvyQst + 339)
#define ActExpAsgCrs		(ActRemSvyQst + 340)
#define ActConAsgCrs		(ActRemSvyQst + 341)
#define ActZIPAsgCrs		(ActRemSvyQst + 342)
#define ActReqDatAsgCrs		(ActRemSvyQst + 343)
#define ActChgDatAsgCrs		(ActRemSvyQst + 344)
#define ActDowAsgCrs		(ActRemSvyQst + 345)

#define ActReqRemFilWrkCrs	(ActRemSvyQst + 346)
#define ActRemFilWrkCrs		(ActRemSvyQst + 347)
#define ActRemFolWrkCrs		(ActRemSvyQst + 348)
#define ActCopWrkCrs		(ActRemSvyQst + 349)
#define ActPasWrkCrs		(ActRemSvyQst + 350)
#define ActRemTreWrkCrs		(ActRemSvyQst + 351)
#define ActFrmCreWrkCrs		(ActRemSvyQst + 352)
#define ActCreFolWrkCrs		(ActRemSvyQst + 353)
#define ActCreLnkWrkCrs		(ActRemSvyQst + 354)
#define ActRenFolWrkCrs		(ActRemSvyQst + 355)
#define ActRcvFilWrkCrsDZ	(ActRemSvyQst + 356)
#define ActRcvFilWrkCrsCla	(ActRemSvyQst + 357)
#define ActExpWrkCrs		(ActRemSvyQst + 358)
#define ActConWrkCrs		(ActRemSvyQst + 359)
#define ActZIPWrkCrs		(ActRemSvyQst + 360)
#define ActReqDatWrkCrs		(ActRemSvyQst + 361)
#define ActChgDatWrkCrs		(ActRemSvyQst + 362)
#define ActDowWrkCrs		(ActRemSvyQst + 363)

#define ActChgToSeeMrk		(ActRemSvyQst + 364)

#define ActSeeMrkCrs		(ActRemSvyQst + 365)
#define ActExpSeeMrkCrs		(ActRemSvyQst + 366)
#define ActConSeeMrkCrs		(ActRemSvyQst + 367)
#define ActReqDatSeeMrkCrs	(ActRemSvyQst + 368)
#define ActReqLnkSeeMrkCrs	(ActRemSvyQst + 369)
#define ActSeeMyMrkCrs		(ActRemSvyQst + 370)

#define ActSeeMrkGrp		(ActRemSvyQst + 371)
#define ActExpSeeMrkGrp		(ActRemSvyQst + 372)
#define ActConSeeMrkGrp		(ActRemSvyQst + 373)
#define ActReqDatSeeMrkGrp	(ActRemSvyQst + 374)
#define ActSeeMyMrkGrp		(ActRemSvyQst + 375)

#define ActChgToAdmMrk		(ActRemSvyQst + 376)

#define ActAdmMrkCrs		(ActRemSvyQst + 377)
#define ActReqRemFilMrkCrs	(ActRemSvyQst + 378)
#define ActRemFilMrkCrs		(ActRemSvyQst + 379)
#define ActRemFolMrkCrs		(ActRemSvyQst + 380)
#define ActCopMrkCrs		(ActRemSvyQst + 381)
#define ActPasMrkCrs		(ActRemSvyQst + 382)
#define ActRemTreMrkCrs		(ActRemSvyQst + 383)
#define ActFrmCreMrkCrs		(ActRemSvyQst + 384)
#define ActCreFolMrkCrs		(ActRemSvyQst + 385)
#define ActRenFolMrkCrs		(ActRemSvyQst + 386)
#define ActRcvFilMrkCrsDZ	(ActRemSvyQst + 387)
#define ActRcvFilMrkCrsCla	(ActRemSvyQst + 388)
#define ActExpAdmMrkCrs		(ActRemSvyQst + 389)
#define ActConAdmMrkCrs		(ActRemSvyQst + 390)
#define ActZIPAdmMrkCrs		(ActRemSvyQst + 391)
#define ActUnhMrkCrs		(ActRemSvyQst + 392)
#define ActHidMrkCrs		(ActRemSvyQst + 393)
#define ActReqDatAdmMrkCrs	(ActRemSvyQst + 394)
#define ActChgDatAdmMrkCrs	(ActRemSvyQst + 395)
#define ActReqLnkAdmMrkCrs	(ActRemSvyQst + 396)
#define ActDowAdmMrkCrs		(ActRemSvyQst + 397)
#define ActChgNumRowHeaCrs	(ActRemSvyQst + 398)
#define ActChgNumRowFooCrs	(ActRemSvyQst + 399)

#define ActAdmMrkGrp		(ActRemSvyQst + 400)
#define ActReqRemFilMrkGrp	(ActRemSvyQst + 401)
#define ActRemFilMrkGrp		(ActRemSvyQst + 402)
#define ActRemFolMrkGrp		(ActRemSvyQst + 403)
#define ActCopMrkGrp		(ActRemSvyQst + 404)
#define ActPasMrkGrp		(ActRemSvyQst + 405)
#define ActRemTreMrkGrp		(ActRemSvyQst + 406)
#define ActFrmCreMrkGrp		(ActRemSvyQst + 407)
#define ActCreFolMrkGrp		(ActRemSvyQst + 408)
#define ActRenFolMrkGrp		(ActRemSvyQst + 409)
#define ActRcvFilMrkGrpDZ	(ActRemSvyQst + 410)
#define ActRcvFilMrkGrpCla	(ActRemSvyQst + 411)
#define ActExpAdmMrkGrp		(ActRemSvyQst + 412)
#define ActConAdmMrkGrp		(ActRemSvyQst + 413)
#define ActZIPAdmMrkGrp		(ActRemSvyQst + 414)
#define ActUnhMrkGrp		(ActRemSvyQst + 415)
#define ActHidMrkGrp		(ActRemSvyQst + 416)
#define ActReqDatAdmMrkGrp	(ActRemSvyQst + 417)
#define ActChgDatAdmMrkGrp	(ActRemSvyQst + 418)
#define ActDowAdmMrkGrp		(ActRemSvyQst + 419)
#define ActChgNumRowHeaGrp	(ActRemSvyQst + 420)
#define ActChgNumRowFooGrp	(ActRemSvyQst + 421)

#define ActReqRemFilBrf		(ActRemSvyQst + 422)
#define ActRemFilBrf		(ActRemSvyQst + 423)
#define ActRemFolBrf		(ActRemSvyQst + 424)
#define ActCopBrf		(ActRemSvyQst + 425)
#define ActPasBrf		(ActRemSvyQst + 426)
#define ActRemTreBrf		(ActRemSvyQst + 427)
#define ActFrmCreBrf		(ActRemSvyQst + 428)
#define ActCreFolBrf		(ActRemSvyQst + 429)
#define ActCreLnkBrf		(ActRemSvyQst + 430)
#define ActRenFolBrf		(ActRemSvyQst + 431)
#define ActRcvFilBrfDZ		(ActRemSvyQst + 432)
#define ActRcvFilBrfCla		(ActRemSvyQst + 433)
#define ActExpBrf		(ActRemSvyQst + 434)
#define ActConBrf		(ActRemSvyQst + 435)
#define ActZIPBrf		(ActRemSvyQst + 436)
#define ActReqDatBrf		(ActRemSvyQst + 437)
#define ActChgDatBrf		(ActRemSvyQst + 438)
#define ActDowBrf		(ActRemSvyQst + 439)
#define ActReqRemOldBrf		(ActRemSvyQst + 440)
#define ActRemOldBrf		(ActRemSvyQst + 441)

/*****************************************************************************/
/******************************* Users tab ***********************************/
/*****************************************************************************/
// Actions in menu
#define ActReqSelGrp		(ActRemOldBrf +   1)
#define ActLstStd		(ActRemOldBrf +   2)
#define ActLstTch		(ActRemOldBrf +   3)
#define ActLstOth		(ActRemOldBrf +   4)
#define ActSeeAtt		(ActRemOldBrf +   5)
#define ActReqSignUp		(ActRemOldBrf +   6)
#define ActSeeSignUpReq		(ActRemOldBrf +   7)
#define ActLstCon		(ActRemOldBrf +   8)

// Secondary actions
#define ActChgGrp		(ActRemOldBrf +   9)
#define ActReqEdiGrp		(ActRemOldBrf +  10)
#define ActNewGrpTyp		(ActRemOldBrf +  11)
#define ActReqRemGrpTyp		(ActRemOldBrf +  12)
#define ActRemGrpTyp		(ActRemOldBrf +  13)
#define ActRenGrpTyp		(ActRemOldBrf +  14)
#define ActChgMdtGrpTyp		(ActRemOldBrf +  15)
#define ActChgMulGrpTyp		(ActRemOldBrf +  16)
#define ActChgTimGrpTyp		(ActRemOldBrf +  17)
#define ActNewGrp		(ActRemOldBrf +  18)
#define ActReqRemGrp		(ActRemOldBrf +  19)
#define ActRemGrp		(ActRemOldBrf +  20)
#define ActOpeGrp		(ActRemOldBrf +  21)
#define ActCloGrp		(ActRemOldBrf +  22)
#define ActEnaFilZonGrp		(ActRemOldBrf +  23)
#define ActDisFilZonGrp		(ActRemOldBrf +  24)
#define ActChgGrpTyp		(ActRemOldBrf +  25)
#define ActRenGrp		(ActRemOldBrf +  26)
#define ActChgGrpRoo		(ActRemOldBrf +  27)
#define ActChgMaxStdGrp		(ActRemOldBrf +  28)

#define ActLstGst		(ActRemOldBrf +  29)

#define ActPrnGstPho		(ActRemOldBrf +  30)
#define ActPrnStdPho		(ActRemOldBrf +  31)
#define ActPrnTchPho		(ActRemOldBrf +  32)
#define ActLstGstAll		(ActRemOldBrf +  33)
#define ActLstStdAll		(ActRemOldBrf +  34)
#define ActLstTchAll		(ActRemOldBrf +  35)

#define ActSeeRecOneStd		(ActRemOldBrf +  36)
#define ActSeeRecOneTch		(ActRemOldBrf +  37)
#define ActDoActOnSevGst	(ActRemOldBrf +  38)
#define ActDoActOnSevStd	(ActRemOldBrf +  39)
#define ActDoActOnSevTch	(ActRemOldBrf +  40)
#define ActSeeRecSevGst		(ActRemOldBrf +  41)
#define ActSeeRecSevStd		(ActRemOldBrf +  42)
#define ActSeeRecSevTch		(ActRemOldBrf +  43)
#define ActPrnRecSevGst		(ActRemOldBrf +  44)
#define ActPrnRecSevStd		(ActRemOldBrf +  45)
#define ActPrnRecSevTch		(ActRemOldBrf +  46)
#define ActRcvRecOthUsr		(ActRemOldBrf +  47)
#define ActEdiRecFie		(ActRemOldBrf +  48)
#define ActNewFie		(ActRemOldBrf +  49)
#define ActReqRemFie		(ActRemOldBrf +  50)
#define ActRemFie		(ActRemOldBrf +  51)
#define ActRenFie		(ActRemOldBrf +  52)
#define ActChgRowFie		(ActRemOldBrf +  53)
#define ActChgVisFie		(ActRemOldBrf +  54)
#define ActRcvRecCrs		(ActRemOldBrf +  55)

#define ActFrmLogInUsrAgd	(ActRemOldBrf +  56)
#define ActLogInUsrAgd		(ActRemOldBrf +  57)
#define ActLogInUsrAgdLan	(ActRemOldBrf +  58)
#define ActSeeUsrAgd		(ActRemOldBrf +  59)

#define ActReqEnrSevStd		(ActRemOldBrf +  60)
#define ActReqEnrSevNET		(ActRemOldBrf +  61)
#define ActReqEnrSevTch		(ActRemOldBrf +  62)

#define ActReqLstUsrAtt		(ActRemOldBrf +  63)
#define ActSeeLstMyAtt		(ActRemOldBrf +  64)
#define ActPrnLstMyAtt		(ActRemOldBrf +  65)
#define ActSeeLstUsrAtt		(ActRemOldBrf +  66)
#define ActPrnLstUsrAtt		(ActRemOldBrf +  67)
#define ActFrmNewAtt		(ActRemOldBrf +  68)
#define ActEdiOneAtt		(ActRemOldBrf +  69)
#define ActNewAtt		(ActRemOldBrf +  70)
#define ActChgAtt		(ActRemOldBrf +  71)
#define ActReqRemAtt		(ActRemOldBrf +  72)
#define ActRemAtt		(ActRemOldBrf +  73)
#define ActHidAtt		(ActRemOldBrf +  74)
#define ActUnhAtt		(ActRemOldBrf +  75)
#define ActSeeOneAtt		(ActRemOldBrf +  76)
#define ActReqLnkAtt		(ActRemOldBrf +  77)
#define ActRecAttStd		(ActRemOldBrf +  78)
#define ActRecAttMe		(ActRemOldBrf +  79)

#define ActSignUp		(ActRemOldBrf +  80)
#define ActUpdSignUpReq		(ActRemOldBrf +  81)
#define ActReqRejSignUp		(ActRemOldBrf +  82)
#define ActRejSignUp		(ActRemOldBrf +  83)

#define ActReqMdfOneOth		(ActRemOldBrf +  84)
#define ActReqMdfOneStd		(ActRemOldBrf +  85)
#define ActReqMdfOneTch		(ActRemOldBrf +  86)

#define ActReqMdfOth		(ActRemOldBrf +  87)
#define ActReqMdfStd		(ActRemOldBrf +  88)
#define ActReqMdfNET		(ActRemOldBrf +  89)
#define ActReqMdfTch		(ActRemOldBrf +  90)

#define ActReqOthPho		(ActRemOldBrf +  91)
#define ActReqStdPho		(ActRemOldBrf +  92)
#define ActReqTchPho		(ActRemOldBrf +  93)
#define ActDetOthPho		(ActRemOldBrf +  94)
#define ActDetStdPho		(ActRemOldBrf +  95)
#define ActDetTchPho		(ActRemOldBrf +  96)
#define ActUpdOthPho		(ActRemOldBrf +  97)
#define ActUpdStdPho		(ActRemOldBrf +  98)
#define ActUpdTchPho		(ActRemOldBrf +  99)
#define ActReqRemOthPho		(ActRemOldBrf + 100)
#define ActReqRemStdPho		(ActRemOldBrf + 101)
#define ActReqRemTchPho		(ActRemOldBrf + 102)
#define ActRemOthPho		(ActRemOldBrf + 103)
#define ActRemStdPho		(ActRemOldBrf + 104)
#define ActRemTchPho		(ActRemOldBrf + 105)
#define ActCreOth		(ActRemOldBrf + 106)
#define ActCreStd		(ActRemOldBrf + 107)
#define ActCreNET		(ActRemOldBrf + 108)
#define ActCreTch		(ActRemOldBrf + 109)
#define ActUpdOth		(ActRemOldBrf + 110)
#define ActUpdStd		(ActRemOldBrf + 111)
#define ActUpdNET		(ActRemOldBrf + 112)
#define ActUpdTch		(ActRemOldBrf + 113)

#define ActReqAccEnrStd		(ActRemOldBrf + 114)
#define ActReqAccEnrNET		(ActRemOldBrf + 115)
#define ActReqAccEnrTch		(ActRemOldBrf + 116)
#define ActAccEnrStd		(ActRemOldBrf + 117)
#define ActAccEnrNET		(ActRemOldBrf + 118)
#define ActAccEnrTch		(ActRemOldBrf + 119)
#define ActRemMe_Std		(ActRemOldBrf + 120)
#define ActRemMe_NET		(ActRemOldBrf + 121)
#define ActRemMe_Tch		(ActRemOldBrf + 122)

#define ActNewAdmIns		(ActRemOldBrf + 123)
#define ActRemAdmIns		(ActRemOldBrf + 124)
#define ActNewAdmCtr		(ActRemOldBrf + 125)
#define ActRemAdmCtr		(ActRemOldBrf + 126)
#define ActNewAdmDeg		(ActRemOldBrf + 127)
#define ActRemAdmDeg		(ActRemOldBrf + 128)

#define ActRcvFrmEnrSevStd	(ActRemOldBrf + 129)
#define ActRcvFrmEnrSevNET	(ActRemOldBrf + 130)
#define ActRcvFrmEnrSevTch	(ActRemOldBrf + 131)

#define ActCnfID_Oth		(ActRemOldBrf + 132)
#define ActCnfID_Std		(ActRemOldBrf + 133)
#define ActCnfID_Tch		(ActRemOldBrf + 134)

#define ActFrmAccOth		(ActRemOldBrf + 135)
#define ActFrmAccStd		(ActRemOldBrf + 136)
#define ActFrmAccTch		(ActRemOldBrf + 137)

#define ActRemOldNicOth		(ActRemOldBrf + 138)
#define ActRemOldNicStd		(ActRemOldBrf + 139)
#define ActRemOldNicTch		(ActRemOldBrf + 140)
#define ActChgNicOth		(ActRemOldBrf + 141)
#define ActChgNicStd		(ActRemOldBrf + 142)
#define ActChgNicTch		(ActRemOldBrf + 143)

#define ActRemID_Oth		(ActRemOldBrf + 144)
#define ActRemID_Std		(ActRemOldBrf + 145)
#define ActRemID_Tch		(ActRemOldBrf + 146)
#define ActNewID_Oth		(ActRemOldBrf + 147)
#define ActNewID_Std		(ActRemOldBrf + 148)
#define ActNewID_Tch		(ActRemOldBrf + 149)
#define ActChgPwdOth		(ActRemOldBrf + 150)
#define ActChgPwdStd		(ActRemOldBrf + 151)
#define ActChgPwdTch		(ActRemOldBrf + 152)
#define ActRemMaiOth		(ActRemOldBrf + 153)
#define ActRemMaiStd		(ActRemOldBrf + 154)
#define ActRemMaiTch		(ActRemOldBrf + 155)
#define ActNewMaiOth		(ActRemOldBrf + 156)
#define ActNewMaiStd		(ActRemOldBrf + 157)
#define ActNewMaiTch		(ActRemOldBrf + 158)

#define ActRemStdCrs		(ActRemOldBrf + 159)
#define ActRemNETCrs		(ActRemOldBrf + 160)
#define ActRemTchCrs		(ActRemOldBrf + 161)
#define ActRemUsrGbl		(ActRemOldBrf + 162)

#define ActReqRemAllStdCrs	(ActRemOldBrf + 163)
#define ActRemAllStdCrs		(ActRemOldBrf + 164)

#define ActReqRemOldUsr		(ActRemOldBrf + 165)
#define ActRemOldUsr		(ActRemOldBrf + 166)

#define ActLstDupUsr		(ActRemOldBrf + 167)
#define ActLstSimUsr		(ActRemOldBrf + 168)
#define ActRemDupUsr		(ActRemOldBrf + 169)

#define ActReqFolSevStd		(ActRemOldBrf + 170)
#define ActReqFolSevTch		(ActRemOldBrf + 171)
#define ActReqUnfSevStd		(ActRemOldBrf + 172)
#define ActReqUnfSevTch		(ActRemOldBrf + 173)
#define ActFolSevStd		(ActRemOldBrf + 174)
#define ActFolSevTch		(ActRemOldBrf + 175)
#define ActUnfSevStd		(ActRemOldBrf + 176)
#define ActUnfSevTch		(ActRemOldBrf + 177)

/*****************************************************************************/
/******************************* Messages tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActSeeAnn		(ActUnfSevTch +   1)
#define ActSeeAllNot		(ActUnfSevTch +   2)
#define ActSeeFor		(ActUnfSevTch +   3)
#define ActSeeChtRms		(ActUnfSevTch +   4)
#define ActSeeRcvMsg		(ActUnfSevTch +   5)
#define ActReqMaiUsr		(ActUnfSevTch +   6)
// Secondary actions
#define ActWriAnn		(ActUnfSevTch +   7)
#define ActRcvAnn		(ActUnfSevTch +   8)
#define ActHidAnn		(ActUnfSevTch +   9)
#define ActUnhAnn		(ActUnfSevTch +  10)
#define ActRemAnn		(ActUnfSevTch +  11)
#define ActSeeOneNot		(ActUnfSevTch +  12)
#define ActWriNot		(ActUnfSevTch +  13)
#define ActRcvNot		(ActUnfSevTch +  14)
#define ActHidNot		(ActUnfSevTch +  15)
#define ActUnhNot		(ActUnfSevTch +  16)
#define ActReqRemNot		(ActUnfSevTch +  17)
#define ActRemNot		(ActUnfSevTch +  18)

#define ActSeeForCrsUsr		(ActUnfSevTch +  19)
#define ActSeeForCrsTch		(ActUnfSevTch +  20)
#define ActSeeForDegUsr		(ActUnfSevTch +  21)
#define ActSeeForDegTch		(ActUnfSevTch +  22)
#define ActSeeForCtrUsr		(ActUnfSevTch +  23)
#define ActSeeForCtrTch		(ActUnfSevTch +  24)
#define ActSeeForInsUsr		(ActUnfSevTch +  25)
#define ActSeeForInsTch		(ActUnfSevTch +  26)
#define ActSeeForGenUsr		(ActUnfSevTch +  27)
#define ActSeeForGenTch		(ActUnfSevTch +  28)
#define ActSeeForSWAUsr		(ActUnfSevTch +  29)
#define ActSeeForSWATch		(ActUnfSevTch +  30)
#define ActSeePstForCrsUsr	(ActUnfSevTch +  31)
#define ActSeePstForCrsTch	(ActUnfSevTch +  32)
#define ActSeePstForDegUsr	(ActUnfSevTch +  33)
#define ActSeePstForDegTch	(ActUnfSevTch +  34)
#define ActSeePstForCtrUsr	(ActUnfSevTch +  35)
#define ActSeePstForCtrTch	(ActUnfSevTch +  36)
#define ActSeePstForInsUsr	(ActUnfSevTch +  37)
#define ActSeePstForInsTch	(ActUnfSevTch +  38)
#define ActSeePstForGenUsr	(ActUnfSevTch +  39)
#define ActSeePstForGenTch	(ActUnfSevTch +  40)
#define ActSeePstForSWAUsr	(ActUnfSevTch +  41)
#define ActSeePstForSWATch	(ActUnfSevTch +  42)
#define ActRcvThrForCrsUsr	(ActUnfSevTch +  43)
#define ActRcvThrForCrsTch	(ActUnfSevTch +  44)
#define ActRcvThrForDegUsr	(ActUnfSevTch +  45)
#define ActRcvThrForDegTch	(ActUnfSevTch +  46)
#define ActRcvThrForCtrUsr	(ActUnfSevTch +  47)
#define ActRcvThrForCtrTch	(ActUnfSevTch +  48)
#define ActRcvThrForInsUsr	(ActUnfSevTch +  49)
#define ActRcvThrForInsTch	(ActUnfSevTch +  50)
#define ActRcvThrForGenUsr	(ActUnfSevTch +  51)
#define ActRcvThrForGenTch	(ActUnfSevTch +  52)
#define ActRcvThrForSWAUsr	(ActUnfSevTch +  53)
#define ActRcvThrForSWATch	(ActUnfSevTch +  54)
#define ActRcvRepForCrsUsr	(ActUnfSevTch +  55)
#define ActRcvRepForCrsTch	(ActUnfSevTch +  56)
#define ActRcvRepForDegUsr	(ActUnfSevTch +  57)
#define ActRcvRepForDegTch	(ActUnfSevTch +  58)
#define ActRcvRepForCtrUsr	(ActUnfSevTch +  59)
#define ActRcvRepForCtrTch	(ActUnfSevTch +  60)
#define ActRcvRepForInsUsr	(ActUnfSevTch +  61)
#define ActRcvRepForInsTch	(ActUnfSevTch +  62)
#define ActRcvRepForGenUsr	(ActUnfSevTch +  63)
#define ActRcvRepForGenTch	(ActUnfSevTch +  64)
#define ActRcvRepForSWAUsr	(ActUnfSevTch +  65)
#define ActRcvRepForSWATch	(ActUnfSevTch +  66)
#define ActReqDelThrCrsUsr	(ActUnfSevTch +  67)
#define ActReqDelThrCrsTch	(ActUnfSevTch +  68)
#define ActReqDelThrDegUsr	(ActUnfSevTch +  69)
#define ActReqDelThrDegTch	(ActUnfSevTch +  70)
#define ActReqDelThrCtrUsr	(ActUnfSevTch +  71)
#define ActReqDelThrCtrTch	(ActUnfSevTch +  72)
#define ActReqDelThrInsUsr	(ActUnfSevTch +  73)
#define ActReqDelThrInsTch	(ActUnfSevTch +  74)
#define ActReqDelThrGenUsr	(ActUnfSevTch +  75)
#define ActReqDelThrGenTch	(ActUnfSevTch +  76)
#define ActReqDelThrSWAUsr	(ActUnfSevTch +  77)
#define ActReqDelThrSWATch	(ActUnfSevTch +  78)
#define ActDelThrForCrsUsr	(ActUnfSevTch +  79)
#define ActDelThrForCrsTch	(ActUnfSevTch +  80)
#define ActDelThrForDegUsr	(ActUnfSevTch +  81)
#define ActDelThrForDegTch	(ActUnfSevTch +  82)
#define ActDelThrForCtrUsr	(ActUnfSevTch +  83)
#define ActDelThrForCtrTch	(ActUnfSevTch +  84)
#define ActDelThrForInsUsr	(ActUnfSevTch +  85)
#define ActDelThrForInsTch	(ActUnfSevTch +  86)
#define ActDelThrForGenUsr	(ActUnfSevTch +  87)
#define ActDelThrForGenTch	(ActUnfSevTch +  88)
#define ActDelThrForSWAUsr	(ActUnfSevTch +  89)
#define ActDelThrForSWATch	(ActUnfSevTch +  90)
#define ActCutThrForCrsUsr	(ActUnfSevTch +  91)
#define ActCutThrForCrsTch	(ActUnfSevTch +  92)
#define ActCutThrForDegUsr	(ActUnfSevTch +  93)
#define ActCutThrForDegTch	(ActUnfSevTch +  94)
#define ActCutThrForCtrUsr	(ActUnfSevTch +  95)
#define ActCutThrForCtrTch	(ActUnfSevTch +  96)
#define ActCutThrForInsUsr	(ActUnfSevTch +  97)
#define ActCutThrForInsTch	(ActUnfSevTch +  98)
#define ActCutThrForGenUsr	(ActUnfSevTch +  99)
#define ActCutThrForGenTch	(ActUnfSevTch + 100)
#define ActCutThrForSWAUsr	(ActUnfSevTch + 101)
#define ActCutThrForSWATch	(ActUnfSevTch + 102)
#define ActPasThrForCrsUsr	(ActUnfSevTch + 103)
#define ActPasThrForCrsTch	(ActUnfSevTch + 104)
#define ActPasThrForDegUsr	(ActUnfSevTch + 105)
#define ActPasThrForDegTch	(ActUnfSevTch + 106)
#define ActPasThrForCtrUsr	(ActUnfSevTch + 107)
#define ActPasThrForCtrTch	(ActUnfSevTch + 108)
#define ActPasThrForInsUsr	(ActUnfSevTch + 109)
#define ActPasThrForInsTch	(ActUnfSevTch + 110)
#define ActPasThrForGenUsr	(ActUnfSevTch + 111)
#define ActPasThrForGenTch	(ActUnfSevTch + 112)
#define ActPasThrForSWAUsr	(ActUnfSevTch + 113)
#define ActPasThrForSWATch	(ActUnfSevTch + 114)
#define ActDelPstForCrsUsr	(ActUnfSevTch + 115)
#define ActDelPstForCrsTch	(ActUnfSevTch + 116)
#define ActDelPstForDegUsr	(ActUnfSevTch + 117)
#define ActDelPstForDegTch	(ActUnfSevTch + 118)
#define ActDelPstForCtrUsr	(ActUnfSevTch + 119)
#define ActDelPstForCtrTch	(ActUnfSevTch + 120)
#define ActDelPstForInsUsr	(ActUnfSevTch + 121)
#define ActDelPstForInsTch	(ActUnfSevTch + 122)
#define ActDelPstForGenUsr	(ActUnfSevTch + 123)
#define ActDelPstForGenTch	(ActUnfSevTch + 124)
#define ActDelPstForSWAUsr	(ActUnfSevTch + 125)
#define ActDelPstForSWATch	(ActUnfSevTch + 126)
#define ActEnbPstForCrsUsr	(ActUnfSevTch + 127)
#define ActEnbPstForCrsTch	(ActUnfSevTch + 128)
#define ActEnbPstForDegUsr	(ActUnfSevTch + 129)
#define ActEnbPstForDegTch	(ActUnfSevTch + 130)
#define ActEnbPstForCtrUsr	(ActUnfSevTch + 131)
#define ActEnbPstForCtrTch	(ActUnfSevTch + 132)
#define ActEnbPstForInsUsr	(ActUnfSevTch + 133)
#define ActEnbPstForInsTch	(ActUnfSevTch + 134)
#define ActEnbPstForGenUsr	(ActUnfSevTch + 135)
#define ActEnbPstForGenTch	(ActUnfSevTch + 136)
#define ActEnbPstForSWAUsr	(ActUnfSevTch + 137)
#define ActEnbPstForSWATch	(ActUnfSevTch + 138)
#define ActDisPstForCrsUsr	(ActUnfSevTch + 139)
#define ActDisPstForCrsTch	(ActUnfSevTch + 140)
#define ActDisPstForDegUsr	(ActUnfSevTch + 141)
#define ActDisPstForDegTch	(ActUnfSevTch + 142)
#define ActDisPstForCtrUsr	(ActUnfSevTch + 143)
#define ActDisPstForCtrTch	(ActUnfSevTch + 144)
#define ActDisPstForInsUsr	(ActUnfSevTch + 145)
#define ActDisPstForInsTch	(ActUnfSevTch + 146)
#define ActDisPstForGenUsr	(ActUnfSevTch + 147)
#define ActDisPstForGenTch	(ActUnfSevTch + 148)
#define ActDisPstForSWAUsr	(ActUnfSevTch + 149)
#define ActDisPstForSWATch	(ActUnfSevTch + 150)
#define ActReqLnkForCrsUsr	(ActUnfSevTch + 151)

#define ActCht			(ActUnfSevTch + 152)

#define ActReqMsgUsr		(ActUnfSevTch + 153)
#define ActSeeSntMsg		(ActUnfSevTch + 154)

#define ActRcvMsgUsr		(ActUnfSevTch + 155)
#define ActReqDelAllSntMsg	(ActUnfSevTch + 156)
#define ActReqDelAllRcvMsg	(ActUnfSevTch + 157)
#define ActDelAllSntMsg		(ActUnfSevTch + 158)
#define ActDelAllRcvMsg		(ActUnfSevTch + 159)
#define ActDelSntMsg		(ActUnfSevTch + 160)
#define ActDelRcvMsg		(ActUnfSevTch + 161)
#define ActExpSntMsg		(ActUnfSevTch + 162)
#define ActExpRcvMsg		(ActUnfSevTch + 163)
#define ActConSntMsg		(ActUnfSevTch + 164)
#define ActConRcvMsg		(ActUnfSevTch + 165)
#define ActLstBanUsr		(ActUnfSevTch + 166)
#define ActBanUsrMsg		(ActUnfSevTch + 167)
#define ActUnbUsrMsg		(ActUnfSevTch + 168)
#define ActUnbUsrLst		(ActUnfSevTch + 169)

#define ActMaiUsr		(ActUnfSevTch + 170)

/*****************************************************************************/
/****************************** Analytics tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActReqUseGbl		(ActMaiUsr +  1)
#define ActSeePhoDeg		(ActMaiUsr +  2)
#define ActReqStaCrs		(ActMaiUsr +  3)
#define ActReqAccGbl		(ActMaiUsr +  4)
#define ActReqMyUsgRep		(ActMaiUsr +  5)
#define ActMFUAct		(ActMaiUsr +  6)

// Secondary actions
#define ActSeeUseGbl		(ActMaiUsr +  7)
#define ActPrnPhoDeg		(ActMaiUsr +  8)
#define ActCalPhoDeg		(ActMaiUsr +  9)
#define ActSeeAccGbl		(ActMaiUsr + 10)
#define ActReqAccCrs		(ActMaiUsr + 11)
#define ActSeeAccCrs		(ActMaiUsr + 12)
#define ActSeeAllStaCrs		(ActMaiUsr + 13)

#define ActLstClk		(ActMaiUsr + 14)
#define ActRefLstClk		(ActMaiUsr + 15)

#define ActSeeMyUsgRep		(ActMaiUsr + 16)

/*****************************************************************************/
/******************************** Profile tab ********************************/
/*****************************************************************************/
// Actions in menu
#define ActFrmRolSes		(ActSeeMyUsgRep +  1)
#define ActMyCrs		(ActSeeMyUsgRep +  2)
#define ActSeeMyTT		(ActSeeMyUsgRep +  3)
#define ActSeeMyAgd		(ActSeeMyUsgRep +  4)
#define ActFrmMyAcc		(ActSeeMyUsgRep +  5)
#define ActReqEdiRecSha		(ActSeeMyUsgRep +  6)
#define ActReqEdiSet		(ActSeeMyUsgRep +  7)
// Secondary actions
#define ActChgMyRol		(ActSeeMyUsgRep +  8)
#define ActFrmNewEvtMyAgd	(ActSeeMyUsgRep +  9)
#define ActEdiOneEvtMyAgd	(ActSeeMyUsgRep + 10)
#define ActNewEvtMyAgd		(ActSeeMyUsgRep + 11)
#define ActChgEvtMyAgd		(ActSeeMyUsgRep + 12)
#define ActReqRemEvtMyAgd	(ActSeeMyUsgRep + 13)
#define ActRemEvtMyAgd		(ActSeeMyUsgRep + 14)
#define ActHidEvtMyAgd		(ActSeeMyUsgRep + 15)
#define ActUnhEvtMyAgd		(ActSeeMyUsgRep + 16)
#define ActPrvEvtMyAgd		(ActSeeMyUsgRep + 17)
#define ActPubEvtMyAgd		(ActSeeMyUsgRep + 18)
#define ActPrnAgdQR		(ActSeeMyUsgRep + 19)

#define ActChkUsrAcc		(ActSeeMyUsgRep + 20)
#define ActCreMyAcc		(ActSeeMyUsgRep + 21)
#define ActCreUsrAcc		(ActSeeMyUsgRep + 22)
#define ActRemMyID		(ActSeeMyUsgRep + 23)
#define ActChgMyID		(ActSeeMyUsgRep + 24)
#define ActRemMyNck		(ActSeeMyUsgRep + 25)
#define ActChgMyNck		(ActSeeMyUsgRep + 26)
#define ActRemMyMai		(ActSeeMyUsgRep + 27)
#define ActChgMyMai		(ActSeeMyUsgRep + 28)
#define ActCnfMai		(ActSeeMyUsgRep + 29)
#define ActChgMyPwd		(ActSeeMyUsgRep + 30)
#define ActReqRemMyAcc		(ActSeeMyUsgRep + 31)
#define ActRemMyAcc		(ActSeeMyUsgRep + 32)

#define ActChgMyData		(ActSeeMyUsgRep + 33)

#define ActReqMyPho		(ActSeeMyUsgRep + 34)
#define ActDetMyPho		(ActSeeMyUsgRep + 35)
#define ActUpdMyPho		(ActSeeMyUsgRep + 36)
#define ActReqRemMyPho		(ActSeeMyUsgRep + 37)
#define ActRemMyPho		(ActSeeMyUsgRep + 38)

#define ActChgCtyMyIns		(ActSeeMyUsgRep + 39)
#define ActChgMyIns		(ActSeeMyUsgRep + 40)
#define ActChgMyCtr		(ActSeeMyUsgRep + 41)
#define ActChgMyDpt		(ActSeeMyUsgRep + 42)
#define ActChgMyOff		(ActSeeMyUsgRep + 43)
#define ActChgMyOffPho		(ActSeeMyUsgRep + 44)

#define ActReqEdiMyNet		(ActSeeMyUsgRep + 45)
#define ActChgMyNet		(ActSeeMyUsgRep + 46)

#define ActChgThe		(ActSeeMyUsgRep + 47)
#define ActReqChgLan		(ActSeeMyUsgRep + 48)
#define ActChgLan		(ActSeeMyUsgRep + 49)
#define ActChg1stDay		(ActSeeMyUsgRep + 50)
#define ActChgDatFmt		(ActSeeMyUsgRep + 51)
#define ActChgCol		(ActSeeMyUsgRep + 52)
#define ActChgIco		(ActSeeMyUsgRep + 53)
#define ActChgMnu		(ActSeeMyUsgRep + 54)
#define ActChgUsrPho		(ActSeeMyUsgRep + 55)
#define ActChgPriPho		(ActSeeMyUsgRep + 56)
#define ActChgBasPriPrf		(ActSeeMyUsgRep + 57)
#define ActChgExtPriPrf		(ActSeeMyUsgRep + 58)
#define ActChgCooPrf		(ActSeeMyUsgRep + 59)
#define ActChgNtfPrf		(ActSeeMyUsgRep + 60)

#define ActPrnUsrQR		(ActSeeMyUsgRep + 61)

#define ActPrnMyTT		(ActSeeMyUsgRep + 62)
#define ActEdiTut		(ActSeeMyUsgRep + 63)
#define ActChgTut		(ActSeeMyUsgRep + 64)
#define ActChgMyTT1stDay	(ActSeeMyUsgRep + 65)

#define Act_NUM_ACTIONS		(ActChgMyTT1stDay + 1)

/*****************************************************************************/
/******************************** Public types *******************************/
/*****************************************************************************/

struct Act_Tabs
  {
   char *Icon;
  };

struct Act_Actions
  {
   long ActCod;	// Unique, time-persistent numerical code for the action
   signed int IndexInMenu;
   Tab_Tab_t Tab;
   Act_Action_t SuperAction;
   unsigned PermissionCrsIfIBelong;
   unsigned PermissionCrsIfIDontBelong;
   unsigned PermissionDeg;
   unsigned PermissionCtr;
   unsigned PermissionIns;
   unsigned PermissionCty;
   unsigned PermissionSys;
   Act_Content_t ContentType;
   Act_BrowserTab_t BrowserTab;
   void (*FunctionPriori) ();
   void (*FunctionPosteriori) ();
   const char *Icon;
  };

/*****************************************************************************/
/***************************** Public prototypes *****************************/
/*****************************************************************************/

Act_Action_t Act_GetActionFromActCod (long ActCod);
long Act_GetActCod (Act_Action_t Action);
signed int Act_GetIndexInMenu (Act_Action_t Action);
Tab_Tab_t Act_GetTab (Act_Action_t Action);
Act_Action_t Act_GetSuperAction (Act_Action_t Action);
bool Act_CheckIfIHavePermissionToExecuteAction (Act_Action_t Action);
Act_Content_t Act_GetContentType (Act_Action_t Action);
Act_BrowserTab_t Act_GetBrowserTab (Act_Action_t Action);
void (*Act_GetFunctionPriori (Act_Action_t Action)) (void);
void (*Act_GetFunctionPosteriori (Act_Action_t Action)) (void);
const char *Act_GetIcon (Act_Action_t Action);

const char *Act_GetTitleAction (Act_Action_t Action);
const char *Act_GetActionText (Act_Action_t Action);

void Act_AdjustActionWhenNoUsrLogged (void);
void Act_AdjustCurrentAction (void);

#endif
