/* soapServer.c
   Generated by gSOAP 2.8.18 from swad_web_service.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.18 2014-12-03 18:12:24 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:createAccount"))
		return soap_serve_swad__createAccount(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:loginByUserPasswordKey"))
		return soap_serve_swad__loginByUserPasswordKey(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:loginBySessionKey"))
		return soap_serve_swad__loginBySessionKey(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getNewPassword"))
		return soap_serve_swad__getNewPassword(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getCourses"))
		return soap_serve_swad__getCourses(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getCourseInfo"))
		return soap_serve_swad__getCourseInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getGroupTypes"))
		return soap_serve_swad__getGroupTypes(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getGroups"))
		return soap_serve_swad__getGroups(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:sendMyGroups"))
		return soap_serve_swad__sendMyGroups(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getDirectoryTree"))
		return soap_serve_swad__getDirectoryTree(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getFile"))
		return soap_serve_swad__getFile(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getMarks"))
		return soap_serve_swad__getMarks(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getTestConfig"))
		return soap_serve_swad__getTestConfig(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getTests"))
		return soap_serve_swad__getTests(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getUsers"))
		return soap_serve_swad__getUsers(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getAttendanceEvents"))
		return soap_serve_swad__getAttendanceEvents(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:sendAttendanceEvent"))
		return soap_serve_swad__sendAttendanceEvent(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getAttendanceUsers"))
		return soap_serve_swad__getAttendanceUsers(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:sendAttendanceUsers"))
		return soap_serve_swad__sendAttendanceUsers(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:getNotifications"))
		return soap_serve_swad__getNotifications(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:markNotificationsAsRead"))
		return soap_serve_swad__markNotificationsAsRead(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:sendNotice"))
		return soap_serve_swad__sendNotice(soap);
	if (!soap_match_tag(soap, soap->tag, "swad:sendMessage"))
		return soap_serve_swad__sendMessage(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__createAccount(struct soap *soap)
{	struct swad__createAccount soap_tmp_swad__createAccount;
	struct swad__createAccountOutput createAccountOut;
	soap_default_swad__createAccountOutput(soap, &createAccountOut);
	soap_default_swad__createAccount(soap, &soap_tmp_swad__createAccount);
	if (!soap_get_swad__createAccount(soap, &soap_tmp_swad__createAccount, "swad:createAccount", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__createAccount(soap, soap_tmp_swad__createAccount.userNickname, soap_tmp_swad__createAccount.userEmail, soap_tmp_swad__createAccount.userID, soap_tmp_swad__createAccount.userPassword, soap_tmp_swad__createAccount.appKey, &createAccountOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__createAccountOutput(soap, &createAccountOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__createAccountOutput(soap, &createAccountOut, "swad:createAccountOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__createAccountOutput(soap, &createAccountOut, "swad:createAccountOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__loginByUserPasswordKey(struct soap *soap)
{	struct swad__loginByUserPasswordKey soap_tmp_swad__loginByUserPasswordKey;
	struct swad__loginByUserPasswordKeyOutput loginByUserPasswordKeyOut;
	soap_default_swad__loginByUserPasswordKeyOutput(soap, &loginByUserPasswordKeyOut);
	soap_default_swad__loginByUserPasswordKey(soap, &soap_tmp_swad__loginByUserPasswordKey);
	if (!soap_get_swad__loginByUserPasswordKey(soap, &soap_tmp_swad__loginByUserPasswordKey, "swad:loginByUserPasswordKey", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__loginByUserPasswordKey(soap, soap_tmp_swad__loginByUserPasswordKey.userID, soap_tmp_swad__loginByUserPasswordKey.userPassword, soap_tmp_swad__loginByUserPasswordKey.appKey, &loginByUserPasswordKeyOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__loginByUserPasswordKeyOutput(soap, &loginByUserPasswordKeyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__loginByUserPasswordKeyOutput(soap, &loginByUserPasswordKeyOut, "swad:loginByUserPasswordKeyOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__loginByUserPasswordKeyOutput(soap, &loginByUserPasswordKeyOut, "swad:loginByUserPasswordKeyOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__loginBySessionKey(struct soap *soap)
{	struct swad__loginBySessionKey soap_tmp_swad__loginBySessionKey;
	struct swad__loginBySessionKeyOutput loginBySessionKeyOut;
	soap_default_swad__loginBySessionKeyOutput(soap, &loginBySessionKeyOut);
	soap_default_swad__loginBySessionKey(soap, &soap_tmp_swad__loginBySessionKey);
	if (!soap_get_swad__loginBySessionKey(soap, &soap_tmp_swad__loginBySessionKey, "swad:loginBySessionKey", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__loginBySessionKey(soap, soap_tmp_swad__loginBySessionKey.sessionID, soap_tmp_swad__loginBySessionKey.appKey, &loginBySessionKeyOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__loginBySessionKeyOutput(soap, &loginBySessionKeyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__loginBySessionKeyOutput(soap, &loginBySessionKeyOut, "swad:loginBySessionKeyOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__loginBySessionKeyOutput(soap, &loginBySessionKeyOut, "swad:loginBySessionKeyOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getNewPassword(struct soap *soap)
{	struct swad__getNewPassword soap_tmp_swad__getNewPassword;
	struct swad__getNewPasswordOutput getNewPasswordOut;
	soap_default_swad__getNewPasswordOutput(soap, &getNewPasswordOut);
	soap_default_swad__getNewPassword(soap, &soap_tmp_swad__getNewPassword);
	if (!soap_get_swad__getNewPassword(soap, &soap_tmp_swad__getNewPassword, "swad:getNewPassword", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getNewPassword(soap, soap_tmp_swad__getNewPassword.userID, soap_tmp_swad__getNewPassword.appKey, &getNewPasswordOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getNewPasswordOutput(soap, &getNewPasswordOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getNewPasswordOutput(soap, &getNewPasswordOut, "swad:getNewPasswordOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getNewPasswordOutput(soap, &getNewPasswordOut, "swad:getNewPasswordOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getCourses(struct soap *soap)
{	struct swad__getCourses soap_tmp_swad__getCourses;
	struct swad__getCoursesOutput getCoursesOut;
	soap_default_swad__getCoursesOutput(soap, &getCoursesOut);
	soap_default_swad__getCourses(soap, &soap_tmp_swad__getCourses);
	if (!soap_get_swad__getCourses(soap, &soap_tmp_swad__getCourses, "swad:getCourses", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getCourses(soap, soap_tmp_swad__getCourses.wsKey, &getCoursesOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getCoursesOutput(soap, &getCoursesOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getCoursesOutput(soap, &getCoursesOut, "swad:getCoursesOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getCoursesOutput(soap, &getCoursesOut, "swad:getCoursesOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getCourseInfo(struct soap *soap)
{	struct swad__getCourseInfo soap_tmp_swad__getCourseInfo;
	struct swad__getCourseInfoOutput getCourseInfoOut;
	soap_default_swad__getCourseInfoOutput(soap, &getCourseInfoOut);
	soap_default_swad__getCourseInfo(soap, &soap_tmp_swad__getCourseInfo);
	if (!soap_get_swad__getCourseInfo(soap, &soap_tmp_swad__getCourseInfo, "swad:getCourseInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getCourseInfo(soap, soap_tmp_swad__getCourseInfo.wsKey, soap_tmp_swad__getCourseInfo.courseCode, soap_tmp_swad__getCourseInfo.infoType, &getCourseInfoOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getCourseInfoOutput(soap, &getCourseInfoOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getCourseInfoOutput(soap, &getCourseInfoOut, "swad:getCourseInfoOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getCourseInfoOutput(soap, &getCourseInfoOut, "swad:getCourseInfoOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getGroupTypes(struct soap *soap)
{	struct swad__getGroupTypes soap_tmp_swad__getGroupTypes;
	struct swad__getGroupTypesOutput getGroupTypesOut;
	soap_default_swad__getGroupTypesOutput(soap, &getGroupTypesOut);
	soap_default_swad__getGroupTypes(soap, &soap_tmp_swad__getGroupTypes);
	if (!soap_get_swad__getGroupTypes(soap, &soap_tmp_swad__getGroupTypes, "swad:getGroupTypes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getGroupTypes(soap, soap_tmp_swad__getGroupTypes.wsKey, soap_tmp_swad__getGroupTypes.courseCode, &getGroupTypesOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getGroupTypesOutput(soap, &getGroupTypesOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getGroupTypesOutput(soap, &getGroupTypesOut, "swad:getGroupTypesOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getGroupTypesOutput(soap, &getGroupTypesOut, "swad:getGroupTypesOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getGroups(struct soap *soap)
{	struct swad__getGroups soap_tmp_swad__getGroups;
	struct swad__getGroupsOutput getGroupsOut;
	soap_default_swad__getGroupsOutput(soap, &getGroupsOut);
	soap_default_swad__getGroups(soap, &soap_tmp_swad__getGroups);
	if (!soap_get_swad__getGroups(soap, &soap_tmp_swad__getGroups, "swad:getGroups", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getGroups(soap, soap_tmp_swad__getGroups.wsKey, soap_tmp_swad__getGroups.courseCode, &getGroupsOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getGroupsOutput(soap, &getGroupsOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getGroupsOutput(soap, &getGroupsOut, "swad:getGroupsOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getGroupsOutput(soap, &getGroupsOut, "swad:getGroupsOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendMyGroups(struct soap *soap)
{	struct swad__sendMyGroups soap_tmp_swad__sendMyGroups;
	struct swad__sendMyGroupsOutput sendMyGroupsOut;
	soap_default_swad__sendMyGroupsOutput(soap, &sendMyGroupsOut);
	soap_default_swad__sendMyGroups(soap, &soap_tmp_swad__sendMyGroups);
	if (!soap_get_swad__sendMyGroups(soap, &soap_tmp_swad__sendMyGroups, "swad:sendMyGroups", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__sendMyGroups(soap, soap_tmp_swad__sendMyGroups.wsKey, soap_tmp_swad__sendMyGroups.courseCode, soap_tmp_swad__sendMyGroups.myGroups, &sendMyGroupsOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__sendMyGroupsOutput(soap, &sendMyGroupsOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__sendMyGroupsOutput(soap, &sendMyGroupsOut, "swad:sendMyGroupsOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__sendMyGroupsOutput(soap, &sendMyGroupsOut, "swad:sendMyGroupsOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getDirectoryTree(struct soap *soap)
{	struct swad__getDirectoryTree soap_tmp_swad__getDirectoryTree;
	struct swad__getDirectoryTreeOutput getDirectoryTreeOut;
	soap_default_swad__getDirectoryTreeOutput(soap, &getDirectoryTreeOut);
	soap_default_swad__getDirectoryTree(soap, &soap_tmp_swad__getDirectoryTree);
	if (!soap_get_swad__getDirectoryTree(soap, &soap_tmp_swad__getDirectoryTree, "swad:getDirectoryTree", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getDirectoryTree(soap, soap_tmp_swad__getDirectoryTree.wsKey, soap_tmp_swad__getDirectoryTree.courseCode, soap_tmp_swad__getDirectoryTree.groupCode, soap_tmp_swad__getDirectoryTree.treeCode, &getDirectoryTreeOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getDirectoryTreeOutput(soap, &getDirectoryTreeOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getDirectoryTreeOutput(soap, &getDirectoryTreeOut, "swad:getDirectoryTreeOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getDirectoryTreeOutput(soap, &getDirectoryTreeOut, "swad:getDirectoryTreeOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getFile(struct soap *soap)
{	struct swad__getFile soap_tmp_swad__getFile;
	struct swad__getFileOutput getFileOut;
	soap_default_swad__getFileOutput(soap, &getFileOut);
	soap_default_swad__getFile(soap, &soap_tmp_swad__getFile);
	if (!soap_get_swad__getFile(soap, &soap_tmp_swad__getFile, "swad:getFile", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getFile(soap, soap_tmp_swad__getFile.wsKey, soap_tmp_swad__getFile.fileCode, &getFileOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getFileOutput(soap, &getFileOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getFileOutput(soap, &getFileOut, "swad:getFileOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getFileOutput(soap, &getFileOut, "swad:getFileOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getMarks(struct soap *soap)
{	struct swad__getMarks soap_tmp_swad__getMarks;
	struct swad__getMarksOutput getMarksOut;
	soap_default_swad__getMarksOutput(soap, &getMarksOut);
	soap_default_swad__getMarks(soap, &soap_tmp_swad__getMarks);
	if (!soap_get_swad__getMarks(soap, &soap_tmp_swad__getMarks, "swad:getMarks", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getMarks(soap, soap_tmp_swad__getMarks.wsKey, soap_tmp_swad__getMarks.fileCode, &getMarksOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getMarksOutput(soap, &getMarksOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getMarksOutput(soap, &getMarksOut, "swad:getMarksOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getMarksOutput(soap, &getMarksOut, "swad:getMarksOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getTestConfig(struct soap *soap)
{	struct swad__getTestConfig soap_tmp_swad__getTestConfig;
	struct swad__getTestConfigOutput getTestConfigOut;
	soap_default_swad__getTestConfigOutput(soap, &getTestConfigOut);
	soap_default_swad__getTestConfig(soap, &soap_tmp_swad__getTestConfig);
	if (!soap_get_swad__getTestConfig(soap, &soap_tmp_swad__getTestConfig, "swad:getTestConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getTestConfig(soap, soap_tmp_swad__getTestConfig.wsKey, soap_tmp_swad__getTestConfig.courseCode, &getTestConfigOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getTestConfigOutput(soap, &getTestConfigOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getTestConfigOutput(soap, &getTestConfigOut, "swad:getTestConfigOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getTestConfigOutput(soap, &getTestConfigOut, "swad:getTestConfigOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getTests(struct soap *soap)
{	struct swad__getTests soap_tmp_swad__getTests;
	struct swad__getTestsOutput getTestsOut;
	soap_default_swad__getTestsOutput(soap, &getTestsOut);
	soap_default_swad__getTests(soap, &soap_tmp_swad__getTests);
	if (!soap_get_swad__getTests(soap, &soap_tmp_swad__getTests, "swad:getTests", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getTests(soap, soap_tmp_swad__getTests.wsKey, soap_tmp_swad__getTests.courseCode, soap_tmp_swad__getTests.beginTime, &getTestsOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getTestsOutput(soap, &getTestsOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getTestsOutput(soap, &getTestsOut, "swad:getTestsOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getTestsOutput(soap, &getTestsOut, "swad:getTestsOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getUsers(struct soap *soap)
{	struct swad__getUsers soap_tmp_swad__getUsers;
	struct swad__getUsersOutput getUsersOut;
	soap_default_swad__getUsersOutput(soap, &getUsersOut);
	soap_default_swad__getUsers(soap, &soap_tmp_swad__getUsers);
	if (!soap_get_swad__getUsers(soap, &soap_tmp_swad__getUsers, "swad:getUsers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getUsers(soap, soap_tmp_swad__getUsers.wsKey, soap_tmp_swad__getUsers.courseCode, soap_tmp_swad__getUsers.groupCode, soap_tmp_swad__getUsers.userRole, &getUsersOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getUsersOutput(soap, &getUsersOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getUsersOutput(soap, &getUsersOut, "swad:getUsersOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getUsersOutput(soap, &getUsersOut, "swad:getUsersOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getAttendanceEvents(struct soap *soap)
{	struct swad__getAttendanceEvents soap_tmp_swad__getAttendanceEvents;
	struct swad__getAttendanceEventsOutput getAttendanceEventsOut;
	soap_default_swad__getAttendanceEventsOutput(soap, &getAttendanceEventsOut);
	soap_default_swad__getAttendanceEvents(soap, &soap_tmp_swad__getAttendanceEvents);
	if (!soap_get_swad__getAttendanceEvents(soap, &soap_tmp_swad__getAttendanceEvents, "swad:getAttendanceEvents", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getAttendanceEvents(soap, soap_tmp_swad__getAttendanceEvents.wsKey, soap_tmp_swad__getAttendanceEvents.courseCode, &getAttendanceEventsOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getAttendanceEventsOutput(soap, &getAttendanceEventsOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getAttendanceEventsOutput(soap, &getAttendanceEventsOut, "swad:getAttendanceEventsOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getAttendanceEventsOutput(soap, &getAttendanceEventsOut, "swad:getAttendanceEventsOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendAttendanceEvent(struct soap *soap)
{	struct swad__sendAttendanceEvent soap_tmp_swad__sendAttendanceEvent;
	struct swad__sendAttendanceEventOutput sendAttendanceEventOut;
	soap_default_swad__sendAttendanceEventOutput(soap, &sendAttendanceEventOut);
	soap_default_swad__sendAttendanceEvent(soap, &soap_tmp_swad__sendAttendanceEvent);
	if (!soap_get_swad__sendAttendanceEvent(soap, &soap_tmp_swad__sendAttendanceEvent, "swad:sendAttendanceEvent", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__sendAttendanceEvent(soap, soap_tmp_swad__sendAttendanceEvent.wsKey, soap_tmp_swad__sendAttendanceEvent.attendanceEventCode, soap_tmp_swad__sendAttendanceEvent.courseCode, soap_tmp_swad__sendAttendanceEvent.hidden, soap_tmp_swad__sendAttendanceEvent.startTime, soap_tmp_swad__sendAttendanceEvent.endTime, soap_tmp_swad__sendAttendanceEvent.commentsTeachersVisible, soap_tmp_swad__sendAttendanceEvent.title, soap_tmp_swad__sendAttendanceEvent.text, soap_tmp_swad__sendAttendanceEvent.groups, &sendAttendanceEventOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__sendAttendanceEventOutput(soap, &sendAttendanceEventOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__sendAttendanceEventOutput(soap, &sendAttendanceEventOut, "swad:sendAttendanceEventOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__sendAttendanceEventOutput(soap, &sendAttendanceEventOut, "swad:sendAttendanceEventOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getAttendanceUsers(struct soap *soap)
{	struct swad__getAttendanceUsers soap_tmp_swad__getAttendanceUsers;
	struct swad__getAttendanceUsersOutput getAttendanceUsersOut;
	soap_default_swad__getAttendanceUsersOutput(soap, &getAttendanceUsersOut);
	soap_default_swad__getAttendanceUsers(soap, &soap_tmp_swad__getAttendanceUsers);
	if (!soap_get_swad__getAttendanceUsers(soap, &soap_tmp_swad__getAttendanceUsers, "swad:getAttendanceUsers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getAttendanceUsers(soap, soap_tmp_swad__getAttendanceUsers.wsKey, soap_tmp_swad__getAttendanceUsers.attendanceEventCode, &getAttendanceUsersOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getAttendanceUsersOutput(soap, &getAttendanceUsersOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getAttendanceUsersOutput(soap, &getAttendanceUsersOut, "swad:getAttendanceUsersOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getAttendanceUsersOutput(soap, &getAttendanceUsersOut, "swad:getAttendanceUsersOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendAttendanceUsers(struct soap *soap)
{	struct swad__sendAttendanceUsers soap_tmp_swad__sendAttendanceUsers;
	struct swad__sendAttendanceUsersOutput sendAttendanceUsersOut;
	soap_default_swad__sendAttendanceUsersOutput(soap, &sendAttendanceUsersOut);
	soap_default_swad__sendAttendanceUsers(soap, &soap_tmp_swad__sendAttendanceUsers);
	if (!soap_get_swad__sendAttendanceUsers(soap, &soap_tmp_swad__sendAttendanceUsers, "swad:sendAttendanceUsers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__sendAttendanceUsers(soap, soap_tmp_swad__sendAttendanceUsers.wsKey, soap_tmp_swad__sendAttendanceUsers.attendanceEventCode, soap_tmp_swad__sendAttendanceUsers.users, soap_tmp_swad__sendAttendanceUsers.setOthersAsAbsent, &sendAttendanceUsersOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__sendAttendanceUsersOutput(soap, &sendAttendanceUsersOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__sendAttendanceUsersOutput(soap, &sendAttendanceUsersOut, "swad:sendAttendanceUsersOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__sendAttendanceUsersOutput(soap, &sendAttendanceUsersOut, "swad:sendAttendanceUsersOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getNotifications(struct soap *soap)
{	struct swad__getNotifications soap_tmp_swad__getNotifications;
	struct swad__getNotificationsOutput getNotificationsOut;
	soap_default_swad__getNotificationsOutput(soap, &getNotificationsOut);
	soap_default_swad__getNotifications(soap, &soap_tmp_swad__getNotifications);
	if (!soap_get_swad__getNotifications(soap, &soap_tmp_swad__getNotifications, "swad:getNotifications", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__getNotifications(soap, soap_tmp_swad__getNotifications.wsKey, soap_tmp_swad__getNotifications.beginTime, &getNotificationsOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__getNotificationsOutput(soap, &getNotificationsOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__getNotificationsOutput(soap, &getNotificationsOut, "swad:getNotificationsOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__getNotificationsOutput(soap, &getNotificationsOut, "swad:getNotificationsOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__markNotificationsAsRead(struct soap *soap)
{	struct swad__markNotificationsAsRead soap_tmp_swad__markNotificationsAsRead;
	struct swad__markNotificationsAsReadOutput markNotificationAsReadOut;
	soap_default_swad__markNotificationsAsReadOutput(soap, &markNotificationAsReadOut);
	soap_default_swad__markNotificationsAsRead(soap, &soap_tmp_swad__markNotificationsAsRead);
	if (!soap_get_swad__markNotificationsAsRead(soap, &soap_tmp_swad__markNotificationsAsRead, "swad:markNotificationsAsRead", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__markNotificationsAsRead(soap, soap_tmp_swad__markNotificationsAsRead.wsKey, soap_tmp_swad__markNotificationsAsRead.notifications, &markNotificationAsReadOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__markNotificationsAsReadOutput(soap, &markNotificationAsReadOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__markNotificationsAsReadOutput(soap, &markNotificationAsReadOut, "swad:markNotificationsAsReadOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__markNotificationsAsReadOutput(soap, &markNotificationAsReadOut, "swad:markNotificationsAsReadOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendNotice(struct soap *soap)
{	struct swad__sendNotice soap_tmp_swad__sendNotice;
	struct swad__sendNoticeOutput sendNoticeOut;
	soap_default_swad__sendNoticeOutput(soap, &sendNoticeOut);
	soap_default_swad__sendNotice(soap, &soap_tmp_swad__sendNotice);
	if (!soap_get_swad__sendNotice(soap, &soap_tmp_swad__sendNotice, "swad:sendNotice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__sendNotice(soap, soap_tmp_swad__sendNotice.wsKey, soap_tmp_swad__sendNotice.courseCode, soap_tmp_swad__sendNotice.body, &sendNoticeOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__sendNoticeOutput(soap, &sendNoticeOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__sendNoticeOutput(soap, &sendNoticeOut, "swad:sendNoticeOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__sendNoticeOutput(soap, &sendNoticeOut, "swad:sendNoticeOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendMessage(struct soap *soap)
{	struct swad__sendMessage soap_tmp_swad__sendMessage;
	struct swad__sendMessageOutput sendMessageOut;
	soap_default_swad__sendMessageOutput(soap, &sendMessageOut);
	soap_default_swad__sendMessage(soap, &soap_tmp_swad__sendMessage);
	if (!soap_get_swad__sendMessage(soap, &soap_tmp_swad__sendMessage, "swad:sendMessage", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = swad__sendMessage(soap, soap_tmp_swad__sendMessage.wsKey, soap_tmp_swad__sendMessage.messageCode, soap_tmp_swad__sendMessage.to, soap_tmp_swad__sendMessage.subject, soap_tmp_swad__sendMessage.body, &sendMessageOut);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_swad__sendMessageOutput(soap, &sendMessageOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_swad__sendMessageOutput(soap, &sendMessageOut, "swad:sendMessageOutput", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_swad__sendMessageOutput(soap, &sendMessageOut, "swad:sendMessageOutput", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
