/* soapStub.h
   Generated by gSOAP 2.8.18 from swad_web_service.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20818
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_swad__createAccountOutput
#define SOAP_TYPE_swad__createAccountOutput (7)
/* swad:createAccountOutput */
struct swad__createAccountOutput
{
	int userCode;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *string;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__loginBySessionKeyOutput
#define SOAP_TYPE_swad__loginBySessionKeyOutput (8)
/* swad:loginBySessionKeyOutput */
struct swad__loginBySessionKeyOutput
{
	int userCode;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int degreeTypeCode;	/* required element of type xsd:int */
	int degreeCode;	/* required element of type xsd:int */
	int courseCode;	/* required element of type xsd:int */
	char *wsKey;	/* optional element of type xsd:string */
	char *userNickname;	/* optional element of type xsd:string */
	char *userID;	/* optional element of type xsd:string */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
	char *userBirthday;	/* optional element of type xsd:string */
	int userRole;	/* required element of type xsd:int */
	char *degreeTypeName;	/* optional element of type xsd:string */
	char *degreeName;	/* optional element of type xsd:string */
	char *courseName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__loginByUserPasswordKeyOutput
#define SOAP_TYPE_swad__loginByUserPasswordKeyOutput (9)
/* swad:loginByUserPasswordKeyOutput */
struct swad__loginByUserPasswordKeyOutput
{
	int userCode;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	char *wsKey;	/* optional element of type xsd:string */
	char *userNickname;	/* optional element of type xsd:string */
	char *userID;	/* optional element of type xsd:string */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
	char *userBirthday;	/* optional element of type xsd:string */
	int userRole;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getNewPasswordOutput
#define SOAP_TYPE_swad__getNewPasswordOutput (10)
/* swad:getNewPasswordOutput */
struct swad__getNewPasswordOutput
{
	int success;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__course
#define SOAP_TYPE_swad__course (11)
/* swad:course */
struct swad__course
{
	int courseCode;	/* required element of type xsd:int */
	char *courseShortName;	/* optional element of type xsd:string */
	char *courseFullName;	/* optional element of type xsd:string */
	int userRole;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__coursesArray
#define SOAP_TYPE_swad__coursesArray (12)
/* Sequence of swad:coursesArray schema type: */
struct swad__coursesArray
{
	struct swad__course *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getCoursesOutput
#define SOAP_TYPE_swad__getCoursesOutput (14)
/* swad:getCoursesOutput */
struct swad__getCoursesOutput
{
	int numCourses;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__coursesArray coursesArray;	/* required element of type swad:coursesArray */
};
#endif

#ifndef SOAP_TYPE_swad__getCourseInfoOutput
#define SOAP_TYPE_swad__getCourseInfoOutput (15)
/* swad:getCourseInfoOutput */
struct swad__getCourseInfoOutput
{
	char *infoSrc;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *infoTxt;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__groupType
#define SOAP_TYPE_swad__groupType (16)
/* swad:groupType */
struct swad__groupType
{
	int groupTypeCode;	/* required element of type xsd:int */
	char *groupTypeName;	/* optional element of type xsd:string */
	int mandatory;	/* required element of type xsd:int */
	int multiple;	/* required element of type xsd:int */
	long openTime;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_swad__groupTypesArray
#define SOAP_TYPE_swad__groupTypesArray (18)
/* Sequence of swad:groupTypesArray schema type: */
struct swad__groupTypesArray
{
	struct swad__groupType *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getGroupTypesOutput
#define SOAP_TYPE_swad__getGroupTypesOutput (20)
/* swad:getGroupTypesOutput */
struct swad__getGroupTypesOutput
{
	int numGroupTypes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__groupTypesArray groupTypesArray;	/* required element of type swad:groupTypesArray */
};
#endif

#ifndef SOAP_TYPE_swad__group
#define SOAP_TYPE_swad__group (21)
/* swad:group */
struct swad__group
{
	int groupCode;	/* required element of type xsd:int */
	char *groupName;	/* optional element of type xsd:string */
	int groupTypeCode;	/* required element of type xsd:int */
	char *groupTypeName;	/* optional element of type xsd:string */
	int open;	/* required element of type xsd:int */
	int maxStudents;	/* required element of type xsd:int */
	int numStudents;	/* required element of type xsd:int */
	int fileZones;	/* required element of type xsd:int */
	int member;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__groupsArray
#define SOAP_TYPE_swad__groupsArray (22)
/* Sequence of swad:groupsArray schema type: */
struct swad__groupsArray
{
	struct swad__group *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getGroupsOutput
#define SOAP_TYPE_swad__getGroupsOutput (24)
/* swad:getGroupsOutput */
struct swad__getGroupsOutput
{
	int numGroups;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__groupsArray groupsArray;	/* required element of type swad:groupsArray */
};
#endif

#ifndef SOAP_TYPE_swad__sendMyGroupsOutput
#define SOAP_TYPE_swad__sendMyGroupsOutput (25)
/* swad:sendMyGroupsOutput */
struct swad__sendMyGroupsOutput
{
	int success;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int numGroups;	/* required element of type xsd:int */
	struct swad__groupsArray groupsArray;	/* required element of type swad:groupsArray */
};
#endif

#ifndef SOAP_TYPE_swad__notification
#define SOAP_TYPE_swad__notification (26)
/* swad:notification */
struct swad__notification
{
	int notifCode;	/* required element of type xsd:int */
	char *eventType;	/* optional element of type xsd:string */
	int eventCode;	/* required element of type xsd:int */
	long eventTime;	/* required element of type xsd:long */
	char *userNickname;	/* optional element of type xsd:string */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
	char *location;	/* optional element of type xsd:string */
	int status;	/* required element of type xsd:int */
	char *summary;	/* optional element of type xsd:string */
	char *content;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__notificationsArray
#define SOAP_TYPE_swad__notificationsArray (27)
/* Sequence of swad:notificationsArray schema type: */
struct swad__notificationsArray
{
	struct swad__notification *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getNotificationsOutput
#define SOAP_TYPE_swad__getNotificationsOutput (29)
/* swad:getNotificationsOutput */
struct swad__getNotificationsOutput
{
	int numNotifications;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__notificationsArray notificationsArray;	/* required element of type swad:notificationsArray */
};
#endif

#ifndef SOAP_TYPE_swad__markNotificationsAsReadOutput
#define SOAP_TYPE_swad__markNotificationsAsReadOutput (30)
/* swad:markNotificationsAsReadOutput */
struct swad__markNotificationsAsReadOutput
{
	int numNotifications;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getTestConfigOutput
#define SOAP_TYPE_swad__getTestConfigOutput (31)
/* swad:getTestConfigOutput */
struct swad__getTestConfigOutput
{
	int pluggable;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int numQuestions;	/* required element of type xsd:int */
	int minQuestions;	/* required element of type xsd:int */
	int defQuestions;	/* required element of type xsd:int */
	int maxQuestions;	/* required element of type xsd:int */
	char *feedback;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__tag
#define SOAP_TYPE_swad__tag (32)
/* swad:tag */
struct swad__tag
{
	int tagCode;	/* required element of type xsd:int */
	char *tagText;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__tagsArray
#define SOAP_TYPE_swad__tagsArray (33)
/* Sequence of swad:tagsArray schema type: */
struct swad__tagsArray
{
	struct swad__tag *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__question
#define SOAP_TYPE_swad__question (35)
/* swad:question */
struct swad__question
{
	int questionCode;	/* required element of type xsd:int */
	char *answerType;	/* optional element of type xsd:string */
	int shuffle;	/* required element of type xsd:int */
	char *stem;	/* optional element of type xsd:string */
	char *feedback;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__questionsArray
#define SOAP_TYPE_swad__questionsArray (36)
/* Sequence of swad:questionsArray schema type: */
struct swad__questionsArray
{
	struct swad__question *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__answer
#define SOAP_TYPE_swad__answer (38)
/* swad:answer */
struct swad__answer
{
	int questionCode;	/* required element of type xsd:int */
	int answerIndex;	/* required element of type xsd:int */
	int correct;	/* required element of type xsd:int */
	char *answerText;	/* optional element of type xsd:string */
	char *answerFeedback;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__answersArray
#define SOAP_TYPE_swad__answersArray (39)
/* Sequence of swad:answersArray schema type: */
struct swad__answersArray
{
	struct swad__answer *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__questionTag
#define SOAP_TYPE_swad__questionTag (41)
/* swad:questionTag */
struct swad__questionTag
{
	int questionCode;	/* required element of type xsd:int */
	int tagCode;	/* required element of type xsd:int */
	int tagIndex;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__questionTagsArray
#define SOAP_TYPE_swad__questionTagsArray (42)
/* Sequence of swad:questionTagsArray schema type: */
struct swad__questionTagsArray
{
	struct swad__questionTag *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getTestsOutput
#define SOAP_TYPE_swad__getTestsOutput (44)
/* swad:getTestsOutput */
struct swad__getTestsOutput
{
	struct swad__tagsArray tagsArray;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type swad:tagsArray */
	struct swad__questionsArray questionsArray;	/* required element of type swad:questionsArray */
	struct swad__answersArray answersArray;	/* required element of type swad:answersArray */
	struct swad__questionTagsArray questionTagsArray;	/* required element of type swad:questionTagsArray */
};
#endif

#ifndef SOAP_TYPE_swad__user
#define SOAP_TYPE_swad__user (45)
/* swad:user */
struct swad__user
{
	int userCode;	/* required element of type xsd:int */
	char *userNickname;	/* optional element of type xsd:string */
	char *userID;	/* optional element of type xsd:string */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__usersArray
#define SOAP_TYPE_swad__usersArray (46)
/* Sequence of swad:usersArray schema type: */
struct swad__usersArray
{
	struct swad__user *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getUsersOutput
#define SOAP_TYPE_swad__getUsersOutput (48)
/* swad:getUsersOutput */
struct swad__getUsersOutput
{
	int numUsers;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__usersArray usersArray;	/* required element of type swad:usersArray */
};
#endif

#ifndef SOAP_TYPE_swad__attendanceEvent
#define SOAP_TYPE_swad__attendanceEvent (49)
/* swad:attendanceEvent */
struct swad__attendanceEvent
{
	int attendanceEventCode;	/* required element of type xsd:int */
	int hidden;	/* required element of type xsd:int */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
	int startTime;	/* required element of type xsd:int */
	int endTime;	/* required element of type xsd:int */
	int commentsTeachersVisible;	/* required element of type xsd:int */
	char *title;	/* optional element of type xsd:string */
	char *text;	/* optional element of type xsd:string */
	char *groups;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__attendanceEventsArray
#define SOAP_TYPE_swad__attendanceEventsArray (50)
/* Sequence of swad:attendanceEventsArray schema type: */
struct swad__attendanceEventsArray
{
	struct swad__attendanceEvent *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getAttendanceEventsOutput
#define SOAP_TYPE_swad__getAttendanceEventsOutput (52)
/* swad:getAttendanceEventsOutput */
struct swad__getAttendanceEventsOutput
{
	int numEvents;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__attendanceEventsArray eventsArray;	/* required element of type swad:attendanceEventsArray */
};
#endif

#ifndef SOAP_TYPE_swad__sendAttendanceEventOutput
#define SOAP_TYPE_swad__sendAttendanceEventOutput (53)
/* swad:sendAttendanceEventOutput */
struct swad__sendAttendanceEventOutput
{
	int attendanceEventCode;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__attendanceUser
#define SOAP_TYPE_swad__attendanceUser (54)
/* swad:attendanceUser */
struct swad__attendanceUser
{
	int userCode;	/* required element of type xsd:int */
	char *userNickname;	/* optional element of type xsd:string */
	char *userID;	/* optional element of type xsd:string */
	char *userSurname1;	/* optional element of type xsd:string */
	char *userSurname2;	/* optional element of type xsd:string */
	char *userFirstname;	/* optional element of type xsd:string */
	char *userPhoto;	/* optional element of type xsd:string */
	int present;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__attendanceUsersArray
#define SOAP_TYPE_swad__attendanceUsersArray (55)
/* Sequence of swad:attendanceUsersArray schema type: */
struct swad__attendanceUsersArray
{
	struct swad__attendanceUser *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_swad__getAttendanceUsersOutput
#define SOAP_TYPE_swad__getAttendanceUsersOutput (57)
/* swad:getAttendanceUsersOutput */
struct swad__getAttendanceUsersOutput
{
	int numUsers;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__attendanceUsersArray usersArray;	/* required element of type swad:attendanceUsersArray */
};
#endif

#ifndef SOAP_TYPE_swad__sendAttendanceUsersOutput
#define SOAP_TYPE_swad__sendAttendanceUsersOutput (58)
/* swad:sendAttendanceUsersOutput */
struct swad__sendAttendanceUsersOutput
{
	int success;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	int numUsers;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getDirectoryTreeOutput
#define SOAP_TYPE_swad__getDirectoryTreeOutput (59)
/* swad:getDirectoryTreeOutput */
struct swad__getDirectoryTreeOutput
{
	char *tree;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getFileOutput
#define SOAP_TYPE_swad__getFileOutput (60)
/* swad:getFileOutput */
struct swad__getFileOutput
{
	char *fileName;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	char *URL;	/* optional element of type xsd:string */
	int size;	/* required element of type xsd:int */
	int time;	/* required element of type xsd:int */
	char *license;	/* optional element of type xsd:string */
	char *publisherName;	/* optional element of type xsd:string */
	char *publisherPhoto;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getMarksOutput
#define SOAP_TYPE_swad__getMarksOutput (61)
/* swad:getMarksOutput */
struct swad__getMarksOutput
{
	char *content;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__sendNoticeOutput
#define SOAP_TYPE_swad__sendNoticeOutput (62)
/* swad:sendNoticeOutput */
struct swad__sendNoticeOutput
{
	int noticeCode;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__sendMessageOutput
#define SOAP_TYPE_swad__sendMessageOutput (63)
/* swad:sendMessageOutput */
struct swad__sendMessageOutput
{
	int numUsers;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct swad__usersArray usersArray;	/* required element of type swad:usersArray */
};
#endif

#ifndef SOAP_TYPE_swad__createAccount
#define SOAP_TYPE_swad__createAccount (66)
/* swad:createAccount */
struct swad__createAccount
{
	char *userNickname;	/* optional element of type xsd:string */
	char *userEmail;	/* optional element of type xsd:string */
	char *userID;	/* optional element of type xsd:string */
	char *userPassword;	/* optional element of type xsd:string */
	char *appKey;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__loginByUserPasswordKey
#define SOAP_TYPE_swad__loginByUserPasswordKey (69)
/* swad:loginByUserPasswordKey */
struct swad__loginByUserPasswordKey
{
	char *userID;	/* optional element of type xsd:string */
	char *userPassword;	/* optional element of type xsd:string */
	char *appKey;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__loginBySessionKey
#define SOAP_TYPE_swad__loginBySessionKey (72)
/* swad:loginBySessionKey */
struct swad__loginBySessionKey
{
	char *sessionID;	/* optional element of type xsd:string */
	char *appKey;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getNewPassword
#define SOAP_TYPE_swad__getNewPassword (75)
/* swad:getNewPassword */
struct swad__getNewPassword
{
	char *userID;	/* optional element of type xsd:string */
	char *appKey;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getCourses
#define SOAP_TYPE_swad__getCourses (78)
/* swad:getCourses */
struct swad__getCourses
{
	char *wsKey;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getCourseInfo
#define SOAP_TYPE_swad__getCourseInfo (81)
/* swad:getCourseInfo */
struct swad__getCourseInfo
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	char *infoType;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getGroupTypes
#define SOAP_TYPE_swad__getGroupTypes (84)
/* swad:getGroupTypes */
struct swad__getGroupTypes
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getGroups
#define SOAP_TYPE_swad__getGroups (87)
/* swad:getGroups */
struct swad__getGroups
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__sendMyGroups
#define SOAP_TYPE_swad__sendMyGroups (90)
/* swad:sendMyGroups */
struct swad__sendMyGroups
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	char *myGroups;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getDirectoryTree
#define SOAP_TYPE_swad__getDirectoryTree (93)
/* swad:getDirectoryTree */
struct swad__getDirectoryTree
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	int groupCode;	/* required element of type xsd:int */
	int treeCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getFile
#define SOAP_TYPE_swad__getFile (96)
/* swad:getFile */
struct swad__getFile
{
	char *wsKey;	/* optional element of type xsd:string */
	int fileCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getMarks
#define SOAP_TYPE_swad__getMarks (99)
/* swad:getMarks */
struct swad__getMarks
{
	char *wsKey;	/* optional element of type xsd:string */
	int fileCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getTestConfig
#define SOAP_TYPE_swad__getTestConfig (102)
/* swad:getTestConfig */
struct swad__getTestConfig
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getTests
#define SOAP_TYPE_swad__getTests (105)
/* swad:getTests */
struct swad__getTests
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	long beginTime;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_swad__getUsers
#define SOAP_TYPE_swad__getUsers (108)
/* swad:getUsers */
struct swad__getUsers
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	int groupCode;	/* required element of type xsd:int */
	int userRole;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getAttendanceEvents
#define SOAP_TYPE_swad__getAttendanceEvents (111)
/* swad:getAttendanceEvents */
struct swad__getAttendanceEvents
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__sendAttendanceEvent
#define SOAP_TYPE_swad__sendAttendanceEvent (114)
/* swad:sendAttendanceEvent */
struct swad__sendAttendanceEvent
{
	char *wsKey;	/* optional element of type xsd:string */
	int attendanceEventCode;	/* required element of type xsd:int */
	int courseCode;	/* required element of type xsd:int */
	int hidden;	/* required element of type xsd:int */
	int startTime;	/* required element of type xsd:int */
	int endTime;	/* required element of type xsd:int */
	int commentsTeachersVisible;	/* required element of type xsd:int */
	char *title;	/* optional element of type xsd:string */
	char *text;	/* optional element of type xsd:string */
	char *groups;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__getAttendanceUsers
#define SOAP_TYPE_swad__getAttendanceUsers (117)
/* swad:getAttendanceUsers */
struct swad__getAttendanceUsers
{
	char *wsKey;	/* optional element of type xsd:string */
	int attendanceEventCode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__sendAttendanceUsers
#define SOAP_TYPE_swad__sendAttendanceUsers (120)
/* swad:sendAttendanceUsers */
struct swad__sendAttendanceUsers
{
	char *wsKey;	/* optional element of type xsd:string */
	int attendanceEventCode;	/* required element of type xsd:int */
	char *users;	/* optional element of type xsd:string */
	int setOthersAsAbsent;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_swad__getNotifications
#define SOAP_TYPE_swad__getNotifications (123)
/* swad:getNotifications */
struct swad__getNotifications
{
	char *wsKey;	/* optional element of type xsd:string */
	long beginTime;	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE_swad__markNotificationsAsRead
#define SOAP_TYPE_swad__markNotificationsAsRead (126)
/* swad:markNotificationsAsRead */
struct swad__markNotificationsAsRead
{
	char *wsKey;	/* optional element of type xsd:string */
	char *notifications;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__sendNotice
#define SOAP_TYPE_swad__sendNotice (129)
/* swad:sendNotice */
struct swad__sendNotice
{
	char *wsKey;	/* optional element of type xsd:string */
	int courseCode;	/* required element of type xsd:int */
	char *body;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_swad__sendMessage
#define SOAP_TYPE_swad__sendMessage (132)
/* swad:sendMessage */
struct swad__sendMessage
{
	char *wsKey;	/* optional element of type xsd:string */
	int messageCode;	/* required element of type xsd:int */
	char *to;	/* optional element of type xsd:string */
	char *subject;	/* optional element of type xsd:string */
	char *body;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (133)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (134)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (136)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (139)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (140)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 swad__createAccount(struct soap*, char *userNickname, char *userEmail, char *userID, char *userPassword, char *appKey, struct swad__createAccountOutput *createAccountOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__loginByUserPasswordKey(struct soap*, char *userID, char *userPassword, char *appKey, struct swad__loginByUserPasswordKeyOutput *loginByUserPasswordKeyOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__loginBySessionKey(struct soap*, char *sessionID, char *appKey, struct swad__loginBySessionKeyOutput *loginBySessionKeyOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getNewPassword(struct soap*, char *userID, char *appKey, struct swad__getNewPasswordOutput *getNewPasswordOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getCourses(struct soap*, char *wsKey, struct swad__getCoursesOutput *getCoursesOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getCourseInfo(struct soap*, char *wsKey, int courseCode, char *infoType, struct swad__getCourseInfoOutput *getCourseInfoOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getGroupTypes(struct soap*, char *wsKey, int courseCode, struct swad__getGroupTypesOutput *getGroupTypesOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getGroups(struct soap*, char *wsKey, int courseCode, struct swad__getGroupsOutput *getGroupsOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__sendMyGroups(struct soap*, char *wsKey, int courseCode, char *myGroups, struct swad__sendMyGroupsOutput *sendMyGroupsOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getDirectoryTree(struct soap*, char *wsKey, int courseCode, int groupCode, int treeCode, struct swad__getDirectoryTreeOutput *getDirectoryTreeOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getFile(struct soap*, char *wsKey, int fileCode, struct swad__getFileOutput *getFileOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getMarks(struct soap*, char *wsKey, int fileCode, struct swad__getMarksOutput *getMarksOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getTestConfig(struct soap*, char *wsKey, int courseCode, struct swad__getTestConfigOutput *getTestConfigOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getTests(struct soap*, char *wsKey, int courseCode, long beginTime, struct swad__getTestsOutput *getTestsOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getUsers(struct soap*, char *wsKey, int courseCode, int groupCode, int userRole, struct swad__getUsersOutput *getUsersOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getAttendanceEvents(struct soap*, char *wsKey, int courseCode, struct swad__getAttendanceEventsOutput *getAttendanceEventsOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__sendAttendanceEvent(struct soap*, char *wsKey, int attendanceEventCode, int courseCode, int hidden, int startTime, int endTime, int commentsTeachersVisible, char *title, char *text, char *groups, struct swad__sendAttendanceEventOutput *sendAttendanceEventOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getAttendanceUsers(struct soap*, char *wsKey, int attendanceEventCode, struct swad__getAttendanceUsersOutput *getAttendanceUsersOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__sendAttendanceUsers(struct soap*, char *wsKey, int attendanceEventCode, char *users, int setOthersAsAbsent, struct swad__sendAttendanceUsersOutput *sendAttendanceUsersOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__getNotifications(struct soap*, char *wsKey, long beginTime, struct swad__getNotificationsOutput *getNotificationsOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__markNotificationsAsRead(struct soap*, char *wsKey, char *notifications, struct swad__markNotificationsAsReadOutput *markNotificationAsReadOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__sendNotice(struct soap*, char *wsKey, int courseCode, char *body, struct swad__sendNoticeOutput *sendNoticeOut);

SOAP_FMAC5 int SOAP_FMAC6 swad__sendMessage(struct soap*, char *wsKey, int messageCode, char *to, char *subject, char *body, struct swad__sendMessageOutput *sendMessageOut);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__createAccount(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__loginByUserPasswordKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__loginBySessionKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getNewPassword(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getCourses(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getCourseInfo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getGroupTypes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getGroups(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendMyGroups(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getDirectoryTree(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getFile(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getMarks(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getTestConfig(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getTests(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getUsers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getAttendanceEvents(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendAttendanceEvent(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getAttendanceUsers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendAttendanceUsers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__getNotifications(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__markNotificationsAsRead(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendNotice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_swad__sendMessage(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
